import type { AppData, ArenaScore, ScoreEntry } from '../types';

const DAY=86_400_000,clamp=(v:number,min=0,max=1)=>Math.min(max,Math.max(min,v)),round=Math.round;
const key=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,day=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),d.getDate()),add=(d:Date,n:number)=>new Date(d.getTime()+n*DAY),between=(v:string,a:Date,b:Date)=>v>=key(a)&&v<=key(b);
const sessions=(data:AppData,a:Date,b:Date)=>data.sessions.filter(v=>between(v.date,a,b)&&v.seconds>0),seconds=(data:AppData,a:Date,b:Date)=>sessions(data,a,b).reduce((s,v)=>s+Math.max(0,v.seconds),0),plans=(data:AppData,a:Date,b:Date)=>[...Object.entries(data.calendar).filter(([d])=>between(d,a,b)).flatMap(([,v])=>v.plans??[]),...data.dailyDrills.filter(v=>between(v.date,a,b))];
const rate=(yes:number,total:number)=>total?yes/total:null,sample=(value:number|null,n:number)=>value===null?null:value*clamp(n/5);
const weighted=(items:{value:number|null;max:number}[],cap:number)=>{const available=items.filter((v):v is {value:number;max:number}=>v.value!==null);if(!available.length)return 0;return round(clamp(available.reduce((s,v)=>s+clamp(v.value)*v.max,0)/available.reduce((s,v)=>s+v.max,0))*cap)};
const subjectAverages=(rows:ScoreEntry[])=>['korean','math','english'].map(subject=>{const v=rows.map(r=>r[subject as keyof ScoreEntry]).filter((x):x is number=>typeof x==='number'&&Number.isFinite(x));return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}),average=(v:(number|null)[])=>{const found=v.filter((x):x is number=>x!==null);return found.length?found.reduce((a,b)=>a+b,0)/found.length:null},stability=(rates:number[])=>{if(rates.length<2)return null;const mean=rates.reduce((a,b)=>a+b,0)/rates.length;return clamp(1-Math.sqrt(rates.reduce((s,v)=>s+(v-mean)**2,0)/rates.length))};

export type LearningIntelligenceMetrics={reviewSuccesses:number;reviewCompleted:number;drillSuccesses:number;drillCompleted:number;repeatedErrorsCurrent:number;repeatedErrorsPrevious:number;masteryCurrent?:number|null;masteryPrevious?:number|null;reviewScheduleCredits:number;reviewScheduleCompleted:number};

export function calculateArenaScore(data:AppData,now=new Date(),li?:LearningIntelligenceMetrics):ArenaScore{
 const end=day(now),start=add(end,-13),previousStart=add(end,-27),previousEnd=add(end,-14),weekStart=add(end,-((end.getDay()+6)%7)),availableDays=Math.max(1,Math.min(7,Math.floor((end.getTime()-weekStart.getTime())/DAY)+1));
 const weekPlans=plans(data,weekStart,end),planExecution=rate(weekPlans.filter(v=>v.done).length,weekPlans.length),activeDays=new Set(sessions(data,weekStart,end).map(v=>v.date)).size,currentSeconds=seconds(data,weekStart,end),pastWeeks=[1,2,3,4].map(n=>seconds(data,add(weekStart,-7*n),add(weekStart,-7*n+6))).filter(Boolean).sort((a,b)=>a-b),target=pastWeeks.length?pastWeeks[Math.floor(pastWeeks.length/2)]:weekPlans.length?weekPlans.length*3600:0,studyGoal=target?clamp(currentSeconds/target):null;
 const execution=weighted([{value:planExecution,max:100},{value:studyGoal,max:60},{value:activeDays/availableDays,max:40}],200);
 const retries=data.wrongAnswerDrills.flatMap(v=>v.retries??[]),retryDone=retries.filter(v=>v.completedDate).length,drillRate=li?.drillCompleted?sample(li.drillSuccesses/li.drillCompleted,li.drillCompleted):sample(rate(retryDone,retries.length),retries.length),reviewRate=li?.reviewCompleted?sample(li.reviewSuccesses/li.reviewCompleted,li.reviewCompleted):null,repeated=li&&li.repeatedErrorsPrevious>0?clamp((li.repeatedErrorsPrevious-li.repeatedErrorsCurrent)/li.repeatedErrorsPrevious):null,masteryGrowth=li?.masteryCurrent!=null&&li?.masteryPrevious!=null?clamp((li.masteryCurrent-li.masteryPrevious)/.25):null;
 const mastery=weighted([{value:reviewRate,max:100},{value:drillRate,max:80},{value:repeated,max:70},{value:masteryGrowth,max:50}],300);
 const currentScores=data.scores.filter(v=>between(v.date,start,end)),previousScores=data.scores.filter(v=>between(v.date,previousStart,previousEnd)),currentSubjects=subjectAverages(currentScores),previousSubjects=subjectAverages(previousScores),currentPerformance=average(currentSubjects),changes=currentSubjects.map((v,i)=>v===null||previousSubjects[i]===null?null:clamp((v-(previousSubjects[i] as number)+10)/20)),performanceChange=average(changes),goals=data.weeklyCapabilityGoals.filter(v=>between(v.weekStart,start,end)),goalRate=rate(goals.filter(v=>v.done).length,goals.length),performance=weighted([{value:currentPerformance===null?null:clamp(currentPerformance/100),max:80},{value:performanceChange,max:80},{value:goalRate,max:40}],200);
 const active14=new Set(sessions(data,start,end).map(v=>v.date)).size,dailyRates=Array.from({length:14},(_,i)=>{const p=plans(data,add(start,i),add(start,i));return p.length?p.filter(v=>v.done).length/p.length:null}).filter((v):v is number=>v!==null),schedule=li?.reviewScheduleCompleted?li.reviewScheduleCredits/li.reviewScheduleCompleted:null,consistency=weighted([{value:active14/14,max:60},{value:stability(dailyRates),max:50},{value:schedule,max:40}],150);
 const currentPeriodPlans=plans(data,start,end),previousPeriodPlans=plans(data,previousStart,previousEnd),currentPlan=rate(currentPeriodPlans.filter(v=>v.done).length,currentPeriodPlans.length),previousPlan=rate(previousPeriodPlans.filter(v=>v.done).length,previousPeriodPlans.length),executionGrowth=currentPlan!==null&&previousPlan!==null?clamp((currentPlan-previousPlan+.25)/.5):null,currentActive=active14/14,previousActive=new Set(sessions(data,previousStart,previousEnd).map(v=>v.date)).size/14,consistencyGrowth=clamp((currentActive-previousActive+.25)/.5),growth=weighted([{value:masteryGrowth,max:60},{value:performanceChange,max:50},{value:executionGrowth,max:25},{value:consistencyGrowth,max:15}],150),breakdown={execution,mastery,performance,consistency,growth};
 const weakAreas=[['계획 실행률',planExecution??0],['Review 성공',reviewRate??0],['반복 오답 감소',repeated??0],['성과 개선',performanceChange??0]].sort((a,b)=>Number(a[1])-Number(b[1])).slice(0,2).map(v=>String(v[0])),nextActions=weakAreas.map(v=>v==='Review 성공'?'예정된 D+3/D+7/D+14 Review를 결과와 함께 완료하세요.':v==='반복 오답 감소'?'최근 반복 실패 Core Rule 하나를 Drill로 다시 검증하세요.':v==='계획 실행률'?'오늘 계획 중 가장 중요한 한 항목을 완료하세요.':'최근 시험 한 과목의 실패 원인을 Core Rule과 연결하세요.');
 return {total:Object.values(breakdown).reduce((a,b)=>a+b,0),scoreVersion:2,breakdown,metrics:{currentWeekSeconds:currentSeconds,previousWeekSeconds:seconds(data,add(weekStart,-7),add(weekStart,-1)),planExecutionRate:round((planExecution??0)*100),studyGoalRate:studyGoal===null?null:round(studyGoal*100),activeDays,availableDays,streakDays:active14,reviewSuccessRate:reviewRate===null?null:round(reviewRate*100),drillSuccessRate:drillRate===null?null:round(drillRate*100),repeatedErrorReduction:repeated===null?null:round(repeated*100),coreRuleMasteryGrowth:masteryGrowth===null?null:round(masteryGrowth*100),performanceChange:performanceChange===null?null:round((performanceChange-.5)*200)/10,capabilityGoalRate:goalRate===null?null:round(goalRate*100),reviewScheduleRate:schedule===null?null:round(schedule*100),drillCompletionRate:drillRate===null?0:round(drillRate*100),completedTripleDrills:data.wrongAnswerDrills.filter(v=>(v.retries??[]).length>=3&&(v.retries??[]).every(r=>r.completedDate)).length,weaknessImprovementRate:repeated===null?0:round(repeated*100),growthRate:round(((executionGrowth??.5)-.5)*2000)/10,weakAreas,nextActions},calculatedAt:now.toISOString()};
}
