import type { AppData, Subject } from '../types';
import { parsePlannedMinutes } from './plannedTime';
import { loadCloudflareConfig } from './cloudflare';
import type { TeacherSignal } from './teacherSignals';

export type FeedbackContextType = 'general'|'mock_exam'|'wrong_answer'|'drill'|'weekly_goal'|'subject_progress'|'statistics'|'resource'|'weekly_plan';
export type Feedback = { id:string; type:'subject'|'academic_management'; subject?:Subject; title?:string; categories?:string[]; status:'needs_improvement'|'normal'|'stable'; progress:'active'|'achieved'|'replaced'|'archived'; bottleneck?:string; observation?:string; action?:string; success_criterion?:string; comment?:string; teacher_name?:string; acknowledgedByStudent:boolean; linked_weekly_goal_id?:string; linked_daily_drill_id?:string; context_type?:FeedbackContextType; context_target_id?:string; created_at:string; signal?:TeacherSignal };
const api = async <T>(path:string, method='GET', body?:unknown):Promise<T> => { const config=loadCloudflareConfig(), base=config.url.replace(/\/+$/,''); if(!base||!config.token)throw new Error('로그인이 필요합니다.'); const response=await fetch(base+path,{method,headers:{Authorization:`Bearer ${config.token}`,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})}); const value=await response.json() as T&{error?:string}; if(!response.ok)throw new Error(value.error||`요청 실패 (${response.status})`); return value; };
export const studentFeedback=()=>api<{feedback:Feedback[]}>('/api/collab/student/feedback');
export const acknowledgeFeedback=(id:string)=>api(`/api/collab/student/feedback/${id}/acknowledge`,'POST');
export const linkFeedback=(id:string,target:'daily_drill'|'weekly_goal',linkedId:string)=>api(`/api/collab/student/feedback/${id}/apply`,'POST',{target,linkedId});
export const summarizeTeacherFeedback=(data:AppData, feedback:Feedback[])=>api<{message:string}>('/api/ai/teacher-feedback-summary','POST',{context:{today:{plannedMinutes:Object.values(data.calendar).flatMap(day=>day.plans??[]).reduce((total,plan)=>total+parsePlannedMinutes(plan.quantity),0),completedMinutes:data.sessions.filter(item=>item.date===new Date().toISOString().slice(0,10)).reduce((total,item)=>total+Math.round(item.seconds/60),0)},subjectFeedback:feedback.filter(item=>item.type==='subject'&&item.progress==='active').map(item=>({subject:item.subject,bottleneck:item.bottleneck,action:item.action,successCriterion:item.success_criterion})),academicFeedback:feedback.filter(item=>item.type==='academic_management'&&item.progress==='active').map(item=>({bottleneck:item.bottleneck,action:item.action,successCriterion:item.success_criterion})),weeklyGoals:data.weeklyCapabilityGoals.filter(item=>!item.done).slice(0,5).map(item=>({subject:item.subject,ability:item.ability,successCriterion:item.successCriterion})),recentBottlenecks:[...new Set(data.wrongAnswerDrills.map(item=>item.bottleneck).filter(Boolean))].slice(0,5)}});
export { makeDailyDrill, makeWeeklyGoal } from './feedbackDrafts';
