import assert from 'node:assert/strict';
import { test } from 'node:test';
import { DatabaseSync } from 'node:sqlite';
import { createHash, pbkdf2Sync } from 'node:crypto';
import { readFileSync } from 'node:fs';
import worker from '../worker/src/index.ts';
import { calculateArenaScore } from '../src/lib/arenaScore.ts';

if(typeof crypto.subtle.timingSafeEqual!=='function')Object.defineProperty(crypto.subtle,'timingSafeEqual',{value:(a,b)=>{const left=new Uint8Array(a.buffer??a,a.byteOffset??0,a.byteLength),right=new Uint8Array(b.buffer??b,b.byteOffset??0,b.byteLength);if(left.length!==right.length)return false;let diff=0;for(let i=0;i<left.length;i++)diff|=left[i]^right[i];return diff===0;}});

const hash = value => createHash('sha256').update(value).digest('hex');
const password = (value, salt, iterations=100000) => pbkdf2Sync(value,salt,iterations,32,'sha256').toString('hex');
const wrap=(stmt,args=[])=>({bind:(...values)=>wrap(stmt,values),first:async()=>stmt.get(...args)??null,run:async()=>stmt.run(...args),all:async()=>({results:stmt.all(...args)})});
const emptyData=()=>({calendar:{},sessions:[],mockSchedule:[],journals:{},scores:[],resources:[],goals:[],weeklyCapabilityGoals:[],wrongAnswerDrills:[],dailyDrills:[],monthlyPlans:[],notionPages:[],routine:[],quotes:[],examDate:'2026-11-19',googleClientId:'',plaire:{},trinity:[]});

function harness(){
 const db=new DatabaseSync(':memory:');
 db.exec(`CREATE TABLE users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT NOT NULL UNIQUE,password_hash TEXT,salt TEXT,is_admin INTEGER NOT NULL DEFAULT 0,must_change_password INTEGER NOT NULL DEFAULT 0,password_changed_at TEXT,created_at TEXT NOT NULL);
 CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
 CREATE TABLE api_tokens(token_hash TEXT PRIMARY KEY,user_id INTEGER NOT NULL,label TEXT NOT NULL,created_at TEXT NOT NULL,revoked_at TEXT);
 CREATE TABLE learning_state(user_id INTEGER PRIMARY KEY,payload TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE learning_state_history(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,payload TEXT NOT NULL,saved_at TEXT NOT NULL);`);
 for(const name of ['0001_support_portal.sql','0002_feedback_collaboration.sql','0003_feedback_context.sql','0008_security_hardening.sql','0009_arena_14_day_seasons.sql'])db.exec(readFileSync(new URL(`../worker/migrations/${name}`,import.meta.url),'utf8'));
 const salt='student-salt';
 db.prepare('INSERT INTO users(id,username,password_hash,salt,password_iterations,active,arena_public_id,created_at) VALUES(1,?,?,?,?,1,?,?)').run('student-a',password('correct-password',salt),salt,100000,'arena_a','2026-09-01');
 db.prepare('INSERT INTO users(id,username,password_hash,salt,password_iterations,active,arena_public_id,created_at) VALUES(2,?,?,?,?,1,?,?)').run('student-b',password('correct-password',salt),salt,100000,'arena_b','2026-09-01');
 db.prepare('INSERT INTO learning_state VALUES(1,?,?)').run(JSON.stringify({...emptyData(),sessions:[{id:'a',date:'2026-09-12',subject:'수학',seconds:3600}],wrongAnswerDrills:[{id:'wa',date:'2026-09-12',subject:'수학',source:'x',question:'1',wrongJudgment:'private',missedCue:'private',correction:'check',transfer:'new',bottleneck:'조건',retries:[]}]}),'2026-09-12');
 db.prepare('INSERT INTO learning_state VALUES(2,?,?)').run(JSON.stringify({...emptyData(),sessions:[{id:'b',date:'2026-09-12',subject:'영어',seconds:7200}]}),'2026-09-12');
 const env={DB:{prepare:sql=>wrap(db.prepare(sql)),batch:async list=>{db.exec('BEGIN');try{const out=[];for(const statement of list)out.push(await statement.run());db.exec('COMMIT');return out;}catch(error){db.exec('ROLLBACK');throw error;}}},ALLOWED_ORIGIN:'https://trinityos.mcv.kr',ENVIRONMENT:'production',SYNC_TOKEN:'setup'};
 const session=(token,userId=1,expires=new Date(Date.now()+86400000).toISOString())=>db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(hash(token),userId,expires,new Date().toISOString());
 const call=(path,{method='GET',token,body,origin,headers={}}={})=>worker.fetch(new Request(`https://worker.test${path}`,{method,headers:{...(token?{Authorization:`Bearer ${token}`} : {}),...(origin?{Origin:origin}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{}),...headers},...(body!==undefined?{body:typeof body==='string'?body:JSON.stringify(body)}:{})}),env);
 return {db,env,session,call};
}

test('unauthenticated user cannot access /api/sync',async()=>{const h=harness();assert.equal((await h.call('/api/sync')).status,401);});
test('student session reads only its own learning_state',async()=>{const h=harness();h.session('a',1);const body=await(await h.call('/api/sync',{token:'a'})).json();assert.equal(body.data.sessions[0].id,'a');assert(!JSON.stringify(body).includes('"id":"b"'));});
test('teacher cannot access another student learning data',async()=>{const h=harness();h.db.prepare("INSERT INTO support_accounts(id,username,role,collaboration_role,password_hash,salt,password_iterations,created_at) VALUES('ta','teacher-a','tutor','subject_teacher','x','x',310000,'x')").run();h.db.prepare("INSERT INTO support_sessions VALUES(?, 'ta', ?)").run(hash('teacher'),new Date(Date.now()+86400000).toISOString());h.db.prepare("INSERT INTO student_support_assignments VALUES('as',1,'ta','subject_teacher','수학','{}','x')").run();assert.equal((await h.call('/api/collab/students/arena_b/data',{token:'teacher'})).status,403);});
test('parent cannot access unassigned student',async()=>{const h=harness();h.db.prepare("INSERT INTO support_accounts(id,username,role,collaboration_role,password_hash,salt,password_iterations,created_at) VALUES('pa','parent-a','parent','parent','x','x',310000,'x')").run();h.db.prepare("INSERT INTO support_sessions VALUES(?, 'pa', ?)").run(hash('parent'),new Date(Date.now()+86400000).toISOString());assert.equal((await h.call('/api/collab/students/arena_b/data',{token:'parent'})).status,403);});
test('parent projection excludes restricted academic detail',async()=>{const h=harness();h.db.prepare("INSERT INTO support_accounts(id,username,role,collaboration_role,password_hash,salt,password_iterations,created_at) VALUES('pa','parent-a','parent','parent','x','x',310000,'x')").run();h.db.prepare("INSERT INTO support_sessions VALUES(?, 'pa', ?)").run(hash('parent'),new Date(Date.now()+86400000).toISOString());h.db.prepare("INSERT INTO student_support_assignments VALUES('as',1,'pa','parent',NULL,?,'x')").run(JSON.stringify({viewSessions:true,viewScores:true,viewCalendar:true,viewWeeklyGoals:true,viewDrills:true}));const body=await(await h.call('/api/collab/students/arena_a/data',{token:'parent'})).json();assert.deepEqual(body.data.wrongAnswerDrills,[]);assert.deepEqual(body.data.plaire,[]);assert(!JSON.stringify(body).includes('wrongJudgment'));});
test('subject teacher receives only assigned subject data',async()=>{const h=harness();h.db.prepare("INSERT INTO support_accounts(id,username,role,collaboration_role,password_hash,salt,password_iterations,created_at) VALUES('ta','teacher-a','tutor','subject_teacher','x','x',310000,'x')").run();h.db.prepare("INSERT INTO support_sessions VALUES(?, 'ta', ?)").run(hash('teacher'),new Date(Date.now()+86400000).toISOString());h.db.prepare("INSERT INTO student_support_assignments VALUES('as',1,'ta','subject_teacher','수학',?,'x')").run(JSON.stringify({viewSessions:true}));const body=await(await h.call('/api/collab/students/arena_a/data',{token:'teacher'})).json();assert(body.data.sessions.every(item=>item.subject==='수학'));});
test('revoked session cannot access API',async()=>{const h=harness();h.session('gone');h.db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash('gone'));assert.equal((await h.call('/api/sync',{token:'gone'})).status,401);});
test('password change invalidates old sessions',async()=>{const h=harness();h.session('old');h.session('other');const response=await h.call('/api/auth/change-password',{method:'POST',token:'old',body:{currentPassword:'correct-password',newPassword:'new-password-123'}});assert.equal(response.status,200);assert.equal((await h.call('/api/sync',{token:'other'})).status,401);});
test('logout invalidates current session',async()=>{const h=harness();h.session('logout');assert.equal((await h.call('/api/auth/logout',{method:'POST',token:'logout',body:{}})).status,200);assert.equal((await h.call('/api/sync',{token:'logout'})).status,401);});
test('expired session returns 401',async()=>{const h=harness();h.session('expired',1,'2020-01-01T00:00:00.000Z');assert.equal((await h.call('/api/sync',{token:'expired'})).status,401);});
test('invalid Origin is rejected',async()=>{const h=harness();const response=await h.call('/api/auth/login',{method:'POST',origin:'https://evil.test',body:{username:'student-a',password:'correct-password'}});assert.equal(response.status,403);});
test('login brute force returns 429',async()=>{const h=harness();for(let i=0;i<8;i++)assert.equal((await h.call('/api/auth/login',{method:'POST',body:{username:'student-a',password:'wrong'}})).status,401);assert.equal((await h.call('/api/auth/login',{method:'POST',body:{username:'student-a',password:'wrong'}})).status,429);});
test('user enumeration is not possible from auth response',async()=>{const h=harness();const wrong=await h.call('/api/auth/login',{method:'POST',body:{username:'student-a',password:'wrong'}}),missing=await h.call('/api/auth/login',{method:'POST',body:{username:'missing',password:'wrong'}});assert.equal(wrong.status,missing.status);assert.deepEqual(await wrong.json(),await missing.json());});
test('Arena score cannot be submitted manually',async()=>{const h=harness();h.session('a');assert.equal((await h.call('/api/arena/score',{method:'POST',token:'a',body:{breakdown:{execution:300},calculatedAt:'2099-01-01'}})).status,405);});
test('Arena score is generated from server state and server time',async()=>{const h=harness();h.session('a');const before=Date.now(),response=await h.call('/api/arena/recalculate',{method:'POST',token:'a',body:{total:9999,calculatedAt:'2099-01-01'}}),after=Date.now();assert.equal(response.status,200);const body=await response.json(),data=JSON.parse(h.db.prepare('SELECT payload FROM learning_state WHERE user_id=1').get().payload),expected=calculateArenaScore(data,new Date(body.score.calculatedAt));assert.equal(body.score.total,expected.total);assert(new Date(body.score.calculatedAt).getTime()>=before&&new Date(body.score.calculatedAt).getTime()<=after);});
test('two Arena profiles appear in ranking and can become rivals',async()=>{const h=harness();h.session('a',1);h.session('b',2);for(const [token,nickname] of [['a','Alpha'],['b','Beta']]){assert.equal((await h.call('/api/arena/profile',{method:'PUT',token,body:{nickname,studyGoal:[]}})).status,200);assert.equal((await h.call('/api/arena/recalculate',{method:'POST',token})).status,200);}const ranking=await(await h.call('/api/arena/ranking',{token:'a'})).json();assert.equal(ranking.ranking.length,2);const beta=ranking.ranking.find(row=>row.nickname==='Beta');assert.equal(beta.userId,'arena_b');assert.equal((await h.call('/api/arena/rivals',{method:'POST',token:'a',body:{rivalUserId:beta.userId}})).status,200);});
test('Arena uses a shared 14-day season with a private custom name',async()=>{const h=harness();h.session('a',1);h.session('b',2);const first=await(await h.call('/api/arena',{token:'a'})).json();assert.equal((Date.parse(first.season.endsAt)-Date.parse(first.season.startsAt))/86400000,13);assert.match(first.season.id,/^arena-14d-\d{4}-\d{2}-\d{2}$/);const renamed=await(await h.call('/api/arena/season',{method:'PUT',token:'a',body:{name:'수학 완결성 스프린트'}})).json();assert.equal(renamed.season.name,'수학 완결성 스프린트');const mine=await(await h.call('/api/arena',{token:'a'})).json(),other=await(await h.call('/api/arena',{token:'b'})).json();assert.equal(mine.season.id,other.season.id);assert.equal(mine.season.name,'수학 완결성 스프린트');assert.notEqual(other.season.name,mine.season.name);});
test('private Arena group requires invite code',async()=>{const h=harness();h.session('a',1);h.session('b',2);const created=await(await h.call('/api/arena/groups',{method:'POST',token:'a',body:{name:'private',type:'custom',visibility:'private'}})).json();assert.equal((await h.call('/api/arena/groups/join',{method:'POST',token:'b',body:{groupIdOrCode:created.group.id}})).status,403);assert.equal((await h.call('/api/arena/groups/join',{method:'POST',token:'b',body:{groupIdOrCode:created.group.inviteCode}})).status,200);});
test('API token cannot change password',async()=>{const h=harness();h.db.prepare("INSERT INTO api_tokens(token_hash,user_id,label,scopes,created_at) VALUES(?,1,'test','sync:read,sync:write','x')").run(hash('pat'));assert.equal((await h.call('/api/auth/change-password',{method:'POST',token:'pat',body:{currentPassword:'correct-password',newPassword:'new-password-123'}})).status,403);});
test('admin API token cannot manage support accounts',async()=>{const h=harness();h.db.prepare('UPDATE users SET is_admin=1 WHERE id=1').run();h.db.prepare("INSERT INTO api_tokens(token_hash,user_id,label,scopes,created_at) VALUES(?,1,'admin-pat','sync:read,sync:write','x')").run(hash('admin-pat'));assert.equal((await h.call('/api/support/accounts',{token:'admin-pat'})).status,401);});
test('disabled support account cannot login',async()=>{const h=harness();const salt='s';h.db.prepare("INSERT INTO support_accounts(id,username,role,collaboration_role,password_hash,salt,password_iterations,active,created_at) VALUES('ta','teacher','tutor','subject_teacher',?,?,310000,0,'x')").run(password('support-password',salt,310000),salt);assert.equal((await h.call('/api/support/login',{method:'POST',body:{username:'teacher',password:'support-password',role:'subject_teacher'}})).status,401);});
test('disabled support account existing session cannot access data',async()=>{const h=harness();h.db.prepare("INSERT INTO support_accounts(id,username,role,collaboration_role,password_hash,salt,password_iterations,active,created_at) VALUES('ta','teacher','tutor','subject_teacher','x','x',310000,0,'x')").run();h.db.prepare("INSERT INTO support_sessions VALUES(?, 'ta', ?)").run(hash('support'),new Date(Date.now()+86400000).toISOString());assert.equal((await h.call('/api/support/data',{token:'support'})).status,401);});
test('oversized /api/sync is rejected',async()=>{const h=harness();h.session('a');const response=await h.call('/api/sync',{method:'PUT',token:'a',body:'{}',headers:{'Content-Length':String(5*1024*1024+1)}});assert.equal(response.status,413);});
test('malicious object keys are rejected',async()=>{const h=harness();h.session('a');const body=`{"data":{"calendar":{},"sessions":[],"mockSchedule":[],"journals":{},"scores":[],"resources":[],"goals":[],"weeklyCapabilityGoals":[],"wrongAnswerDrills":[],"dailyDrills":[],"monthlyPlans":[],"notionPages":[],"routine":[],"quotes":[],"trinity":[],"plaire":{},"__proto__":{"polluted":true}}}`;assert.equal((await h.call('/api/sync',{method:'PUT',token:'a',body})).status,400);});
