import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { support, projection, publicExamPath } from '../worker/src/support.ts';
import { createHash, randomBytes, pbkdf2Sync } from 'node:crypto';
import { registerHooks } from 'node:module';
registerHooks({resolve(specifier,context,next){try{return next(specifier,context);}catch(e){if(specifier.startsWith('./')||specifier.startsWith('../'))return next(specifier+'.ts',context);throw e;}}});
const db=new DatabaseSync(':memory:');
db.exec("CREATE TABLE learning_state(id INTEGER PRIMARY KEY,payload TEXT,updated_at TEXT); CREATE TABLE users(id INTEGER PRIMARY KEY,username TEXT);INSERT INTO users VALUES(1,'keep-me')");
const sql=readFileSync(new URL('../worker/migrations/0001_support_portal.sql',import.meta.url),'utf8');
db.exec(sql);db.exec(sql);
assert.equal(db.prepare('SELECT username FROM users').get().username,'keep-me');
const wrap=(stmt,args=[])=>({bind:(...values)=>wrap(stmt,values),first:async()=>stmt.get(...args)??null,run:async()=>stmt.run(...args),all:async()=>({results:stmt.all(...args)})});
const env={DB:{prepare:sql=>wrap(db.prepare(sql)),batch:async list=>{db.exec('BEGIN');try{const out=[];for(const statement of list)out.push(await statement.run());db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}}};
const h={json:(v,status=200)=>new Response(JSON.stringify(v),{status}),sha256:async s=>createHash('sha256').update(s).digest('hex'),randomHex:(n=32)=>randomBytes(n).toString('hex'),passwordHash:async(p,s)=>pbkdf2Sync(p,s,100000,32,'sha256').toString('hex')};
async function call(path,method='GET',body,token='',owner=false){
 return support(new Request('https://test'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env,owner,'https://app',h);
}
const data={resources:[{subject:'수학',name:'math',done:1,total:3},{subject:'국어',name:'PRIVATE'}],sessions:[{subject:'수학',date:'2026-09-07',seconds:90,note:'PRIVATE'},{subject:'국어',seconds:100}],calendar:{'2026-09-07':{date:'2026-09-07',reflection:'PRIVATE',plans:[{subject:'수학',title:'math'},{subject:'영어',title:'PRIVATE'}]}},scores:[{id:'x',subject:'국어',name:'test',math:70,overallReview:'PRIVATE',reviews:{국어:{observation:'PRIVATE'},수학:{observation:'math'}}}],notionPages:[{content:'PRIVATE'}],journals:{private:'PRIVATE'},plaire:{private:'PRIVATE'},trinity:[],weeklyCapabilityGoals:[],wrongAnswerDrills:[],dailyDrills:[],monthlyPlans:[]};
assert(!JSON.stringify(projection(data,'tutor')).includes('PRIVATE'));
assert.equal(projection(data,'parent').resources.length,2);
assert.equal(publicExamPath('2026/평가원/수학.pdf'),'exams/2026/%ED%8F%89%EA%B0%80%EC%9B%90/%EC%88%98%ED%95%99.pdf');
for(const key of ['../math.pdf','/math.pdf','https://evil.test/math.pdf','folder//math.pdf','math.pdf?x=1'])assert.equal(publicExamPath(key),null);
db.prepare('INSERT INTO learning_state VALUES(1,?,?)').run(JSON.stringify(data),'2026-09-07');
assert.equal((await call('/api/support/data')).status,401);
assert.equal((await call('/api/support/accounts','POST',{username:'teacher',password:'correct-password-123',role:'tutor'},'',true)).status,201);
assert.equal((await call('/api/support/login','POST',{username:'teacher',password:'wrong',role:'tutor'})).status,401);
const auth=await (await call('/api/support/login','POST',{username:'teacher',password:'correct-password-123',role:'tutor'})).json();
assert(auth.token);const token=auth.token;
const worker=(await import('../worker/src/index.ts')).default;
for(const method of ['GET','PUT']) {
 const denied=await worker.fetch(new Request('https://test/api/sync',{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(method==='PUT'?{body:JSON.stringify({data:{}})}:{})}),env);
 assert.equal(denied.status,401,'Tutor must never read or overwrite raw student sync');
}
const routed=await worker.fetch(new Request('https://test/api/support/data',{headers:{Authorization:'Bearer '+token}}),env);
assert.equal(routed.status,200);
assert.equal((await call('/api/support/accounts','GET',null,token)).status,403);
assert.equal((await call('/api/support/data','PUT',{},token)).status,404);
const shared=await(await call('/api/support/data','GET',null,token)).json();
assert(!JSON.stringify(shared).includes('PRIVATE'));
assert.equal((await call('/api/support/comments','POST',{target:'주간 총평',body:'잘했습니다'},token)).status,201);
assert.equal((await(await call('/api/support/comments','GET',null,'',true)).json()).comments.length,1);
assert.equal((await call('/api/exams','POST',{title:'math',agency:'평가원',year:2026,subject:'수학',object_key:'math.pdf'},token)).status,403);
assert.equal((await call('/api/exams','POST',{title:'math',agency:'평가원',year:2026,subject:'수학',object_key:'math.pdf'},'',true)).status,201);
const docs=await(await call('/api/exams','GET',null,token)).json();
assert.equal(docs.documents.length,1);
assert.deepEqual(await(await call('/api/exams/'+docs.documents[0].id,'GET',null,token)).json(),{path:'exams/math.pdf',public:true});
const account=db.prepare("SELECT id FROM support_accounts WHERE username='teacher'").get();
await call('/api/support/accounts','PUT',{id:account.id},'',true);
assert.equal((await call('/api/support/data','GET',null,token)).status,401);
await call('/api/support/accounts','POST',{username:'guardian',password:'parent-password-123',role:'parent'},'',true);
const parent=await(await call('/api/support/login','POST',{username:'guardian',password:'parent-password-123',role:'parent'})).json();
assert.equal((await call('/api/exams','GET',null,parent.token)).status,403);
assert.equal((await call('/api/exams/'+docs.documents[0].id,'GET',null,parent.token)).status,403);
assert.equal((await call('/api/support/comments','GET',null,parent.token)).status,200);
assert.equal((await(await call('/api/support/comments','GET',null,parent.token)).json()).comments.length,0,'Do not expose tutor comments to parent automatically');
assert.equal((await call('/api/support/comments','POST',{target:'이번 주',body:'학습량 평가'},parent.token)).status,201);
await call('/api/support/logout','POST',{},parent.token);
assert.equal((await call('/api/support/data','GET',null,parent.token)).status,401);
console.log('PASS: additive migration, private-field filtering, role restrictions, comments, PDF access, revocation');
const {studyTotals}=await import('../src/lib/studyTotals.ts');
const totals=studyTotals([{id:'cross',date:'2026-09-07',subject:'수학',seconds:3600,segments:[{start:new Date('2026-09-07T23:30:00').toISOString(),end:new Date('2026-09-08T00:30:00').toISOString(),kind:'focus'},{start:new Date('2026-09-08T00:30:00').toISOString(),end:new Date('2026-09-08T00:40:00').toISOString(),kind:'break'}]},{id:'legacy',date:'2026-09-07',subject:'국어',seconds:600}]);
assert.equal(totals['2026-09-07'],2400);
assert.equal(totals['2026-09-08'],1800);
assert.equal(db.prepare('SELECT payload FROM learning_state').get().payload,JSON.stringify(data));
console.log('PASS: midnight allocation, break exclusion, legacy duration retention, original student payload unchanged');
