type Env={DB:D1Database};
type User={id:number;is_admin:number}|null;
type Helpers={json:(body:unknown,status?:number,origin?:string)=>Response;randomHex:(size?:number)=>string;boundedJson:<T>(request:Request,maxBytes?:number)=>Promise<T>};
const clean=(v:unknown,n=1200)=>typeof v==='string'?v.trim().slice(0,n):'';
const subjects=['korean','math','english'],institutions=['KICE','education_office','EBS','private','textbook','custom'],masteries=['input','understanding','reproduction','automated'];
const parseJson=(v:unknown,fallback:unknown=[])=>{try{return JSON.parse(String(v))}catch{return fallback}};
const entryOut=(row:Record<string,unknown>)=>({id:row.id,userId:row.user_id,subject:row.subject,year:row.year,month:row.month,institution:row.institution,institutionCustomName:row.institution_custom_name,examName:row.exam_name,sourceName:row.source_name,questionNumber:row.question_number,category:row.category,subcategory:row.subcategory,title:row.title,studiedAt:row.studied_at,masteryStatus:row.mastery_status,memo:row.memo,conditionSummary:row.condition_summary,firstThought:row.first_thought,representation:row.representation,solutionFlow:row.solution_flow,bottleneck:row.bottleneck,transfer:row.transfer,mainIdea:row.main_idea,structureSummary:row.structure_summary,keyExpression:row.key_expression,reviewEnabled:Boolean(row.review_enabled),createdAt:row.created_at,updatedAt:row.updated_at,wrongAnswerId:row.wrong_answer_id??null});
const annotationOut=(r:Record<string,unknown>)=>({id:r.id,archiveEntryId:r.archive_entry_id,color:r.color,type:r.type,text:r.text,order:r.sort_order,createdAt:r.created_at,updatedAt:r.updated_at});
const ruleOut=(r:Record<string,unknown>)=>({id:r.id,subject:r.subject,title:r.title,content:r.content,tags:parseJson(r.tags_json),masteryStatus:r.mastery_status,usageCount:Number(r.usage_count??0),createdAt:r.created_at,updatedAt:r.updated_at});
async function owner(db:D1Database,id:string,userId:number){return db.prepare('SELECT id FROM archive_entries WHERE id=? AND user_id=?').bind(id,userId).first()}
function entryValues(body:Record<string,unknown>){
 const subject=clean(body.subject,12),institution=clean(body.institution,30),mastery=clean(body.masteryStatus,30),year=Number(body.year),month=Number(body.month);
 if(!subjects.includes(subject)||!institutions.includes(institution)||!masteries.includes(mastery)||!Number.isInteger(year)||year<2000||year>2100||!Number.isInteger(month)||month<1||month>12||!clean(body.title,240)||!/^\d{4}-\d{2}-\d{2}/.test(clean(body.studiedAt,30)))throw new Error('INVALID_ENTRY');
 return [subject,year,month,institution,clean(body.institutionCustomName,120)||null,clean(body.examName,160),clean(body.sourceName,160),clean(body.questionNumber,40),clean(body.category,120),clean(body.subcategory,120),clean(body.title,240),clean(body.studiedAt,30),mastery,clean(body.memo,5000),clean(body.conditionSummary,3000)||null,clean(body.firstThought,3000)||null,clean(body.representation,3000)||null,clean(body.solutionFlow,5000)||null,clean(body.bottleneck,3000)||null,clean(body.transfer,3000)||null,clean(body.mainIdea,3000)||null,clean(body.structureSummary,3000)||null,clean(body.keyExpression,3000)||null,body.reviewEnabled===true?1:0] as const;
}
async function bundle(db:D1Database,userId:number,where:string,bind:unknown[]){
 const entries=await db.prepare(`SELECT e.*,w.wrong_answer_id FROM archive_entries e LEFT JOIN archive_wrong_answer_links w ON w.archive_entry_id=e.id WHERE e.user_id=? ${where} ORDER BY e.studied_at DESC,e.updated_at DESC LIMIT 300`).bind(userId,...bind).all<Record<string,unknown>>();
 const ids=entries.results.map(r=>String(r.id));if(!ids.length)return {entries:[]};const marks=ids.map(()=>'?').join(',');
 const [annotations,rules]=await Promise.all([db.prepare(`SELECT * FROM archive_annotations WHERE archive_entry_id IN (${marks}) ORDER BY sort_order,id`).bind(...ids).all<Record<string,unknown>>(),db.prepare(`SELECT l.archive_entry_id,r.* FROM archive_entry_core_rules l JOIN core_rules r ON r.id=l.core_rule_id WHERE l.archive_entry_id IN (${marks}) AND r.user_id=? ORDER BY r.title`).bind(...ids,userId).all<Record<string,unknown>>()]);
 return {entries:entries.results.map(row=>({...entryOut(row),annotations:annotations.results.filter(a=>a.archive_entry_id===row.id).map(annotationOut),coreRules:rules.results.filter(r=>r.archive_entry_id===row.id).map(ruleOut)}))};
}
export async function archive(request:Request,env:Env,user:User,origin:string,h:Helpers):Promise<Response|null>{
 const url=new URL(request.url),path=url.pathname,method=request.method;if(!path.startsWith('/api/archive'))return null;const out=(v:unknown,s=200)=>h.json(v,s,origin);if(!user)return out({error:'Unauthorized'},401);
 try{
  if(path==='/api/archive/entries'&&method==='GET'){
   const clauses:string[]=[],bind:unknown[]=[];for(const [key,column] of [['subject','e.subject'],['year','e.year'],['month','e.month'],['institution','e.institution'],['exam','e.exam_name'],['source','e.source_name'],['category','e.category'],['subcategory','e.subcategory'],['masteryStatus','e.mastery_status']] as const){const value=url.searchParams.get(key);if(value){clauses.push(`${column}=?`);bind.push(value)}}
   const color=url.searchParams.get('color'),core=url.searchParams.get('coreRule'),q=url.searchParams.get('q');if(color){clauses.push('EXISTS(SELECT 1 FROM archive_annotations a WHERE a.archive_entry_id=e.id AND a.color=?)');bind.push(color)}if(core==='true')clauses.push('EXISTS(SELECT 1 FROM archive_entry_core_rules l WHERE l.archive_entry_id=e.id)');if(core==='false')clauses.push('NOT EXISTS(SELECT 1 FROM archive_entry_core_rules l WHERE l.archive_entry_id=e.id)');if(q){clauses.push("(e.title LIKE ? OR e.memo LIKE ? OR e.exam_name LIKE ? OR e.source_name LIKE ? OR EXISTS(SELECT 1 FROM archive_annotations a WHERE a.archive_entry_id=e.id AND a.text LIKE ?))");for(let i=0;i<5;i++)bind.push(`%${q.slice(0,100)}%`)}return out(await bundle(env.DB,user.id,clauses.length?'AND '+clauses.join(' AND '):'',bind));
  }
  if(path==='/api/archive/entries'&&method==='POST'){const body=await h.boundedJson<Record<string,unknown>>(request),values=entryValues(body),id=h.randomHex(16),now=new Date().toISOString();await env.DB.prepare('INSERT INTO archive_entries(id,user_id,subject,year,month,institution,institution_custom_name,exam_name,source_name,question_number,category,subcategory,title,studied_at,mastery_status,memo,condition_summary,first_thought,representation,solution_flow,bottleneck,transfer,main_idea,structure_summary,key_expression,review_enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,user.id,...values,now,now).run();return out({id},201)}
  const item=path.match(/^\/api\/archive\/entries\/([^/]+)$/);if(item){const id=decodeURIComponent(item[1]);if(!await owner(env.DB,id,user.id))return out({error:'Not found'},404);if(method==='GET')return out(await bundle(env.DB,user.id,'AND e.id=?',[id]));if(method==='PATCH'){const body=await h.boundedJson<Record<string,unknown>>(request),v=entryValues(body);await env.DB.prepare('UPDATE archive_entries SET subject=?,year=?,month=?,institution=?,institution_custom_name=?,exam_name=?,source_name=?,question_number=?,category=?,subcategory=?,title=?,studied_at=?,mastery_status=?,memo=?,condition_summary=?,first_thought=?,representation=?,solution_flow=?,bottleneck=?,transfer=?,main_idea=?,structure_summary=?,key_expression=?,review_enabled=?,updated_at=? WHERE id=? AND user_id=?').bind(...v,new Date().toISOString(),id,user.id).run();return out({ok:true})}if(method==='DELETE'){await env.DB.prepare('DELETE FROM archive_entries WHERE id=? AND user_id=?').bind(id,user.id).run();return out({ok:true})}}
  if(path==='/api/archive/annotations'&&method==='POST'){const b=await h.boundedJson<Record<string,unknown>>(request),entryId=clean(b.archiveEntryId,80);if(!await owner(env.DB,entryId,user.id))return out({error:'Not found'},404);const text=clean(b.text,3000),color=clean(b.color,40),type=clean(b.type,80);if(!text||!color||!type)return out({error:'color, type, text are required'},400);const id=h.randomHex(16),now=new Date().toISOString();await env.DB.prepare('INSERT INTO archive_annotations VALUES(?,?,?,?,?,?,?,?)').bind(id,entryId,color,type,text,Number(b.order)||0,now,now).run();return out({id},201)}
  const annotation=path.match(/^\/api\/archive\/annotations\/([^/]+)$/);if(annotation){const id=decodeURIComponent(annotation[1]),row=await env.DB.prepare('SELECT a.id FROM archive_annotations a JOIN archive_entries e ON e.id=a.archive_entry_id WHERE a.id=? AND e.user_id=?').bind(id,user.id).first();if(!row)return out({error:'Not found'},404);if(method==='PATCH'){const b=await h.boundedJson<Record<string,unknown>>(request);await env.DB.prepare('UPDATE archive_annotations SET color=?,type=?,text=?,sort_order=?,updated_at=? WHERE id=?').bind(clean(b.color,40),clean(b.type,80),clean(b.text,3000),Number(b.order)||0,new Date().toISOString(),id).run();return out({ok:true})}if(method==='DELETE'){await env.DB.prepare('DELETE FROM archive_annotations WHERE id=?').bind(id).run();return out({ok:true})}}
  if(path==='/api/archive/rules'&&method==='GET'){const rows=await env.DB.prepare('SELECT r.*,COUNT(l.archive_entry_id) usage_count FROM core_rules r LEFT JOIN archive_entry_core_rules l ON l.core_rule_id=r.id WHERE r.user_id=? GROUP BY r.id ORDER BY r.updated_at DESC').bind(user.id).all<Record<string,unknown>>();return out({rules:rows.results.map(ruleOut)})}
  if(path==='/api/archive/rules'&&method==='POST'){const b=await h.boundedJson<Record<string,unknown>>(request),subject=clean(b.subject,12),mastery=clean(b.masteryStatus,30);if(!subjects.includes(subject)||!masteries.includes(mastery)||!clean(b.title,240)||!clean(b.content,5000))return out({error:'Invalid rule'},400);const id=h.randomHex(16),now=new Date().toISOString(),tags=Array.isArray(b.tags)?b.tags.filter(v=>typeof v==='string').slice(0,30):[];await env.DB.prepare('INSERT INTO core_rules VALUES(?,?,?,?,?,?,?,?,?)').bind(id,user.id,subject,clean(b.title,240),clean(b.content,5000),JSON.stringify(tags),mastery,now,now).run();return out({id},201)}
  const rule=path.match(/^\/api\/archive\/rules\/([^/]+)$/);if(rule){const id=decodeURIComponent(rule[1]),existing=await env.DB.prepare('SELECT id FROM core_rules WHERE id=? AND user_id=?').bind(id,user.id).first();if(!existing)return out({error:'Not found'},404);if(method==='PATCH'){const b=await h.boundedJson<Record<string,unknown>>(request),subject=clean(b.subject,12),mastery=clean(b.masteryStatus,30),tags=Array.isArray(b.tags)?b.tags.filter(v=>typeof v==='string').slice(0,30):[];if(!subjects.includes(subject)||!masteries.includes(mastery))return out({error:'Invalid rule'},400);await env.DB.prepare('UPDATE core_rules SET subject=?,title=?,content=?,tags_json=?,mastery_status=?,updated_at=? WHERE id=? AND user_id=?').bind(subject,clean(b.title,240),clean(b.content,5000),JSON.stringify(tags),mastery,new Date().toISOString(),id,user.id).run();return out({ok:true})}if(method==='DELETE'){await env.DB.prepare('DELETE FROM core_rules WHERE id=? AND user_id=?').bind(id,user.id).run();return out({ok:true})}}
  if(path==='/api/archive/rule-links'&&method==='POST'){const b=await h.boundedJson<Record<string,unknown>>(request),entryId=clean(b.archiveEntryId,80),ruleId=clean(b.coreRuleId,80);const [e,r]=await Promise.all([owner(env.DB,entryId,user.id),env.DB.prepare('SELECT id FROM core_rules WHERE id=? AND user_id=?').bind(ruleId,user.id).first()]);if(!e||!r)return out({error:'Not found'},404);await env.DB.prepare('INSERT OR IGNORE INTO archive_entry_core_rules VALUES(?,?,?)').bind(entryId,ruleId,new Date().toISOString()).run();return out({ok:true},201)}
  const link=path.match(/^\/api\/archive\/entries\/([^/]+)\/rules\/([^/]+)$/);if(link&&method==='DELETE'){const entryId=decodeURIComponent(link[1]),ruleId=decodeURIComponent(link[2]);if(!await owner(env.DB,entryId,user.id))return out({error:'Not found'},404);await env.DB.prepare('DELETE FROM archive_entry_core_rules WHERE archive_entry_id=? AND core_rule_id=? AND core_rule_id IN(SELECT id FROM core_rules WHERE user_id=?)').bind(entryId,ruleId,user.id).run();return out({ok:true})}
  if(path==='/api/archive/review'&&method==='GET'){const intervals=(await env.DB.prepare('SELECT intervals_json FROM archive_review_settings WHERE user_id=?').bind(user.id).first<{intervals_json:string}>())?.intervals_json??'[3,7,14,30]';const data=await bundle(env.DB,user.id,"AND (e.review_enabled=1 OR EXISTS(SELECT 1 FROM archive_entry_core_rules l WHERE l.archive_entry_id=e.id))",[]);const latest=await env.DB.prepare("SELECT r.archive_entry_id entry_id,r.next_due_at FROM archive_reviews r JOIN (SELECT archive_entry_id,MAX(reviewed_at) reviewed_at FROM archive_reviews WHERE user_id=? GROUP BY archive_entry_id) x ON x.archive_entry_id=r.archive_entry_id AND x.reviewed_at=r.reviewed_at WHERE r.user_id=?").bind(user.id,user.id).all<{entry_id:string;next_due_at:string}>();const schedule=parseJson(intervals) as number[],today=new Date().toISOString().slice(0,10);return out({...data,entries:data.entries.map((entry:any)=>{const due=latest.results.find(v=>v.entry_id===entry.id)?.next_due_at?.slice(0,10)??new Date(new Date(`${entry.studiedAt.slice(0,10)}T00:00:00Z`).getTime()+Number(schedule[0]??3)*86400000).toISOString().slice(0,10);return {...entry,nextReviewAt:due,reviewBucket:due<today?'overdue':due===today?'today':'upcoming'}}),intervals:schedule})}
  if(path==='/api/archive/review/settings'&&method==='PUT'){const b=await h.boundedJson<{intervals?:unknown}>(request),intervals=Array.isArray(b.intervals)?b.intervals.map(Number).filter(v=>Number.isInteger(v)&&v>0&&v<=365).slice(0,10):[];if(!intervals.length)return out({error:'Invalid intervals'},400);await env.DB.prepare('INSERT INTO archive_review_settings VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET intervals_json=excluded.intervals_json,updated_at=excluded.updated_at').bind(user.id,JSON.stringify(intervals),new Date().toISOString()).run();return out({ok:true})}
  if(path==='/api/archive/reviews'&&method==='POST'){const b=await h.boundedJson<Record<string,unknown>>(request),entryId=clean(b.archiveEntryId,80);if(!await owner(env.DB,entryId,user.id))return out({error:'Not found'},404);const now=new Date(),days=Math.max(1,Math.min(365,Number(b.nextIntervalDays)||3)),next=new Date(now.getTime()+days*86400000).toISOString();await env.DB.prepare('INSERT INTO archive_reviews VALUES(?,?,?,?,?,?,?,?)').bind(h.randomHex(16),user.id,entryId,now.toISOString(),b.success===true?1:0,b.coreRuleRevealed===true?1:0,next,now.toISOString()).run();return out({ok:true,nextDueAt:next},201)}
  if(path==='/api/archive/wrong-answer-links'&&method==='POST'){const b=await h.boundedJson<Record<string,unknown>>(request),entryId=clean(b.archiveEntryId,80),wrong=clean(b.wrongAnswerId,100);if(!wrong||!await owner(env.DB,entryId,user.id))return out({error:'Not found'},404);await env.DB.prepare('INSERT INTO archive_wrong_answer_links VALUES(?,?,?,?) ON CONFLICT(archive_entry_id) DO UPDATE SET wrong_answer_id=excluded.wrong_answer_id').bind(entryId,user.id,wrong,new Date().toISOString()).run();return out({ok:true},201)}
  return out({error:'Not found'},404);
 }catch(cause){if(cause instanceof Error&&cause.message==='INVALID_ENTRY')return out({error:'Invalid archive entry'},400);throw cause}
}
