type Env={DB:D1Database};
type User={id:number;is_admin:number}|null;
type Helpers={json:(body:unknown,status?:number,origin?:string)=>Response;randomHex:(size?:number)=>string;boundedJson:<T>(request:Request,maxBytes?:number)=>Promise<T>};
const clean=(v:unknown,n=1200)=>typeof v==='string'?v.trim().slice(0,n):'';
const subjects=['korean','math','english'],institutions=['KICE','education_office','EBS','private','textbook','custom'],masteries=['input','understanding','reproduction','automated'];
const parseJson=(v:unknown,fallback:unknown=[])=>{try{return JSON.parse(String(v))}catch{return fallback}};
const entryOut=(row:Record<string,unknown>)=>({id:row.id,userId:row.user_id,subject:row.subject,year:row.year,month:row.month,institution:row.institution,institutionCustomName:row.institution_custom_name,examName:row.exam_name,sourceName:row.source_name,questionNumber:row.question_number,category:row.category,subcategory:row.subcategory,title:row.title,studiedAt:row.studied_at,masteryStatus:row.mastery_status,memo:row.memo,conditionSummary:row.condition_summary,firstThought:row.first_thought,representation:row.representation,solutionFlow:row.solution_flow,bottleneck:row.bottleneck,transfer:row.transfer,mainIdea:row.main_idea,structureSummary:row.structure_summary,keyExpression:row.key_expression,reviewEnabled:Boolean(row.review_enabled),createdAt:row.created_at,updatedAt:row.updated_at,wrongAnswerId:row.wrong_answer_id??null});
const annotationOut=(r:Record<string,unknown>)=>({id:r.id,archiveEntryId:r.archive_entry_id,color:r.color,type:r.type,text:r.text,order:r.sort_order,createdAt:r.created_at,updatedAt:r.updated_at});
const ruleOut=(r:Record<string,unknown>)=>({id:r.id,subject:r.subject,title:r.title,content:r.content,tags:parseJson(r.tags_json),masteryStatus:r.mastery_status,usageCount:Number(r.usage_count??0),createdAt:r.created_at,updatedAt:r.updated_at});
const idPattern=/^[-A-Za-z0-9._:]{1,80}$/;
const iso=(v:unknown)=>typeof v==='string'&&v.length<=40&&!Number.isNaN(Date.parse(v));
const requiredId=(v:unknown)=>{if(typeof v!=='string'||!idPattern.test(v))throw new Error('INVALID_BACKUP');return v};
const requiredText=(v:unknown,max:number)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw new Error('INVALID_BACKUP');return v.trim()};
const optionalText=(v:unknown,max:number)=>{if(v===undefined||v===null||v==='')return null;if(typeof v!=='string'||v.length>max)throw new Error('INVALID_BACKUP');return v.trim()||null};
const requiredDate=(v:unknown)=>{if(!iso(v))throw new Error('INVALID_BACKUP');return v as string};
const optionalDate=(v:unknown)=>{if(v!==undefined&&v!==null&&!iso(v))throw new Error('INVALID_BACKUP')};
function arrayOf(value:unknown,max:number){if(!Array.isArray(value)||value.length>max)throw new Error('INVALID_BACKUP');return value as Record<string,unknown>[]}
async function importId(db:D1Database,table:string,id:string,userId:number,h:Helpers,ownerSql='user_id'){
 const row=await db.prepare(`SELECT ${ownerSql} owner FROM ${table} WHERE id=?`).bind(id).first<{owner:number}>();if(!row||Number(row.owner)===userId)return id;
 let candidate=`u${userId}_${id}`.slice(0,80);for(let attempt=0;attempt<5;attempt++){const hit=await db.prepare(`SELECT ${ownerSql} owner FROM ${table} WHERE id=?`).bind(candidate).first<{owner:number}>();if(!hit||Number(hit.owner)===userId)return candidate;candidate=`u${userId}_${h.randomHex(8)}`}
 throw new Error('ID_COLLISION');
}
function importedEntryValues(b:Record<string,unknown>){
 const subject=requiredText(b.subject,12),institution=requiredText(b.institution,30),mastery=requiredText(b.masteryStatus,30),year=Number(b.year),month=Number(b.month);
 if(!subjects.includes(subject)||!institutions.includes(institution)||!masteries.includes(mastery)||!Number.isInteger(year)||year<2000||year>2100||!Number.isInteger(month)||month<1||month>12)throw new Error('INVALID_BACKUP');
 return [subject,year,month,institution,optionalText(b.institutionCustomName,120),optionalText(b.examName,160)??'',optionalText(b.sourceName,160)??'',optionalText(b.questionNumber,40)??'',optionalText(b.category,120)??'',optionalText(b.subcategory,120)??'',requiredText(b.title,240),requiredDate(b.studiedAt),mastery,optionalText(b.memo,5000)??'',optionalText(b.conditionSummary,3000),optionalText(b.firstThought,3000),optionalText(b.representation,3000),optionalText(b.solutionFlow,5000),optionalText(b.bottleneck,3000),optionalText(b.transfer,3000),optionalText(b.mainIdea,3000),optionalText(b.structureSummary,3000),optionalText(b.keyExpression,3000),b.reviewEnabled===true?1:0] as const;
}
async function archiveExport(db:D1Database,userId:number){
 const [entries,annotations,rules,links,reviews,wrong,settings,drillLinks,learningReviews]=await Promise.all([
  db.prepare('SELECT * FROM archive_entries WHERE user_id=? ORDER BY id').bind(userId).all<Record<string,unknown>>(),
  db.prepare('SELECT a.* FROM archive_annotations a JOIN archive_entries e ON e.id=a.archive_entry_id WHERE e.user_id=? ORDER BY a.id').bind(userId).all<Record<string,unknown>>(),
  db.prepare('SELECT r.*,COUNT(l.archive_entry_id) usage_count FROM core_rules r LEFT JOIN archive_entry_core_rules l ON l.core_rule_id=r.id WHERE r.user_id=? GROUP BY r.id ORDER BY r.id').bind(userId).all<Record<string,unknown>>(),
  db.prepare('SELECT l.* FROM archive_entry_core_rules l JOIN archive_entries e ON e.id=l.archive_entry_id JOIN core_rules r ON r.id=l.core_rule_id WHERE e.user_id=? AND r.user_id=? ORDER BY l.archive_entry_id,l.core_rule_id').bind(userId,userId).all<Record<string,unknown>>(),
  db.prepare('SELECT * FROM archive_reviews WHERE user_id=? ORDER BY id').bind(userId).all<Record<string,unknown>>(),
  db.prepare('SELECT * FROM archive_wrong_answer_links WHERE user_id=? ORDER BY archive_entry_id').bind(userId).all<Record<string,unknown>>(),
  db.prepare('SELECT intervals_json FROM archive_review_settings WHERE user_id=?').bind(userId).first<{intervals_json:string}>(),
  db.prepare('SELECT * FROM core_rule_drill_links WHERE user_id=? ORDER BY core_rule_id,drill_id').bind(userId).all<Record<string,unknown>>(),
  db.prepare('SELECT * FROM learning_reviews WHERE user_id=? ORDER BY id').bind(userId).all<Record<string,unknown>>()
 ]);
 return {entries:entries.results.map(entryOut),annotations:annotations.results.map(annotationOut),coreRules:rules.results.map(ruleOut),ruleLinks:links.results.map(r=>({archiveEntryId:r.archive_entry_id,coreRuleId:r.core_rule_id,relationType:r.relation_type??'derived',createdAt:r.created_at})),reviews:reviews.results.map(r=>({id:r.id,archiveEntryId:r.archive_entry_id,reviewedAt:r.reviewed_at,success:Boolean(r.success),coreRuleRevealed:Boolean(r.core_rule_revealed),nextDueAt:r.next_due_at,createdAt:r.created_at})),wrongAnswerLinks:wrong.results.map(r=>({archiveEntryId:r.archive_entry_id,wrongAnswerId:r.wrong_answer_id,createdAt:r.created_at})),coreRuleDrillLinks:drillLinks.results.map(r=>({coreRuleId:r.core_rule_id,drillId:r.drill_id,createdAt:r.created_at})),learningReviews:learningReviews.results.map(r=>({id:r.id,targetType:r.target_type,targetId:r.target_id,reviewType:r.review_type,scheduledAt:r.scheduled_at,reviewedAt:r.reviewed_at,result:r.result,notes:r.notes,createdAt:r.created_at,updatedAt:r.updated_at})),reviewSettings:{intervals:parseJson(settings?.intervals_json??'[3,7,14,30]')}};
}
async function archiveImport(db:D1Database,userId:number,raw:unknown,h:Helpers){
 const body=(raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{}) as Record<string,unknown>,source=(body.learningArchive&&typeof body.learningArchive==='object'?body.learningArchive:body) as Record<string,unknown>;
 const entries=arrayOf(source.entries,300),annotations=arrayOf(source.annotations,2000),rules=arrayOf(source.coreRules,500),links=arrayOf(source.ruleLinks,2000),reviews=arrayOf(source.reviews,3000),wrongLinks=arrayOf(source.wrongAnswerLinks,300),drillLinks=source.coreRuleDrillLinks===undefined?[]:arrayOf(source.coreRuleDrillLinks,2000),learningReviews=source.learningReviews===undefined?[]:arrayOf(source.learningReviews,5000);
 const settings=(source.reviewSettings&&typeof source.reviewSettings==='object'?source.reviewSettings:{}) as Record<string,unknown>,intervals=Array.isArray(settings.intervals)?settings.intervals.map(Number):[];
 if(intervals.length>10||intervals.some(v=>!Number.isInteger(v)||v<1||v>365))throw new Error('INVALID_BACKUP');
 for(const item of rules){requiredId(item.id);const subject=requiredText(item.subject,12),mastery=requiredText(item.masteryStatus,30);requiredText(item.title,240);requiredText(item.content,5000);if(!subjects.includes(subject)||!masteries.includes(mastery)||!Array.isArray(item.tags)||item.tags.length>30||item.tags.some(v=>typeof v!=='string'||v.length>80))throw new Error('INVALID_BACKUP');optionalDate(item.createdAt);optionalDate(item.updatedAt)}
 for(const item of entries){requiredId(item.id);importedEntryValues(item);optionalDate(item.createdAt);optionalDate(item.updatedAt)}
 for(const item of annotations){requiredId(item.id);requiredId(item.archiveEntryId);requiredText(item.color,40);requiredText(item.type,80);requiredText(item.text,3000);const order=Number(item.order);if(!Number.isInteger(order)||order<-100000||order>100000)throw new Error('INVALID_BACKUP');optionalDate(item.createdAt);optionalDate(item.updatedAt)}
 for(const item of links){requiredId(item.archiveEntryId);requiredId(item.coreRuleId);optionalDate(item.createdAt)}
 for(const item of reviews){requiredId(item.id);requiredId(item.archiveEntryId);requiredDate(item.reviewedAt);if(typeof item.success!=='boolean'||typeof item.coreRuleRevealed!=='boolean'||(item.nextDueAt!==null&&item.nextDueAt!==undefined&&!iso(item.nextDueAt)))throw new Error('INVALID_BACKUP');optionalDate(item.createdAt)}
 for(const item of wrongLinks){requiredId(item.archiveEntryId);requiredId(item.wrongAnswerId);optionalDate(item.createdAt)}
 const now=new Date().toISOString(),entryMap=new Map<string,string>(),ruleMap=new Map<string,string>(),warnings:string[]=[];
 const ruleStatements:D1PreparedStatement[]=[];for(const item of rules){const original=requiredId(item.id),id=await importId(db,'core_rules',original,userId,h),subject=requiredText(item.subject,12),mastery=requiredText(item.masteryStatus,30),tags=item.tags;if(!subjects.includes(subject)||!masteries.includes(mastery)||!Array.isArray(tags)||tags.length>30||tags.some(v=>typeof v!=='string'||v.length>80))throw new Error('INVALID_BACKUP');ruleMap.set(original,id);ruleStatements.push(db.prepare('INSERT INTO core_rules(id,user_id,subject,title,content,tags_json,mastery_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET subject=excluded.subject,title=excluded.title,content=excluded.content,tags_json=excluded.tags_json,mastery_status=excluded.mastery_status,updated_at=excluded.updated_at WHERE core_rules.user_id=excluded.user_id').bind(id,userId,subject,requiredText(item.title,240),requiredText(item.content,5000),JSON.stringify(tags),mastery,iso(item.createdAt)?item.createdAt:now,iso(item.updatedAt)?item.updatedAt:now))}if(ruleStatements.length)await db.batch(ruleStatements);
 const entryStatements:D1PreparedStatement[]=[];for(const item of entries){const original=requiredId(item.id),id=await importId(db,'archive_entries',original,userId,h),values=importedEntryValues(item);entryMap.set(original,id);entryStatements.push(db.prepare('INSERT INTO archive_entries(id,user_id,subject,year,month,institution,institution_custom_name,exam_name,source_name,question_number,category,subcategory,title,studied_at,mastery_status,memo,condition_summary,first_thought,representation,solution_flow,bottleneck,transfer,main_idea,structure_summary,key_expression,review_enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET subject=excluded.subject,year=excluded.year,month=excluded.month,institution=excluded.institution,institution_custom_name=excluded.institution_custom_name,exam_name=excluded.exam_name,source_name=excluded.source_name,question_number=excluded.question_number,category=excluded.category,subcategory=excluded.subcategory,title=excluded.title,studied_at=excluded.studied_at,mastery_status=excluded.mastery_status,memo=excluded.memo,condition_summary=excluded.condition_summary,first_thought=excluded.first_thought,representation=excluded.representation,solution_flow=excluded.solution_flow,bottleneck=excluded.bottleneck,transfer=excluded.transfer,main_idea=excluded.main_idea,structure_summary=excluded.structure_summary,key_expression=excluded.key_expression,review_enabled=excluded.review_enabled,updated_at=excluded.updated_at WHERE archive_entries.user_id=excluded.user_id').bind(id,userId,...values,iso(item.createdAt)?item.createdAt:now,iso(item.updatedAt)?item.updatedAt:now))}if(entryStatements.length)await db.batch(entryStatements);
 const annotationStatements:D1PreparedStatement[]=[];for(const item of annotations){const original=requiredId(item.id),parent=entryMap.get(requiredId(item.archiveEntryId));if(!parent){warnings.push(`Annotation ${original}: parent entry 없음`);continue}const id=await importId(db,'archive_annotations',original,userId,h,'(SELECT user_id FROM archive_entries WHERE id=archive_entry_id)'),order=Number(item.order);if(!Number.isInteger(order)||order<-100000||order>100000)throw new Error('INVALID_BACKUP');annotationStatements.push(db.prepare('INSERT INTO archive_annotations(id,archive_entry_id,color,type,text,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET archive_entry_id=excluded.archive_entry_id,color=excluded.color,type=excluded.type,text=excluded.text,sort_order=excluded.sort_order,updated_at=excluded.updated_at WHERE archive_annotations.archive_entry_id IN(SELECT id FROM archive_entries WHERE user_id=?)').bind(id,parent,requiredText(item.color,40),requiredText(item.type,80),requiredText(item.text,3000),order,iso(item.createdAt)?item.createdAt:now,iso(item.updatedAt)?item.updatedAt:now,userId))}if(annotationStatements.length)await db.batch(annotationStatements);
 const seenLinks=new Set<string>(),linkStatements:D1PreparedStatement[]=[];for(const item of links){const entry=entryMap.get(requiredId(item.archiveEntryId)),rule=ruleMap.get(requiredId(item.coreRuleId)),key=`${entry}:${rule}`;if(!entry||!rule){warnings.push('Rule Link: parent entry/rule 없음');continue}if(seenLinks.has(key)){warnings.push(`Rule Link ${key}: 중복 link`);continue}seenLinks.add(key);linkStatements.push(db.prepare('INSERT OR IGNORE INTO archive_entry_core_rules(archive_entry_id,core_rule_id,created_at) VALUES(?,?,?)').bind(entry,rule,iso(item.createdAt)?item.createdAt:now))}if(linkStatements.length)await db.batch(linkStatements);
 const reviewStatements:D1PreparedStatement[]=[];for(const item of reviews){const original=requiredId(item.id),entry=entryMap.get(requiredId(item.archiveEntryId));if(!entry){warnings.push(`Review ${original}: parent entry 없음`);continue}const id=await importId(db,'archive_reviews',original,userId,h);if(typeof item.success!=='boolean'||typeof item.coreRuleRevealed!=='boolean'||!iso(item.reviewedAt)||(item.nextDueAt!==null&&item.nextDueAt!==undefined&&!iso(item.nextDueAt)))throw new Error('INVALID_BACKUP');reviewStatements.push(db.prepare('INSERT INTO archive_reviews(id,user_id,archive_entry_id,reviewed_at,success,core_rule_revealed,next_due_at,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET archive_entry_id=excluded.archive_entry_id,reviewed_at=excluded.reviewed_at,success=excluded.success,core_rule_revealed=excluded.core_rule_revealed,next_due_at=excluded.next_due_at WHERE archive_reviews.user_id=excluded.user_id').bind(id,userId,entry,item.reviewedAt,item.success?1:0,item.coreRuleRevealed?1:0,item.nextDueAt??null,iso(item.createdAt)?item.createdAt:now))}if(reviewStatements.length)await db.batch(reviewStatements);
 const state=await db.prepare('SELECT payload FROM learning_state WHERE user_id=?').bind(userId).first<{payload:string}>(),app=parseJson(state?.payload??'{}',{}) as Record<string,unknown>,validWrong=new Set((Array.isArray(app.wrongAnswerDrills)?app.wrongAnswerDrills:[]).map(v=>v&&typeof v==='object'?(v as Record<string,unknown>).id:null).filter(v=>typeof v==='string'));
 const seenWrong=new Set<string>(),wrongStatements:D1PreparedStatement[]=[];for(const item of wrongLinks){const entry=entryMap.get(requiredId(item.archiveEntryId)),wrong=requiredId(item.wrongAnswerId);if(!entry){warnings.push(`Wrong Answer Link ${wrong}: parent entry 없음`);continue}if(!validWrong.has(wrong)){warnings.push(`Wrong Answer Link ${wrong}: 존재하지 않는 Wrong Answer Drill`);continue}if(seenWrong.has(entry)||seenWrong.has(`wrong:${wrong}`)){warnings.push(`Wrong Answer Link ${wrong}: 중복 link`);continue}seenWrong.add(entry);seenWrong.add(`wrong:${wrong}`);wrongStatements.push(db.prepare('INSERT INTO archive_wrong_answer_links(archive_entry_id,user_id,wrong_answer_id,created_at) VALUES(?,?,?,?) ON CONFLICT(archive_entry_id) DO UPDATE SET wrong_answer_id=excluded.wrong_answer_id,created_at=excluded.created_at WHERE archive_wrong_answer_links.user_id=excluded.user_id').bind(entry,userId,wrong,iso(item.createdAt)?item.createdAt:now))}if(wrongStatements.length)await db.batch(wrongStatements);
 const validDrills=new Set((Array.isArray(app.dailyDrills)?app.dailyDrills:[]).map(v=>v&&typeof v==='object'?(v as Record<string,unknown>).id:null).filter(v=>typeof v==='string')),drillStatements:D1PreparedStatement[]=[];for(const item of drillLinks){const rule=ruleMap.get(requiredId(item.coreRuleId)),drill=requiredId(item.drillId);if(!rule||!validDrills.has(drill)){warnings.push(`Drill Link ${drill}: parent 없음`);continue}drillStatements.push(db.prepare('INSERT OR IGNORE INTO core_rule_drill_links(user_id,core_rule_id,drill_id,created_at) VALUES(?,?,?,?)').bind(userId,rule,drill,iso(item.createdAt)?item.createdAt:now))}if(drillStatements.length)await db.batch(drillStatements);
 const learningReviewStatements:D1PreparedStatement[]=[];for(const item of learningReviews){const type=requiredText(item.targetType,30),result=requiredText(item.result,20),originalTarget=requiredId(item.targetId),target=type==='core_rule'?ruleMap.get(originalTarget):type==='learning_item'?entryMap.get(originalTarget):originalTarget;if(!target||!['wrong_answer','core_rule','drill','learning_item'].includes(type)||!['pending','success','fail'].includes(result)){warnings.push(`Learning Review ${String(item.id)}: target 없음`);continue}learningReviewStatements.push(db.prepare('INSERT OR IGNORE INTO learning_reviews(id,user_id,target_type,target_id,review_type,scheduled_at,reviewed_at,result,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(requiredId(item.id),userId,type,target,optionalText(item.reviewType,40)??'retry',optionalText(item.scheduledAt,40),optionalText(item.reviewedAt,40),result,optionalText(item.notes,3000)??'',iso(item.createdAt)?item.createdAt:now,iso(item.updatedAt)?item.updatedAt:now))}if(learningReviewStatements.length)await db.batch(learningReviewStatements);
 if(intervals.length)await db.batch([db.prepare('INSERT INTO archive_review_settings(user_id,intervals_json,updated_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET intervals_json=excluded.intervals_json,updated_at=excluded.updated_at').bind(userId,JSON.stringify(intervals),now)]);
 return {ok:true,warnings,imported:{coreRules:ruleStatements.length,entries:entryStatements.length,annotations:annotationStatements.length,ruleLinks:linkStatements.length,reviews:reviewStatements.length,wrongAnswerLinks:wrongStatements.length,coreRuleDrillLinks:drillStatements.length,learningReviews:learningReviewStatements.length},skipped:warnings.length,failed:0};
}
async function owner(db:D1Database,id:string,userId:number){return db.prepare('SELECT id FROM archive_entries WHERE id=? AND user_id=?').bind(id,userId).first()}
async function ensureIntelligence(db:D1Database){
 await db.batch([db.prepare("CREATE TABLE IF NOT EXISTS core_rule_drill_links(user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,core_rule_id TEXT NOT NULL REFERENCES core_rules(id) ON DELETE CASCADE,drill_id TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(core_rule_id,drill_id))"),db.prepare("CREATE TABLE IF NOT EXISTS learning_reviews(id TEXT PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,target_type TEXT NOT NULL,target_id TEXT NOT NULL,review_type TEXT NOT NULL DEFAULT 'retry',scheduled_at TEXT,reviewed_at TEXT,result TEXT NOT NULL DEFAULT 'pending',notes TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)")]);
 const columns=await db.prepare('PRAGMA table_info(archive_entry_core_rules)').all<{name:string}>();if(!columns.results.some(v=>v.name==='relation_type'))await db.prepare("ALTER TABLE archive_entry_core_rules ADD COLUMN relation_type TEXT NOT NULL DEFAULT 'derived'").run();
}
function entryValues(body:Record<string,unknown>){
 const subject=clean(body.subject,12),institution=clean(body.institution,30),mastery=clean(body.masteryStatus,30),year=Number(body.year),month=Number(body.month);
 if(!subjects.includes(subject)||!institutions.includes(institution)||!masteries.includes(mastery)||!Number.isInteger(year)||year<2000||year>2100||!Number.isInteger(month)||month<1||month>12||!clean(body.title,240)||!/^\d{4}-\d{2}-\d{2}/.test(clean(body.studiedAt,30)))throw new Error('INVALID_ENTRY');
 return [subject,year,month,institution,clean(body.institutionCustomName,120)||null,clean(body.examName,160),clean(body.sourceName,160),clean(body.questionNumber,40),clean(body.category,120),clean(body.subcategory,120),clean(body.title,240),clean(body.studiedAt,30),mastery,clean(body.memo,5000),clean(body.conditionSummary,3000)||null,clean(body.firstThought,3000)||null,clean(body.representation,3000)||null,clean(body.solutionFlow,5000)||null,clean(body.bottleneck,3000)||null,clean(body.transfer,3000)||null,clean(body.mainIdea,3000)||null,clean(body.structureSummary,3000)||null,clean(body.keyExpression,3000)||null,body.reviewEnabled===true?1:0] as const;
}
async function bundle(db:D1Database,userId:number,where:string,bind:unknown[]){
 const entries=await db.prepare(`SELECT e.*,w.wrong_answer_id FROM archive_entries e LEFT JOIN archive_wrong_answer_links w ON w.archive_entry_id=e.id WHERE e.user_id=? ${where} ORDER BY e.studied_at DESC,e.updated_at DESC LIMIT 300`).bind(userId,...bind).all<Record<string,unknown>>();
 const ids=entries.results.map(r=>String(r.id));if(!ids.length)return {entries:[]};const marks=ids.map(()=>'?').join(',');
 const [annotations,rules]=await Promise.all([db.prepare(`SELECT * FROM archive_annotations WHERE archive_entry_id IN (${marks}) ORDER BY sort_order,id`).bind(...ids).all<Record<string,unknown>>(),db.prepare(`SELECT l.archive_entry_id,r.* FROM archive_entry_core_rules l JOIN core_rules r ON r.id=l.core_rule_id WHERE l.archive_entry_id IN (${marks}) AND r.user_id=? ORDER BY r.title`).bind(...ids,userId).all<Record<string,unknown>>()]);
 return {entries:entries.results.map(row=>({...entryOut(row),annotations:annotations.results.filter(a=>a.archive_entry_id===row.id).map(annotationOut),coreRules:rules.results.filter(r=>r.archive_entry_id===row.id).map(ruleOut)}))};
}
export async function archive(request:Request,env:Env,user:User,origin:string,h:Helpers):Promise<Response|null>{
 const url=new URL(request.url),path=url.pathname,method=request.method;if(!path.startsWith('/api/archive'))return null;const out=(v:unknown,s=200)=>h.json(v,s,origin);if(!user)return out({error:'Unauthorized'},401);
 try{
  await ensureIntelligence(env.DB);
  if(path==='/api/archive/export'&&method==='GET')return out(await archiveExport(env.DB,user.id));
  if(path==='/api/archive/import'&&method==='POST')return out(await archiveImport(env.DB,user.id,await h.boundedJson<unknown>(request,5*1024*1024),h));
  if(path==='/api/archive/entries'&&method==='GET'){
   const clauses:string[]=[],bind:unknown[]=[];for(const [key,column] of [['subject','e.subject'],['year','e.year'],['month','e.month'],['institution','e.institution'],['exam','e.exam_name'],['source','e.source_name'],['category','e.category'],['subcategory','e.subcategory'],['masteryStatus','e.mastery_status']] as const){const value=url.searchParams.get(key);if(value){clauses.push(`${column}=?`);bind.push(value)}}
   const color=url.searchParams.get('color'),core=url.searchParams.get('coreRule'),q=url.searchParams.get('q');if(color){clauses.push('EXISTS(SELECT 1 FROM archive_annotations a WHERE a.archive_entry_id=e.id AND a.color=?)');bind.push(color)}if(core==='true')clauses.push('EXISTS(SELECT 1 FROM archive_entry_core_rules l WHERE l.archive_entry_id=e.id)');if(core==='false')clauses.push('NOT EXISTS(SELECT 1 FROM archive_entry_core_rules l WHERE l.archive_entry_id=e.id)');if(q){clauses.push("(e.title LIKE ? OR e.memo LIKE ? OR e.exam_name LIKE ? OR e.source_name LIKE ? OR EXISTS(SELECT 1 FROM archive_annotations a WHERE a.archive_entry_id=e.id AND a.text LIKE ?))");for(let i=0;i<5;i++)bind.push(`%${q.slice(0,100)}%`)}return out(await bundle(env.DB,user.id,clauses.length?'AND '+clauses.join(' AND '):'',bind));
  }
  if(path==='/api/archive/entries'&&method==='POST'){const body=await h.boundedJson<Record<string,unknown>>(request),values=entryValues(body),id=h.randomHex(16),now=new Date().toISOString();await env.DB.prepare('INSERT INTO archive_entries(id,user_id,subject,year,month,institution,institution_custom_name,exam_name,source_name,question_number,category,subcategory,title,studied_at,mastery_status,memo,condition_summary,first_thought,representation,solution_flow,bottleneck,transfer,main_idea,structure_summary,key_expression,review_enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,user.id,...values,now,now).run();return out({id},201)}
  const item=path.match(/^\/api\/archive\/entries\/([^/]+)$/);if(item){const id=decodeURIComponent(item[1]);if(!await owner(env.DB,id,user.id))return out({error:'Not found'},404);if(method==='GET')return out(await bundle(env.DB,user.id,'AND e.id=?',[id]));if(method==='PATCH'){const body=await h.boundedJson<Record<string,unknown>>(request),v=entryValues(body);await env.DB.prepare('UPDATE archive_entries SET subject=?,year=?,month=?,institution=?,institution_custom_name=?,exam_name=?,source_name=?,question_number=?,category=?,subcategory=?,title=?,studied_at=?,mastery_status=?,memo=?,condition_summary=?,first_thought=?,representation=?,solution_flow=?,bottleneck=?,transfer=?,main_idea=?,structure_summary=?,key_expression=?,review_enabled=?,updated_at=? WHERE id=? AND user_id=?').bind(...v,new Date().toISOString(),id,user.id).run();return out({ok:true})}if(method==='DELETE'){await env.DB.prepare('DELETE FROM archive_entries WHERE id=? AND user_id=?').bind(id,user.id).run();return out({ok:true})}}
  if(path==='/api/archive/annotations'&&method==='POST'){const b=await h.boundedJson<Record<string,unknown>>(request),entryId=clean(b.archiveEntryId,80);if(!await owner(env.DB,entryId,user.id))return out({error:'Not found'},404);const text=clean(b.text,3000),color=clean(b.color,40),type=clean(b.type,80);if(!text||!color||!type)return out({error:'color, type, text are required'},400);const id=h.randomHex(16),now=new Date().toISOString();await env.DB.prepare('INSERT INTO archive_annotations VALUES(?,?,?,?,?,?,?,?)').bind(id,entryId,color,type,text,Number(b.order)||0,now,now).run();return out({id},201)}
  const annotation=path.match(/^\/api\/archive\/annotations\/([^/]+)$/);if(annotation){const id=decodeURIComponent(annotation[1]),row=await env.DB.prepare('SELECT a.id FROM archive_annotations a JOIN archive_entries e ON e.id=a.archive_entry_id WHERE a.id=? AND e.user_id=?').bind(id,user.id).first();if(!row)return out({error:'Not found'},404);if(method==='PATCH'){const b=await h.boundedJson<Record<string,unknown>>(request);await env.DB.prepare('UPDATE archive_annotations SET color=?,type=?,text=?,sort_order=?,updated_at=? WHERE id=?').bind(clean(b.color,40),clean(b.type,80),clean(b.text,3000),Number(b.order)||0,new Date().toISOString(),id).run();return out({ok:true})}if(method==='DELETE'){await env.DB.prepare('DELETE FROM archive_annotations WHERE id=?').bind(id).run();return out({ok:true})}}
  if(path==='/api/archive/rules'&&method==='GET'){const rows=await env.DB.prepare('SELECT r.*,COUNT(l.archive_entry_id) usage_count FROM core_rules r LEFT JOIN archive_entry_core_rules l ON l.core_rule_id=r.id WHERE r.user_id=? GROUP BY r.id ORDER BY r.updated_at DESC').bind(user.id).all<Record<string,unknown>>();return out({rules:rows.results.map(ruleOut)})}
  if(path==='/api/archive/rules'&&method==='POST'){const b=await h.boundedJson<Record<string,unknown>>(request),subject=clean(b.subject,12),mastery=clean(b.masteryStatus,30);if(!subjects.includes(subject)||!masteries.includes(mastery)||!clean(b.title,240)||!clean(b.content,5000))return out({error:'Invalid rule'},400);const id=h.randomHex(16),now=new Date().toISOString(),tags=Array.isArray(b.tags)?b.tags.filter(v=>typeof v==='string').slice(0,30):[];await env.DB.prepare('INSERT INTO core_rules VALUES(?,?,?,?,?,?,?,?,?)').bind(id,user.id,subject,clean(b.title,240),clean(b.content,5000),JSON.stringify(tags),mastery,now,now).run();return out({id},201)}
  const rule=path.match(/^\/api\/archive\/rules\/([^/]+)$/);if(rule){const id=decodeURIComponent(rule[1]),existing=await env.DB.prepare('SELECT id FROM core_rules WHERE id=? AND user_id=?').bind(id,user.id).first();if(!existing)return out({error:'Not found'},404);if(method==='PATCH'){const b=await h.boundedJson<Record<string,unknown>>(request),subject=clean(b.subject,12),mastery=clean(b.masteryStatus,30),tags=Array.isArray(b.tags)?b.tags.filter(v=>typeof v==='string').slice(0,30):[];if(!subjects.includes(subject)||!masteries.includes(mastery))return out({error:'Invalid rule'},400);await env.DB.prepare('UPDATE core_rules SET subject=?,title=?,content=?,tags_json=?,mastery_status=?,updated_at=? WHERE id=? AND user_id=?').bind(subject,clean(b.title,240),clean(b.content,5000),JSON.stringify(tags),mastery,new Date().toISOString(),id,user.id).run();return out({ok:true})}if(method==='DELETE'){await env.DB.prepare('DELETE FROM core_rules WHERE id=? AND user_id=?').bind(id,user.id).run();return out({ok:true})}}
  if(path==='/api/archive/rule-links'&&method==='POST'){const b=await h.boundedJson<Record<string,unknown>>(request),entryId=clean(b.archiveEntryId,80),ruleId=clean(b.coreRuleId,80),relation=clean(b.relationType,20)||'derived';if(!['derived','applied','failed','reinforced'].includes(relation))return out({error:'Invalid relation type'},400);const [e,r]=await Promise.all([owner(env.DB,entryId,user.id),env.DB.prepare('SELECT id FROM core_rules WHERE id=? AND user_id=?').bind(ruleId,user.id).first()]);if(!e||!r)return out({error:'Not found'},404);await env.DB.prepare('INSERT INTO archive_entry_core_rules(archive_entry_id,core_rule_id,created_at,relation_type) VALUES(?,?,?,?) ON CONFLICT(archive_entry_id,core_rule_id) DO UPDATE SET relation_type=excluded.relation_type').bind(entryId,ruleId,new Date().toISOString(),relation).run();return out({ok:true},201)}
  const link=path.match(/^\/api\/archive\/entries\/([^/]+)\/rules\/([^/]+)$/);if(link&&method==='DELETE'){const entryId=decodeURIComponent(link[1]),ruleId=decodeURIComponent(link[2]);if(!await owner(env.DB,entryId,user.id))return out({error:'Not found'},404);await env.DB.prepare('DELETE FROM archive_entry_core_rules WHERE archive_entry_id=? AND core_rule_id=? AND core_rule_id IN(SELECT id FROM core_rules WHERE user_id=?)').bind(entryId,ruleId,user.id).run();return out({ok:true})}
  if(path==='/api/archive/review'&&method==='GET'){const intervals=(await env.DB.prepare('SELECT intervals_json FROM archive_review_settings WHERE user_id=?').bind(user.id).first<{intervals_json:string}>())?.intervals_json??'[3,7,14,30]';const data=await bundle(env.DB,user.id,"AND (e.review_enabled=1 OR EXISTS(SELECT 1 FROM archive_entry_core_rules l WHERE l.archive_entry_id=e.id))",[]);const latest=await env.DB.prepare("SELECT r.archive_entry_id entry_id,r.next_due_at FROM archive_reviews r JOIN (SELECT archive_entry_id,MAX(reviewed_at) reviewed_at FROM archive_reviews WHERE user_id=? GROUP BY archive_entry_id) x ON x.archive_entry_id=r.archive_entry_id AND x.reviewed_at=r.reviewed_at WHERE r.user_id=?").bind(user.id,user.id).all<{entry_id:string;next_due_at:string}>();const schedule=parseJson(intervals) as number[],today=new Date().toISOString().slice(0,10);return out({...data,entries:data.entries.map((entry:any)=>{const due=latest.results.find(v=>v.entry_id===entry.id)?.next_due_at?.slice(0,10)??new Date(new Date(`${entry.studiedAt.slice(0,10)}T00:00:00Z`).getTime()+Number(schedule[0]??3)*86400000).toISOString().slice(0,10);return {...entry,nextReviewAt:due,reviewBucket:due<today?'overdue':due===today?'today':'upcoming'}}),intervals:schedule})}
  if(path==='/api/archive/review/settings'&&method==='PUT'){const b=await h.boundedJson<{intervals?:unknown}>(request),intervals=Array.isArray(b.intervals)?b.intervals.map(Number).filter(v=>Number.isInteger(v)&&v>0&&v<=365).slice(0,10):[];if(!intervals.length)return out({error:'Invalid intervals'},400);await env.DB.prepare('INSERT INTO archive_review_settings VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET intervals_json=excluded.intervals_json,updated_at=excluded.updated_at').bind(user.id,JSON.stringify(intervals),new Date().toISOString()).run();return out({ok:true})}
  if(path==='/api/archive/reviews'&&method==='POST'){const b=await h.boundedJson<Record<string,unknown>>(request),entryId=clean(b.archiveEntryId,80);if(!await owner(env.DB,entryId,user.id))return out({error:'Not found'},404);const now=new Date(),days=Math.max(1,Math.min(365,Number(b.nextIntervalDays)||3)),next=new Date(now.getTime()+days*86400000).toISOString();await env.DB.prepare('INSERT INTO archive_reviews VALUES(?,?,?,?,?,?,?,?)').bind(h.randomHex(16),user.id,entryId,now.toISOString(),b.success===true?1:0,b.coreRuleRevealed===true?1:0,next,now.toISOString()).run();return out({ok:true,nextDueAt:next},201)}
  if(path==='/api/archive/wrong-answer-links'&&method==='POST'){const b=await h.boundedJson<Record<string,unknown>>(request),entryId=clean(b.archiveEntryId,80),wrong=clean(b.wrongAnswerId,100);if(!wrong||!await owner(env.DB,entryId,user.id))return out({error:'Not found'},404);await env.DB.prepare('INSERT INTO archive_wrong_answer_links VALUES(?,?,?,?) ON CONFLICT(archive_entry_id) DO UPDATE SET wrong_answer_id=excluded.wrong_answer_id').bind(entryId,user.id,wrong,new Date().toISOString()).run();return out({ok:true},201)}
  const wrongLink=path.match(/^\/api\/archive\/entries\/([^/]+)\/wrong-answer$/);if(wrongLink&&method==='DELETE'){const entryId=decodeURIComponent(wrongLink[1]);if(!await owner(env.DB,entryId,user.id))return out({error:'Not found'},404);await env.DB.prepare('DELETE FROM archive_wrong_answer_links WHERE archive_entry_id=? AND user_id=?').bind(entryId,user.id).run();return out({ok:true})}
  return out({error:'Not found'},404);
 }catch(cause){if(cause instanceof Error&&cause.message==='INVALID_ENTRY')return out({error:'Invalid archive entry'},400);if(cause instanceof Error&&cause.message==='INVALID_BACKUP')return out({error:'Invalid Learning Archive backup'},400);throw cause}
}
