type Env={DB:D1Database};type User={id:number}|null;type Tools={json:(v:unknown,s?:number,o?:string)=>Response;boundedJson:<T>(r:Request,n?:number)=>Promise<T>;randomHex:(n?:number)=>string};
const clean=(v:unknown,n=1000)=>typeof v==='string'?v.trim().slice(0,n):'';
const parse=<T>(v:string,f:T):T=>{try{return JSON.parse(v) as T}catch{return f}};
async function state(env:Env,userId:number){const row=await env.DB.prepare('SELECT payload FROM learning_state WHERE user_id=?').bind(userId).first<{payload:string}>();return parse<Record<string,unknown>>(row?.payload??'{}',{})}
async function entryOwner(db:D1Database,id:string,userId:number){return db.prepare('SELECT id FROM archive_entries WHERE id=? AND user_id=?').bind(id,userId).first()}
async function ruleOwner(db:D1Database,id:string,userId:number){return db.prepare('SELECT id FROM core_rules WHERE id=? AND user_id=?').bind(id,userId).first()}
async function targetOwned(env:Env,userId:number,type:string,id:string){if(type==='learning_item')return Boolean(await entryOwner(env.DB,id,userId));if(type==='core_rule')return Boolean(await ruleOwner(env.DB,id,userId));const app=await state(env,userId),rows=type==='wrong_answer'?app.wrongAnswerDrills:app.dailyDrills;return Array.isArray(rows)&&rows.some(v=>v&&typeof v==='object'&&(v as {id?:unknown}).id===id)}

export async function learningIntelligence(request:Request,env:Env,user:User,origin:string,h:Tools):Promise<Response|null>{
 const url=new URL(request.url),path=url.pathname;if(!path.startsWith('/api/learning-intelligence')&&!path.match(/^\/api\/core-rules\/[^/]+\/intelligence$/))return null;const out=(v:unknown,s=200)=>h.json(v,s,origin);if(!user)return out({error:'Unauthorized'},401);
 if(path==='/api/learning-intelligence'&&request.method==='GET'){
  const [items,rules,reviews]=await Promise.all([env.DB.prepare('SELECT COUNT(*) count FROM archive_entries WHERE user_id=?').bind(user.id).first<{count:number}>(),env.DB.prepare('SELECT COUNT(*) count FROM core_rules WHERE user_id=?').bind(user.id).first<{count:number}>(),env.DB.prepare("SELECT COUNT(*) count,SUM(result='success') successes,SUM(result='fail') failures FROM learning_reviews WHERE user_id=?").bind(user.id).first<{count:number;successes:number;failures:number}>()]);
  return out({items:Number(items?.count||0),coreRules:Number(rules?.count||0),reviews:{count:Number(reviews?.count||0),successes:Number(reviews?.successes||0),failures:Number(reviews?.failures||0)}})
 }
 const item=path.match(/^\/api\/learning-intelligence\/items\/([^/]+)$/);if(item&&request.method==='GET'){
  const id=decodeURIComponent(item[1]);if(!await entryOwner(env.DB,id,user.id))return out({error:'Not found'},404);
  const [archive,annotations,rules,reviews,wrongLinks,drillLinks]=await Promise.all([env.DB.prepare('SELECT * FROM archive_entries WHERE id=? AND user_id=?').bind(id,user.id).first(),env.DB.prepare('SELECT * FROM archive_annotations WHERE archive_entry_id=? ORDER BY sort_order').bind(id).all(),env.DB.prepare('SELECT r.*,l.relation_type FROM core_rules r JOIN archive_entry_core_rules l ON l.core_rule_id=r.id WHERE l.archive_entry_id=? AND r.user_id=?').bind(id,user.id).all(),env.DB.prepare("SELECT * FROM learning_reviews WHERE user_id=? AND ((target_type='learning_item' AND target_id=?) OR target_id IN(SELECT core_rule_id FROM archive_entry_core_rules WHERE archive_entry_id=?)) ORDER BY COALESCE(reviewed_at,scheduled_at) DESC").bind(user.id,id,id).all(),env.DB.prepare('SELECT wrong_answer_id FROM archive_wrong_answer_links WHERE archive_entry_id=? AND user_id=?').bind(id,user.id).all<{wrong_answer_id:string}>(),env.DB.prepare('SELECT d.* FROM core_rule_drill_links d JOIN archive_entry_core_rules l ON l.core_rule_id=d.core_rule_id WHERE l.archive_entry_id=? AND d.user_id=?').bind(id,user.id).all()]);
  const app=await state(env,user.id),wrongIds=new Set(wrongLinks.results.map(v=>v.wrong_answer_id)),drillIds=new Set((drillLinks.results as {drill_id?:string}[]).map(v=>v.drill_id));return out({item:archive,archive:{...archive,annotations:annotations.results},wrongAnswers:(Array.isArray(app.wrongAnswerDrills)?app.wrongAnswerDrills:[]).filter(v=>v&&typeof v==='object'&&wrongIds.has(String((v as {id?:unknown}).id))),coreRules:rules.results,drills:(Array.isArray(app.dailyDrills)?app.dailyDrills:[]).filter(v=>v&&typeof v==='object'&&drillIds.has(String((v as {id?:unknown}).id))),reviews:reviews.results})
 }
 const rule=path.match(/^\/api\/core-rules\/([^/]+)\/intelligence$/);if(rule&&request.method==='GET'){
  const id=decodeURIComponent(rule[1]);if(!await ruleOwner(env.DB,id,user.id))return out({error:'Not found'},404);const [coreRule,linkedItems,wrongLinks,drillLinks,reviews,stats]=await Promise.all([env.DB.prepare('SELECT * FROM core_rules WHERE id=? AND user_id=?').bind(id,user.id).first(),env.DB.prepare('SELECT e.*,l.relation_type FROM archive_entries e JOIN archive_entry_core_rules l ON l.archive_entry_id=e.id WHERE l.core_rule_id=? AND e.user_id=? ORDER BY e.studied_at DESC').bind(id,user.id).all(),env.DB.prepare('SELECT w.wrong_answer_id FROM archive_wrong_answer_links w JOIN archive_entry_core_rules l ON l.archive_entry_id=w.archive_entry_id WHERE l.core_rule_id=? AND w.user_id=?').bind(id,user.id).all<{wrong_answer_id:string}>(),env.DB.prepare('SELECT * FROM core_rule_drill_links WHERE core_rule_id=? AND user_id=?').bind(id,user.id).all<{drill_id:string}>(),env.DB.prepare("SELECT * FROM learning_reviews WHERE user_id=? AND target_type='core_rule' AND target_id=? ORDER BY COALESCE(reviewed_at,scheduled_at) DESC").bind(user.id,id).all(),env.DB.prepare("SELECT COUNT(*) review_count,SUM(result='success') successes,SUM(result='fail') failures,MAX(CASE WHEN result='success' THEN reviewed_at END) last_success_at,MAX(CASE WHEN result='fail' THEN reviewed_at END) last_failure_at FROM learning_reviews WHERE user_id=? AND target_type='core_rule' AND target_id=?").bind(user.id,id).first<Record<string,unknown>>()]);const app=await state(env,user.id),wrongIds=new Set(wrongLinks.results.map(v=>v.wrong_answer_id)),drillIds=new Set(drillLinks.results.map(v=>v.drill_id)),completed=Number(stats?.review_count||0),success=Number(stats?.successes||0);return out({coreRule,linkedItems:linkedItems.results,wrongAnswers:(Array.isArray(app.wrongAnswerDrills)?app.wrongAnswerDrills:[]).filter(v=>v&&typeof v==='object'&&wrongIds.has(String((v as {id?:unknown}).id))),drills:(Array.isArray(app.dailyDrills)?app.dailyDrills:[]).filter(v=>v&&typeof v==='object'&&drillIds.has(String((v as {id?:unknown}).id))),reviews:reviews.results,stats:{linkedItems:linkedItems.results.length,wrongCount:wrongIds.size,drillCount:drillIds.size,reviewCount:completed,reviewSuccessCount:success,reviewFailureCount:Number(stats?.failures||0),lastFailureAt:stats?.last_failure_at??null,lastSuccessAt:stats?.last_success_at??null,masteryRate:completed?success/completed:null,masteryStatus:completed?'measured':'insufficient-data'}})
 }
 if(path==='/api/learning-intelligence/drill-links'&&request.method==='POST'){const b=await h.boundedJson<Record<string,unknown>>(request),ruleId=clean(b.coreRuleId,80),drillId=clean(b.drillId,100);if(!await ruleOwner(env.DB,ruleId,user.id)||!await targetOwned(env,user.id,'drill',drillId))return out({error:'Not found'},404);await env.DB.prepare('INSERT OR IGNORE INTO core_rule_drill_links(user_id,core_rule_id,drill_id,created_at) VALUES(?,?,?,?)').bind(user.id,ruleId,drillId,new Date().toISOString()).run();return out({ok:true},201)}
 if(path==='/api/learning-intelligence/reviews'&&request.method==='POST'){const b=await h.boundedJson<Record<string,unknown>>(request),type=clean(b.targetType,30),id=clean(b.targetId,100),result=clean(b.result,20)||'pending';if(!['wrong_answer','core_rule','drill','learning_item'].includes(type)||!['pending','success','fail'].includes(result)||!await targetOwned(env,user.id,type,id))return out({error:'Invalid review target'},400);const now=new Date().toISOString(),reviewed=result==='pending'?null:now;await env.DB.prepare('INSERT INTO learning_reviews(id,user_id,target_type,target_id,review_type,scheduled_at,reviewed_at,result,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(h.randomHex(16),user.id,type,id,clean(b.reviewType,40)||'retry',clean(b.scheduledAt,40)||null,reviewed,result,clean(b.notes,3000),now,now).run();return out({ok:true},201)}
 return out({error:'Not found'},404)
}
