import { useEffect, useMemo, useState } from 'react';
import { Check, ClipboardPlus, Goal, MessageSquareText } from 'lucide-react';
import type { AppData } from '../types';
import { acknowledgeFeedback, linkFeedback, makeDailyDrill, makeWeeklyGoal, studentFeedback, summarizeTeacherFeedback, type Feedback } from '../lib/feedback';
import { Card, Empty, PageHeader } from '../components/Ui';
import { InterventionEditor } from '../components/teacher/shared';
export default function FeedbackInbox({data,update}:{data:AppData;update:(fn:(value:AppData)=>AppData)=>void}){
 const [items,setItems]=useState<Feedback[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[coach,setCoach]=useState(''),[loading,setLoading]=useState(true);
 const [draft,setDraft]=useState<{item:Feedback;kind:'daily'|'weekly'}>();
 const refresh=async()=>{try{const value=await studentFeedback();setItems(value.feedback);}catch(reason){setError(reason instanceof Error?reason.message:'피드백 조회 실패');}finally{setLoading(false);}};
 useEffect(()=>{void refresh();},[]);
 const active=useMemo(()=>items.filter(item=>item.progress==='active'&&item.signal?.status!=='dismissed'),[items]);
 return <div><PageHeader eyebrow="TEACHER FEEDBACK" title="선생님 피드백" description={active.length?`새로 확인할 피드백 ${active.filter(item=>!item.acknowledgedByStudent).length}개`:'현재 활성 피드백이 없습니다.'}/>
 {active.length>0&&<Card className="feedback-coach"><div><b>AI COACH · 피드백 요약</b><p>{coach||'선생님의 판단을 바꾸지 않고, 오늘 우선할 행동만 짧게 정리합니다.'}</p></div><button className="button" disabled={Boolean(busy)} onClick={async()=>{setBusy('coach');try{setCoach((await summarizeTeacherFeedback(data,items)).message);}catch(reason){setError(reason instanceof Error?reason.message:'AI 요약 조회 실패');}finally{setBusy('');}}}>오늘 우선순위 요약</button></Card>}
 {error&&<p className="team-error" role="alert">{error}</p>}{loading?<p role="status">피드백을 불러오는 중…</p>:active.length?<div className="feedback-list">{active.map(item=><Card key={item.id} className="feedback-card"><div className="feedback-card-head"><div><span className={`subject-badge ${item.signal?.subject??item.subject??'전체'}`}>{item.signal?.subject??(item.type==='academic_management'?'ACADEMIC MANAGER':item.subject)}</span><small>{item.teacher_name||'선생님'} · {item.categories?.join(' · ')}</small><h2>{item.title||item.bottleneck||'학습 피드백'}</h2></div><span className={`feedback-status ${item.status}`}>{item.status==='needs_improvement'?'개선 필요':item.status==='stable'?'안정':'보통'}</span></div>
 {item.observation&&<p className="feedback-observation">{item.observation}</p>}<div className="feedback-actions-text"><section><b>이번 주 행동</b><p>{item.action||'행동 제안 없음'}</p></section><section><b>성공 기준</b><p>{item.success_criterion||'성공 기준 없음'}</p></section></div>
 {item.signal?.weeklyGoal&&<p>학습 선생님이 전달한 목표 초안 · {item.signal.weeklyGoal.ability}</p>}{item.signal?.dailyDrill&&<p>학습 선생님이 전달한 Drill 초안 · {item.signal.dailyDrill.title} · {item.signal.dailyDrill.minutes}분</p>}{item.comment&&<p className="feedback-comment">{item.comment}</p>}
 <div className="feedback-buttons"><button className="button" disabled={Boolean(busy)||item.acknowledgedByStudent} onClick={async()=>{setBusy(item.id);try{await acknowledgeFeedback(item.id);await refresh();}catch(reason){setError(reason instanceof Error?reason.message:'확인 실패');}finally{setBusy('');}}}><Check size={15}/>{item.acknowledgedByStudent?'확인함':'확인'}</button>
 <button className="button" disabled={Boolean(busy)||Boolean(item.linked_daily_drill_id)||data.dailyDrills.some(drill=>drill.feedbackId===item.id)} onClick={()=>setDraft({item,kind:'daily'})}><ClipboardPlus size={15}/>{item.linked_daily_drill_id?'Daily Drill 반영됨':'Daily Drill 확인 · 생성'}</button>
 <button className="button" disabled={Boolean(busy)||Boolean(item.linked_weekly_goal_id)||data.weeklyCapabilityGoals.some(goal=>goal.feedbackId===item.id)} onClick={()=>setDraft({item,kind:'weekly'})}><Goal size={15}/>{item.linked_weekly_goal_id?'Weekly Goal 반영됨':'Weekly Goal 확인 · 생성'}</button></div></Card>)}</div>:<Empty><MessageSquareText size={18}/>아직 작성된 피드백이 없습니다.</Empty>}
 {draft&&<InterventionEditor item={draft.item} kind={draft.kind} student onClose={()=>setDraft(undefined)} onSave={async value=>{setBusy(draft.item.id);try{if('weekStart' in value){const goal={...makeWeeklyGoal(draft.item),...value};await linkFeedback(draft.item.id,'weekly_goal',goal.id);update(current=>({...current,weeklyCapabilityGoals:[goal,...current.weeklyCapabilityGoals]}));}else{const goal=data.weeklyCapabilityGoals.find(goal=>goal.feedbackId===draft.item.id);const drill={...makeDailyDrill(draft.item),...value,capabilityGoalId:goal?.id};await linkFeedback(draft.item.id,'daily_drill',drill.id);update(current=>({...current,dailyDrills:[drill,...current.dailyDrills]}));}await refresh();}finally{setBusy('');}}}/>}
 </div>;
}
