import { useEffect, useMemo, useRef, useState } from 'react';
import { Award, BarChart3, BookOpen, BrainCircuit, CalendarCheck, ChevronRight, Clock3, Crown, Flame, Gem, GraduationCap, LockKeyhole, Medal, Moon, Plus, RefreshCw, Rocket, ShieldCheck, Sparkles, Star, Sun, Target, TrendingUp, Trophy, UserRound, Users, X, Zap } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { AppData, ArenaBootstrap, ArenaGroup, ArenaGroupType, ArenaProfile, ArenaRankingEntry, ArenaScore, ArenaSeason, ArenaVisibility } from '../types';
import { Card, Field, PageHeader } from '../components/Ui';
import { addArenaRival, ArenaApiError, createArenaGroup, fetchArena, fetchArenaRanking, joinArenaGroup, publishArenaScore as publishArenaScoreRequest, removeArenaRival, requestArenaCoach, saveArenaProfile, saveArenaSeasonName } from '../lib/arenaApi';
import { calculateArenaScore } from '../lib/arenaScore';
import { ARENA_BADGE_CATEGORIES, calculateArenaBadges, type ArenaBadgeCategory, type ArenaBadgeIcon } from '../lib/arenaBadges';
import '../arena.css';

type View = 'home' | 'groups' | 'ranking' | 'rivals' | 'achievements' | 'profile';
const EMPTY_PROFILE: ArenaProfile = { nickname: '', grade: '', targetUniversity: '', targetDepartment: '', targetAdmissionType: '', studyGoal: [''], achievementLevel: '' };
const TABS: { id: View; label: string }[] = [{ id: 'home', label: 'Arena Home' }, { id: 'groups', label: '목표 그룹' }, { id: 'ranking', label: '랭킹' }, { id: 'rivals', label: '라이벌' }, { id: 'achievements', label: '시즌 · 배지' }, { id: 'profile', label: '프로필' }];
const BADGE_ICONS: Record<ArenaBadgeIcon, LucideIcon> = { award: Award, book: BookOpen, brain: BrainCircuit, calendar: CalendarCheck, clock: Clock3, crown: Crown, flame: Flame, gem: Gem, graduation: GraduationCap, moon: Moon, rocket: Rocket, sparkles: Sparkles, star: Star, sun: Sun, target: Target, trophy: Trophy, zap: Zap };
const formatHours = (seconds: number) => `${Math.round(seconds / 360) / 10}h`;
const growth = (value: number) => `${value > 0 ? '+' : ''}${value.toFixed(1)}%`;
const target = (profile: Pick<ArenaProfile, 'targetUniversity' | 'targetDepartment'> | null) => profile ? [profile.targetUniversity, profile.targetDepartment].filter(Boolean).join(' ') || '목표 설정 전' : '목표 설정 전';

function ScoreRing({ score, onSecret }: { score: number; onSecret: () => void }) {
  return <button type="button" className="arena-score-ring" aria-label={`Trinity Score ${score}점. 숨겨진 반응 보기`} onClick={onSecret} style={{ '--score': `${score / 10}%` } as React.CSSProperties}><div><strong>{score}</strong><span>/ 1000</span></div></button>;
}

function ScoreBreakdown({ score }: { score: ArenaScore }) {
  const rows = [
    ['실행력', score.breakdown.execution, 300, '계획 대비 실행과 실제 학습'],
    ['문제 해결력', score.breakdown.problemSolving, 300, '시험 변화와 오답 Drill'],
    ['꾸준함', score.breakdown.consistency, 200, '연속 학습과 계획 유지'],
    ['성장률', score.breakdown.growth, 200, '지난 기록 대비 개선 폭'],
  ] as const;
  return <div className="arena-breakdown">{rows.map(([label, value, max, description]) => <div key={label}><header><span><b>{label}</b><small>{description}</small></span><strong>{value}<i>/ {max}</i></strong></header><div><i style={{ width: `${value / max * 100}%` }} /></div></div>)}</div>;
}

function ProfileForm({ value, saving, onChange, onSave }: { value: ArenaProfile; saving: boolean; onChange: (value: ArenaProfile) => void; onSave: () => void }) {
  const set = <K extends keyof ArenaProfile>(field: K, next: ArenaProfile[K]) => onChange({ ...value, [field]: next });
  return <Card className="arena-form-card"><div className="arena-form-intro"><span><UserRound /></span><div><h2>성장 프로필</h2><p>실명 대신 닉네임으로 참여합니다. 목표는 언제든 바꿀 수 있습니다.</p></div></div><div className="arena-profile-grid">
    <Field label="닉네임"><input value={value.nickname} maxLength={20} placeholder="예: HanK" onChange={event => set('nickname', event.target.value)} /></Field>
    <Field label="학년"><select value={value.grade} onChange={event => set('grade', event.target.value)}><option value="">선택</option>{['중3','고1','고2','고3','N수'].map(item => <option key={item}>{item}</option>)}</select></Field>
    <Field label="목표 대학"><input value={value.targetUniversity} placeholder="예: 서울대학교" onChange={event => set('targetUniversity', event.target.value)} /></Field>
    <Field label="목표 학과"><input value={value.targetDepartment} placeholder="예: 전기전자공학부" onChange={event => set('targetDepartment', event.target.value)} /></Field>
    <Field label="전형"><select value={value.targetAdmissionType} onChange={event => set('targetAdmissionType', event.target.value)}><option value="">선택</option>{['정시','학생부종합','학생부교과','논술','기타'].map(item => <option key={item}>{item}</option>)}</select></Field>
    <Field label="현재 성취 수준"><input value={value.achievementLevel} placeholder="예: 수학 2등급 · 국어 3등급" onChange={event => set('achievementLevel', event.target.value)} /></Field>
  </div><Field label="학습 목표" hint="한 줄에 하나씩, 최대 5개"><textarea rows={4} value={value.studyGoal.join('\n')} placeholder={'수학 1등급\n국어 백분위 98'} onChange={event => set('studyGoal', event.target.value.split('\n').slice(0, 5))} /></Field><div className="arena-form-actions"><span><ShieldCheck size={16}/> 랭킹에는 닉네임과 목표만 표시됩니다.</span><button className="button primary" disabled={saving || value.nickname.trim().length < 2} onClick={onSave}>{saving ? '저장 중…' : '프로필 저장'}</button></div></Card>;
}

function SeasonNameForm({ season, saving, onSave }: { season: ArenaSeason; saving: boolean; onSave: (name: string) => void }) {
  const [name, setName] = useState(season.name);
  useEffect(() => setName(season.name), [season.id, season.name]);
  const remaining = Math.max(0, Math.ceil((new Date(`${season.endsAt}T23:59:59`).getTime() - Date.now()) / 86_400_000));
  return <Card className="arena-season-editor"><div className="arena-season-editor-icon"><CalendarCheck /></div><div><span className="card-label">14-DAY SEASON</span><h2>이번 시즌의 이름</h2><p>{season.startsAt.replaceAll('-', '.')} – {season.endsAt.replaceAll('-', '.')} · 종료까지 {remaining}일</p></div><div className="arena-season-name-control"><input aria-label="Arena 시즌 이름" value={name} maxLength={32} onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && name.trim().length >= 2) onSave(name.trim()); }} /><button className="button primary" disabled={saving || name.trim().length < 2 || name.trim() === season.name} onClick={() => onSave(name.trim())}>{saving ? '저장 중…' : '이름 저장'}</button></div></Card>;
}

function RankingTable({ rows, rivals, onRival }: { rows: ArenaRankingEntry[]; rivals: string[]; onRival: (userId: string) => void }) {
  if (!rows.length) return <div className="arena-empty"><BarChart3/><b>아직 공개된 점수가 없습니다.</b><p>학습 기록을 쌓고 점수를 갱신하면 첫 순위가 만들어집니다.</p></div>;
  return <div className="arena-table"><div className="arena-table-head"><span>순위</span><span>닉네임</span><span>Trinity Score</span><span>성장률</span><span>목표</span><span/></div>{rows.map(row => <div className={row.isMe ? 'is-me' : ''} key={row.userId}><strong>{row.rank}</strong><span className="arena-person"><i>{row.nickname.slice(0, 1).toUpperCase()}</i><b>{row.nickname}{row.isMe && <small>나</small>}</b></span><b>{row.score}</b><span className={row.growthRate >= 0 ? 'positive' : 'negative'}>{growth(row.growthRate)}</span><span>{[row.targetUniversity, row.targetDepartment].filter(Boolean).join(' ') || '목표 미설정'}</span><button disabled={row.isMe || rivals.includes(row.userId)} onClick={() => onRival(row.userId)}>{rivals.includes(row.userId) ? '라이벌' : '비교'}</button></div>)}</div>;
}

export default function Arena({ data }: { data: AppData }) {
  const score = useMemo(() => calculateArenaScore(data), [data]);
  const [view, setView] = useState<View>('home'); const [arenaState, setArena] = useState<ArenaBootstrap | null>(null); const [profile, setProfile] = useState<ArenaProfile>(EMPTY_PROFILE); const [ranking, setRanking] = useState<ArenaRankingEntry[]>([]); const [selectedGroup, setSelectedGroup] = useState('');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [coach, setCoach] = useState(''); const [coachLoading, setCoachLoading] = useState(false); const [joinCode, setJoinCode] = useState('');
  const [badgeCategory, setBadgeCategory] = useState<'all' | ArenaBadgeCategory>('all'); const [secretMode, setSecretMode] = useState(false); const scoreTap = useRef({ count: 0, last: 0 }); const secretKeys = useRef('');
  const [groupForm, setGroupForm] = useState<{ name: string; type: ArenaGroupType; targetUniversity: string; targetDepartment: string; visibility: ArenaVisibility }>({ name: '', type: 'university', targetUniversity: '', targetDepartment: '', visibility: 'public' });
  const arena = arenaState ?? { profile: null, groups: [], ranking: [], rivals: [], achievements: [], season: { id: '', name: '', startsAt: '', endsAt: '', status: 'upcoming' as const }, latestScore: null };

  const publishArenaScore = async () => {
    try {
      return await publishArenaScoreRequest();
    } catch (cause) {
      if (cause instanceof ArenaApiError && (cause.status === 404 || cause.status === 405)) {
        setNotice('프로필은 저장되었습니다. Arena 점수 집계 서버를 업데이트하고 있습니다.');
        window.setTimeout(() => setNotice(''), 4000);
        return null;
      }
      throw cause;
    }
  };

  const reload = async (publish = false) => { setError(''); try { let result = await fetchArena(); if (publish && result.profile) { await publishArenaScore(); result = await fetchArena(); } setArena(result); setProfile(result.profile ?? EMPTY_PROFILE); setRanking(result.ranking); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Arena 데이터를 불러오지 못했습니다.'); } finally { setLoading(false); } };
  useEffect(() => { void reload(true); }, []); // The score snapshot is refreshed when Arena opens.
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2400); };
  useEffect(() => { const sequence = 'ArrowUpArrowUpArrowDownArrowDownArrowLeftArrowRightArrowLeftArrowRightba'; const onKeyDown = (event: KeyboardEvent) => { secretKeys.current = (secretKeys.current + event.key).slice(-sequence.length); if (secretKeys.current.endsWith(sequence)) { setSecretMode((value) => !value); flash('✦ TRINITY 비밀 좌표를 발견했습니다.'); secretKeys.current = ''; } }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown); }, []);
  const saveProfile = async () => { setSaving(true); setError(''); try { const result = await saveArenaProfile({ ...profile, studyGoal: profile.studyGoal.map(item => item.trim()).filter(Boolean) }); setProfile(result.profile); await publishArenaScore(); await reload(); flash('Arena 프로필을 저장했습니다.'); setView('home'); } catch (cause) { setError(cause instanceof Error ? cause.message : '프로필 저장에 실패했습니다.'); } finally { setSaving(false); } };
  const createGroup = async () => { if (!groupForm.name.trim()) return; setSaving(true); try { await createArenaGroup(groupForm); setGroupForm({ name: '', type: 'university', targetUniversity: '', targetDepartment: '', visibility: 'public' }); await reload(); flash('그룹을 만들고 가입했습니다.'); } catch (cause) { setError(cause instanceof Error ? cause.message : '그룹 생성에 실패했습니다.'); } finally { setSaving(false); } };
  const join = async (id: string) => { setSaving(true); try { await joinArenaGroup(id); setJoinCode(''); await reload(); flash('목표 그룹에 가입했습니다.'); } catch (cause) { setError(cause instanceof Error ? cause.message : '그룹 가입에 실패했습니다.'); } finally { setSaving(false); } };
  const selectGroup = async (id: string) => { setSelectedGroup(id); setView('ranking'); try { const result = await fetchArenaRanking(id); setRanking(result.ranking); } catch (cause) { setError(cause instanceof Error ? cause.message : '그룹 랭킹을 불러오지 못했습니다.'); } };
  const showAllRanking = async () => { setSelectedGroup(''); setView('ranking'); try { setRanking((await fetchArenaRanking()).ranking); } catch (cause) { setError(cause instanceof Error ? cause.message : '랭킹을 불러오지 못했습니다.'); } };
  const addRival = async (id: string) => { try { await addArenaRival(id); await reload(); flash('라이벌 비교에 추가했습니다.'); } catch (cause) { setError(cause instanceof Error ? cause.message : '라이벌 추가에 실패했습니다.'); } };
  const removeRival = async (id: string) => { try { await removeArenaRival(id); await reload(); flash('라이벌 비교에서 제거했습니다.'); } catch (cause) { setError(cause instanceof Error ? cause.message : '라이벌 제거에 실패했습니다.'); } };
  const askCoach = async () => { setCoachLoading(true); const groupRows = selectedGroup ? ranking : arena?.ranking ?? []; const avg = groupRows.length ? Math.round(groupRows.reduce((sum, row) => sum + row.score, 0) / groupRows.length) : 0; try { const result = await requestArenaCoach({ score: score.total, breakdown: score.breakdown, metrics: score.metrics, group: { size: groupRows.length, averageScore: avg, myRank: groupRows.find(row => row.isMe)?.rank }, nextActions: score.metrics.nextActions }); setCoach(result.message); } catch { setCoach(`현재 가장 큰 개선 지점은 ${score.metrics.weakAreas[0] ?? '기록의 연속성'}입니다. ${score.metrics.nextActions.join(' ')}`); } finally { setCoachLoading(false); } };

  const saveSeasonName = async (name: string) => { setSaving(true); setError(''); try { const result = await saveArenaSeasonName(name); setArena((current) => current ? { ...current, season: result.season } : current); flash('이번 14일 시즌의 이름을 저장했습니다.'); } catch (cause) { setError(cause instanceof Error ? cause.message : '시즌 이름을 저장하지 못했습니다.'); } finally { setSaving(false); } };
  const ownRank = arena.ranking.find(row => row.isMe)?.rank; const joinedGroups = arena.groups.filter(group => group.joined); const group = joinedGroups[0];
  const groupRank = group && selectedGroup === group.id ? ranking.find(row => row.isMe)?.rank : undefined;
  const seasonProgress = arena ? Math.max(0, Math.min(100, (Date.now() - Date.parse(arena.season.startsAt)) / Math.max(1, Date.parse(arena.season.endsAt) - Date.parse(arena.season.startsAt)) * 100)) : 0;
  const awarded = useMemo(() => new Set(arena.achievements.map(item => item.code)), [arena.achievements]);
  const badges = useMemo(() => calculateArenaBadges(data, score, profile, awarded), [data, score, profile, awarded]);
  const visibleBadges = badgeCategory === 'all' ? badges : badges.filter((badge) => badge.category === badgeCategory);
  const unlockedBadges = badges.filter((badge) => badge.unlocked);
  const revealScoreSecret = () => { const now = Date.now(); scoreTap.current.count = now - scoreTap.current.last < 900 ? scoreTap.current.count + 1 : 1; scoreTap.current.last = now; if (scoreTap.current.count >= 3) { scoreTap.current.count = 0; setSecretMode((value) => !value); flash('✦ Trinity Score가 비밀 주파수에 동기화되었습니다.'); } };

  return <div className={`arena-page ${secretMode ? 'arena-secret-mode' : ''}`}><PageHeader eyebrow="TRINITY ARENA" title="목표에 가까워지는 경쟁" description="시간이 아니라 실행, 문제 해결, 꾸준함, 성장의 균형을 봅니다." action={<button className="button" onClick={() => void reload(true)}><RefreshCw size={16}/> 점수 갱신</button>}/>
    <div className="arena-tabs" role="tablist">{TABS.map(tab => <button key={tab.id} className={view === tab.id ? 'active' : ''} onClick={() => setView(tab.id)}>{tab.label}</button>)}</div>
    {error && <div className="arena-alert"><span>{error}</span><button onClick={() => setError('')}><X size={15}/></button></div>}
    {loading ? <div className="arena-loading"><RefreshCw/> 성장 기록을 연결하고 있습니다.</div> : !arena?.profile && view !== 'profile' ? <div className="arena-onboarding"><GraduationCap/><p className="eyebrow">START ARENA</p><h2>먼저 목표를 알려주세요</h2><p>닉네임과 목표 대학을 설정하면 같은 방향의 학생들과 성장 지표를 비교할 수 있습니다.</p><button className="button primary" onClick={() => setView('profile')}>프로필 설정하기 <ChevronRight size={17}/></button></div> : <>
      {view === 'home' && <div className="arena-home">
        <Card className="arena-hero"><div className="arena-hero-copy"><span className="arena-season-chip">{arena.season.name}</span><p className="eyebrow">MY ARENA</p><h2>{target(profile)}</h2><div className="arena-rank-summary"><span><small>전체 순위</small><b>{ownRank ? `${ownRank}위` : '집계 중'}</b></span><span><small>{group ? `${group.name} 순위` : '목표 그룹'}</small><b>{groupRank ? `${groupRank}위` : group ? '랭킹 보기' : '가입 전'}</b></span><span><small>이번 주 성장률</small><b className={score.metrics.growthRate >= 0 ? 'positive' : 'negative'}>{growth(score.metrics.growthRate)}</b></span><span><small>연속 학습</small><b>{score.metrics.streakDays}일</b></span></div></div><ScoreRing score={score.total} onSecret={revealScoreSecret}/></Card>
        <Card className="arena-score-card"><div className="arena-section-head"><div><p className="eyebrow">SCORE EVIDENCE</p><h2>Trinity Score 구성</h2></div><small>{new Date(score.calculatedAt).toLocaleString('ko-KR')} 기준</small></div><ScoreBreakdown score={score}/></Card>
        <Card className="arena-coach"><div className="arena-coach-icon"><Sparkles/></div><div><p className="eyebrow">AI COACH</p><h2>순위보다, 다음 변화</h2><p>{coach || `현재 개선 여지가 가장 큰 영역은 ${score.metrics.weakAreas[0] ?? '주간 기록의 밀도'}입니다. ${score.metrics.nextActions[0]}`}</p><div className="arena-actions">{score.metrics.nextActions.map(action => <span key={action}><Target size={14}/>{action}</span>)}</div></div><button className="button" disabled={coachLoading} onClick={askCoach}>{coachLoading ? '분석 중…' : 'AI 분석 받기'}</button></Card>
        <div className="arena-metrics"><Card><span><TrendingUp/></span><small>계획 실행률</small><strong>{score.metrics.planExecutionRate}%</strong><p>완료한 계획과 Drill 기준</p></Card><Card><span><Flame/></span><small>이번 주 학습</small><strong>{formatHours(score.metrics.currentWeekSeconds)}</strong><p>점수의 일부이며 순위 자체가 아닙니다.</p></Card><Card><span><Target/></span><small>오답 개선</small><strong>{score.metrics.drillCompletionRate}%</strong><p>재풀이와 전이 기록 기준</p></Card><Card><span><Users/></span><small>활동일</small><strong>{score.metrics.activeDays}/7</strong><p>학습 리듬의 분산을 봅니다.</p></Card></div>
        <Card className="arena-badge-preview"><div><span className="card-label">ACHIEVEMENTS</span><h2>{unlockedBadges.length} / {badges.length} 배지 발견</h2><p>학습 기록이 쌓일수록 새로운 표식과 숨겨진 배지가 열립니다.</p></div><div className="arena-badge-preview-icons">{unlockedBadges.slice(-5).map((badge) => { const Icon = BADGE_ICONS[badge.icon]; return <span key={badge.code} title={badge.title}><Icon/></span>; })}{!unlockedBadges.length && <small>첫 학습 세션이 첫 배지를 깨웁니다.</small>}</div><button className="button" onClick={() => setView('achievements')}>전체 배지 보기 <ChevronRight size={15}/></button></Card>
      </div>}

      {view === 'profile' && <div className="arena-profile-settings"><ProfileForm value={profile} saving={saving} onChange={setProfile} onSave={saveProfile}/><SeasonNameForm season={arena.season} saving={saving} onSave={(name) => void saveSeasonName(name)}/></div>}

      {view === 'groups' && <div className="arena-groups-layout"><div><div className="arena-section-head"><div><p className="eyebrow">UNIVERSITY GROUP</p><h2>목표 그룹</h2></div><span>{joinedGroups.length}개 참여 중</span></div><div className="arena-group-list">{arena.groups.map(item => <Card className={item.joined ? 'arena-group joined' : 'arena-group'} key={item.id}><div className="arena-group-icon">{item.type === 'university' ? <GraduationCap/> : item.type === 'department' ? <Target/> : <Users/>}</div><div><span>{item.visibility === 'private' ? '비공개' : '공개'} · {item.memberCount}명</span><h3>{item.name}</h3><p>{[item.targetUniversity, item.targetDepartment].filter(Boolean).join(' · ') || '함께 성장하는 사용자 그룹'}</p>{item.inviteCode && <code>초대 코드 {item.inviteCode}</code>}</div><div>{item.joined ? <button className="button" onClick={() => void selectGroup(item.id)}>랭킹 보기</button> : <button className="button primary" disabled={saving} onClick={() => void join(item.id)}>가입</button>}</div></Card>)}</div>{!arena.groups.length && <div className="arena-empty"><Users/><b>첫 목표 그룹을 만들어 보세요.</b><p>대학, 학과 또는 친구 그룹을 만들 수 있습니다.</p></div>}</div><Card className="arena-create-group"><p className="eyebrow">NEW GROUP</p><h2>그룹 만들기</h2><Field label="그룹 이름"><input value={groupForm.name} placeholder="예: 서울대학교 목표" onChange={e => setGroupForm({ ...groupForm, name: e.target.value })}/></Field><div className="arena-two-fields"><Field label="그룹 유형"><select value={groupForm.type} onChange={e => setGroupForm({ ...groupForm, type: e.target.value as ArenaGroupType })}><option value="university">대학 그룹</option><option value="department">학과 그룹</option><option value="custom">사용자 그룹</option></select></Field><Field label="공개 범위"><select value={groupForm.visibility} onChange={e => setGroupForm({ ...groupForm, visibility: e.target.value as ArenaVisibility })}><option value="public">공개</option><option value="private">비공개</option></select></Field></div><Field label="목표 대학"><input value={groupForm.targetUniversity} onChange={e => setGroupForm({ ...groupForm, targetUniversity: e.target.value })}/></Field><Field label="목표 학과"><input value={groupForm.targetDepartment} onChange={e => setGroupForm({ ...groupForm, targetDepartment: e.target.value })}/></Field><button className="button primary arena-full-button" disabled={saving || !groupForm.name.trim()} onClick={() => void createGroup()}><Plus size={16}/> 그룹 생성</button><div className="arena-join"><span>초대 코드로 가입</span><div><input value={joinCode} placeholder="초대 코드" onChange={e => setJoinCode(e.target.value.toUpperCase())}/><button disabled={!joinCode.trim()} onClick={() => void join(joinCode)}>가입</button></div></div></Card></div>}

      {view === 'ranking' && <Card className="arena-ranking"><div className="arena-section-head"><div><p className="eyebrow">GROWTH RANKING</p><h2>{selectedGroup ? arena.groups.find(item => item.id === selectedGroup)?.name : '전체 Arena'} 랭킹</h2></div><select value={selectedGroup} onChange={event => event.target.value ? void selectGroup(event.target.value) : void showAllRanking()}><option value="">전체 Arena</option>{joinedGroups.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><p className="arena-ranking-note">공부시간 단독 순위가 아닙니다. 네 가지 성장 지표의 합산 결과입니다.</p><RankingTable rows={ranking} rivals={arena.rivals.map(item => item.userId)} onRival={id => void addRival(id)}/></Card>}

      {view === 'rivals' && <div><div className="arena-section-head"><div><p className="eyebrow">RIVAL COMPARE</p><h2>나와 라이벌의 성장 차이</h2></div><span>최대 3명</span></div>{arena.rivals.length ? <div className="arena-rivals">{arena.rivals.map(rival => <Card key={rival.userId} className="arena-rival"><header><span className="arena-person"><i>{profile.nickname.slice(0,1)}</i><b>{profile.nickname}</b></span><em>VS</em><span className="arena-person"><i>{rival.nickname.slice(0,1)}</i><b>{rival.nickname}</b></span><button aria-label="라이벌 제거" onClick={() => void removeRival(rival.userId)}><X size={16}/></button></header><div className="arena-rival-scores"><span><small>나의 Score</small><b>{score.total}</b></span><span><small>{rival.nickname} Score</small><b>{rival.score}</b></span></div><div className="arena-compare-bars">{rival.comparison?.map(item => { const max = Math.max(item.mine, item.rival, 1); return <div key={item.label}><b>{item.label}</b><span><i style={{ width: `${item.mine/max*100}%` }}/><small>{item.mine}{item.unit}</small></span><span><i style={{ width: `${item.rival/max*100}%` }}/><small>{item.rival}{item.unit}</small></span></div>})}</div><p className="arena-insight"><Sparkles size={15}/>{rival.insight}</p></Card>)}</div> : <div className="arena-empty"><Users/><b>아직 지정한 라이벌이 없습니다.</b><p>랭킹에서 학생을 선택하면 최대 3명과 성장 지표를 비교할 수 있습니다.</p><button className="button" onClick={() => void showAllRanking()}>랭킹에서 찾기</button></div>}</div>}

      {view === 'achievements' && <div className="arena-achievement-layout"><Card className="arena-season"><div><p className="eyebrow">CURRENT SEASON</p><h2>{arena.season.name}</h2><p>{arena.season.startsAt.replaceAll('-', '.')} — {arena.season.endsAt.replaceAll('-', '.')}</p></div><div className="arena-season-progress"><span><i style={{ width: `${seasonProgress}%` }}/></span><small>시즌 {Math.round(seasonProgress)}% 진행</small></div><div className="arena-season-awards"><span><Medal/>성장왕</span><span><Flame/>꾸준함 1위</span><span><Target/>문제 해결왕</span></div></Card>
        <Card className="arena-badge-summary"><div><span className="card-label">BADGE VAULT</span><h2>{unlockedBadges.length}개 획득 · {badges.length - unlockedBadges.length}개 남음</h2><p>시간만으로 얻는 배지보다 교정·재현·전이 배지가 더 희귀합니다.</p></div><strong>{Math.round(unlockedBadges.length / Math.max(1, badges.length) * 100)}%</strong></Card>
        <div className="arena-badge-filters" role="tablist" aria-label="배지 분류"><button role="tab" aria-selected={badgeCategory === 'all'} className={badgeCategory === 'all' ? 'active' : ''} onClick={() => setBadgeCategory('all')}>전체 <small>{badges.length}</small></button>{ARENA_BADGE_CATEGORIES.map((category) => <button role="tab" aria-selected={badgeCategory === category.id} key={category.id} className={badgeCategory === category.id ? 'active' : ''} onClick={() => setBadgeCategory(category.id)}>{category.label} <small>{badges.filter((badge) => badge.category === category.id).length}</small></button>)}</div>
        {secretMode && <div className="arena-secret-message"><Sparkles/><span><b>TRINITY SECRET MODE</b><small>점수 링의 세 번째 박동이 숨은 좌표를 열었습니다.</small></span></div>}
        <div className="arena-badge-grid">{visibleBadges.map((badge) => { const Icon = BADGE_ICONS[badge.icon]; const hidden = badge.secret && !badge.unlocked; const progress = Math.min(100, Math.round((badge.current ?? 0) / Math.max(1, badge.target ?? 1) * 100)); return <Card className={`${badge.unlocked ? 'arena-badge unlocked' : 'arena-badge'} ${badge.secret ? 'secret' : ''}`} key={badge.code}><span>{hidden ? <LockKeyhole/> : <Icon/>}</span><small>{badge.unlocked ? '획득 완료' : badge.secret ? 'SECRET' : '도전 중'}</small><h3>{hidden ? '???' : badge.title}</h3><p>{hidden ? 'Arena 어딘가에 조건이 숨어 있습니다.' : badge.description}</p>{!badge.unlocked && !hidden && <div className="arena-badge-progress"><i style={{ width: `${progress}%` }}/><small>{Math.min(badge.current ?? 0, badge.target ?? 1).toFixed((badge.current ?? 0) % 1 ? 1 : 0)} / {badge.target}</small></div>}{badge.unlocked && <b><Award size={14}/> Achievement</b>}</Card>})}</div></div>}
    </>}
    {notice && <div className="arena-notice">{notice}</div>}
  </div>;
}
