import { useMemo, useState } from 'react';
import { Check, ChevronLeft, ChevronRight, Clock3, Plus, Trash2, X } from 'lucide-react';
import type { AppData, CalendarEntry, CalendarPlan, Subject } from '../types';
import { SUBJECTS } from '../data/config';
import { Card, Field, PageHeader, SaveButton, TextArea } from '../components/Ui';
import { toDateKey, uid } from '../lib/date';

const emptyEntry = (date: string): CalendarEntry => ({ date, study: '', minutes: 0, exam: '', event: '', condition: 3, reflection: '', plans: [] });
const emptyPlan = (): CalendarPlan => ({ id: '', subject: '국어', title: '', detail: '', quantity: '', done: false });
const formatStudyTime = (minutes: number) => { const rounded = Math.round(minutes); const hours = Math.floor(rounded / 60); const rest = rounded % 60; return hours ? `${hours}시간${rest ? ` ${rest}분` : ''}` : `${rest}분`; };
export default function CalendarPage({ data, update }: { data: AppData; update: (fn: (value: AppData) => AppData) => void }) {
  const [cursor, setCursor] = useState(() => new Date()); const [selected, setSelected] = useState<string | null>(null); const [draft, setDraft] = useState<CalendarEntry | null>(null); const [planDraft, setPlanDraft] = useState(emptyPlan());
  const year = cursor.getFullYear(), month = cursor.getMonth();
  const cells = useMemo(() => { const first = new Date(year, month, 1); const days = new Date(year, month + 1, 0).getDate(); return [...Array(first.getDay()).fill(null), ...Array.from({ length: days }, (_, i) => i + 1)]; }, [year, month]);
  const studyByDate = useMemo(() => data.sessions.reduce<Record<string, { total: number; subjects: Partial<Record<Subject, number>> }>>((result, session) => { const current = result[session.date] ?? { total: 0, subjects: {} }; current.total += session.seconds / 60; current.subjects[session.subject] = (current.subjects[session.subject] ?? 0) + session.seconds / 60; result[session.date] = current; return result; }, {}), [data.sessions]);
  const selectedStudy = selected ? studyByDate[selected] : undefined;
  const openDay = (day: number) => { const key = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`; setSelected(key); setDraft(data.calendar[key] ? { ...data.calendar[key], plans: data.calendar[key].plans ?? [] } : emptyEntry(key)); setPlanDraft(emptyPlan()); };
  const save = () => { if (!selected || !draft) return; update((value) => ({ ...value, calendar: { ...value.calendar, [selected]: draft } })); setSelected(null); };
  const addPlan = () => { if (!draft || !planDraft.title.trim()) return; setDraft({ ...draft, plans: [...(draft.plans ?? []), { ...planDraft, id: uid(), title: planDraft.title.trim() }] }); setPlanDraft(emptyPlan()); };
  const updatePlan = (id: string, change: Partial<CalendarPlan>) => draft && setDraft({ ...draft, plans: (draft.plans ?? []).map((plan) => plan.id === id ? { ...plan, ...change } : plan) });
  const removePlan = (id: string) => draft && setDraft({ ...draft, plans: (draft.plans ?? []).filter((plan) => plan.id !== id) });
  return <div><PageHeader eyebrow="CALENDAR" title="날짜별 학습 일정" description="날짜마다 훈련 일정·목표량·모의고사를 만들고, 실행 여부와 회고를 함께 남깁니다." />
    <Card className="calendar-card"><div className="calendar-head"><button aria-label="이전 달" onClick={() => setCursor(new Date(year, month - 1))}><ChevronLeft /></button><h2>{year}년 {month + 1}월</h2><button aria-label="다음 달" onClick={() => setCursor(new Date(year, month + 1))}><ChevronRight /></button></div><div className="weekdays">{['일','월','화','수','목','금','토'].map((day) => <span key={day}>{day}</span>)}</div>
      <div className="calendar-grid">{cells.map((day, index) => day ? (() => { const key = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`; const entry = data.calendar[key]; const plans = entry?.plans ?? []; const timerMinutes = studyByDate[key]?.total ?? 0; const studyMinutes = timerMinutes > 0 ? timerMinutes : (entry?.minutes ?? 0); return <button key={key} className={`${key === toDateKey() ? 'today' : ''} ${entry ? 'has-entry' : ''} ${plans.length ? 'has-plan' : ''} ${studyMinutes > 0 ? 'has-study-time' : ''}`} onClick={() => openDay(day)}><b>{day}</b>{studyMinutes > 0 && <strong className="calendar-study-time"><Clock3 size={11} /> {formatStudyTime(studyMinutes)}</strong>}<div className="calendar-plan-preview">{plans.slice(0, 2).map((plan) => <small className={plan.done ? 'done' : ''} key={plan.id}>{plan.subject} · {plan.title}</small>)}{plans.length > 2 && <em>+{plans.length - 2}</em>}</div>{entry?.exam && <i title={entry.exam} />}</button>; })() : <span key={`empty-${index}`} />)}</div>
    </Card>
    {selected && draft && <div className="modal-backdrop" onClick={() => setSelected(null)}><div className="modal schedule-modal" onClick={(event) => event.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">DAILY SCHEDULE</p><h2>{selected}</h2></div><button onClick={() => setSelected(null)} aria-label="닫기"><X /></button></div>
      <section className="daily-plan-editor"><div className="daily-plan-title"><div><b>오늘의 일정</b><small>계획은 여러 개 추가할 수 있으며, 저장 후에도 완료 여부를 바꿀 수 있습니다.</small></div><span>{(draft.plans ?? []).filter((plan) => plan.done).length} / {(draft.plans ?? []).length} 완료</span></div>{(draft.plans ?? []).map((plan) => <div key={plan.id} className={`daily-plan-row ${plan.done ? 'done' : ''}`}><button className="plan-check" onClick={() => updatePlan(plan.id, { done: !plan.done })} aria-label="완료 전환">{plan.done ? <Check size={14} /> : '○'}</button><div><span className={`subject-badge ${plan.subject}`}>{plan.subject}</span><b>{plan.title}</b>{plan.detail && <p>{plan.detail}</p>}</div>{plan.quantity && <small>{plan.quantity}</small>}<button className="icon-button danger" onClick={() => removePlan(plan.id)} aria-label="일정 삭제"><Trash2 size={16} /></button></div>)}
        <div className="new-plan-form"><div className="form-grid two"><Field label="과목"><select value={planDraft.subject} onChange={(event) => setPlanDraft({ ...planDraft, subject: event.target.value as Subject | '생활' })}>{[...SUBJECTS, '생활'].map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="훈련 / 일정명"><input value={planDraft.title} onChange={(event) => setPlanDraft({ ...planDraft, title: event.target.value })} placeholder="예: 수1 뉴런 1단원" /></Field></div><div className="form-grid two"><Field label="세부 계획"><input value={planDraft.detail} onChange={(event) => setPlanDraft({ ...planDraft, detail: event.target.value })} placeholder="예: 정적분으로 정의된 함수" /></Field><Field label="목표량"><input value={planDraft.quantity} onChange={(event) => setPlanDraft({ ...planDraft, quantity: event.target.value })} placeholder="예: 31문제 · 90분" /></Field></div><button className="text-button" onClick={addPlan}><Plus size={15} /> 일정 추가</button></div></section>
      <section className="daily-log-editor"><p className="eyebrow">EXECUTION LOG</p>{selectedStudy && selectedStudy.total > 0 && <div className="daily-study-summary"><div><Clock3 size={18} /><span><small>타이머 자동 집계</small><strong>{formatStudyTime(selectedStudy.total)}</strong></span></div><div>{SUBJECTS.map((subject) => selectedStudy.subjects[subject] ? <span key={subject} className={`subject-badge ${subject}`}>{subject} · {formatStudyTime(selectedStudy.subjects[subject]!)}</span> : null)}</div></div>}<div className="form-grid"><Field label="실행 기록"><TextArea value={draft.study} onChange={(value) => setDraft({ ...draft, study: value })} placeholder={'실제로 수행한 내용\n예: 수1 기출 31문제 중 28문제 완료'} /></Field><div className="form-grid two"><Field label="수동 순공 시간(분) · 타이머 기록이 없을 때 사용"><input type="number" min="0" value={draft.minutes || ''} onChange={(event) => setDraft({ ...draft, minutes: Number(event.target.value) || 0 })} /></Field><Field label="시험 / 모의고사"><input value={draft.exam} onChange={(event) => setDraft({ ...draft, exam: event.target.value })} placeholder="예: 국어 서바이벌" /></Field></div><Field label="일정에 영향을 준 사건"><input value={draft.event} onChange={(event) => setDraft({ ...draft, event: event.target.value })} placeholder="예: 수능 시간표 실전 검증" /></Field><Field label={`컨디션 · ${draft.condition}/5`}><input type="range" min="1" max="5" value={draft.condition} onChange={(event) => setDraft({ ...draft, condition: Number(event.target.value) })} /></Field><Field label="회고 / 다음 조정"><TextArea value={draft.reflection} onChange={(value) => setDraft({ ...draft, reflection: value })} placeholder="예: 목표량보다 기준 검증을 우선한다." /></Field></div></section><div className="modal-actions"><SaveButton onClick={save} label="일정 저장" /></div>
    </div></div>}
  </div>;
}
