import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Check, Clock3, Crosshair, FileText, Gauge, ListTodo, Timer, TriangleAlert } from 'lucide-react';
import type { AppData, CalendarPlan } from '../types';
import { Card, Empty, PageHeader, Progress, SectionTitle } from '../components/Ui';
import { formatKoreanDate, formatMinutes, toDateKey, weekStartKey } from '../lib/date';
import { studentFeedback } from '../lib/feedback';
import DailyCoachCard from '../components/DailyCoachCard';

export default function Dashboard({ data, update, navigate }: { data: AppData; update: (fn: (value: AppData) => AppData) => void; navigate: (page: string) => void }) {
  const now = new Date(), today = toDateKey(now), weekStart = weekStartKey(now), todayPlans = data.calendar[today]?.plans ?? [];
  const [unreadFeedback, setUnreadFeedback] = useState(0), [showCompleted, setShowCompleted] = useState(false);
  useEffect(() => { void studentFeedback().then((value) => setUnreadFeedback(value.feedback.filter((item) => item.progress === 'active' && !item.acknowledgedByStudent).length)).catch(() => setUnreadFeedback(0)); }, []);
  const todaySeconds = data.sessions.filter((item) => item.date === today).reduce((sum, item) => sum + item.seconds, 0);
  const weekSeconds = data.sessions.filter((item) => item.date >= weekStart).reduce((sum, item) => sum + item.seconds, 0);
  const completed = todayPlans.filter((item) => item.done), incomplete = todayPlans.filter((item) => !item.done), next = incomplete[0];
  const plannedMinutes = useMemo(() => todayPlans.reduce((sum, item) => sum + (Number(item.quantity.match(/\d+/)?.[0]) || 0), 0), [todayPlans]);
  const capability = data.weeklyCapabilityGoals.find((item) => item.weekStart === weekStart && !item.done) ?? data.weeklyCapabilityGoals.find((item) => item.weekStart === weekStart);
  const latestDrill = [...data.wrongAnswerDrills].sort((a, b) => b.date.localeCompare(a.date))[0];
  const unresolved = data.wrongAnswerDrills.filter((item) => !item.retries?.some((retry) => retry.completedDate)).length;
  const pendingDrills = data.dailyDrills.filter((item) => !item.done && item.date <= today).length;
  const dday = Math.max(0, Math.ceil((new Date(`${data.examDate}T00:00:00`).getTime() - new Date(`${today}T00:00:00`).getTime()) / 86_400_000));
  const togglePlan = (id: string) => update((value) => { const entry = value.calendar[today]; if (!entry) return value; return { ...value, calendar: { ...value.calendar, [today]: { ...entry, plans: (entry.plans ?? []).map((item) => item.id === id ? { ...item, done: !item.done } : item) } } }; });
  const planRow = (item: CalendarPlan, done = false) => <div key={item.id} className={done ? 'done' : ''}><button className="plan-check" aria-label={`${item.title} 완료 상태 변경`} onClick={() => togglePlan(item.id)}>{done ? <Check size={14} /> : '○'}</button><span className={`subject-badge ${item.subject}`}>{item.subject}</span><div><b>{item.title}</b>{item.detail && <small>{item.detail}</small>}</div><em>{item.quantity}</em></div>;

  return <div><PageHeader eyebrow="TODAY'S EXECUTION" title="오늘의 실행" description={formatKoreanDate(now)} />
    <div className="dashboard-glance"><Card><span>오늘 진행률</span><strong>{todayPlans.length ? Math.round(completed.length / todayPlans.length * 100) : 0}%</strong><small>{completed.length} / {todayPlans.length} 완료</small></Card><Card><span>실제 학습</span><strong>{formatMinutes(todaySeconds / 60)}</strong><small>{plannedMinutes ? `계획 ${plannedMinutes}분` : '계획 시간 없음'}</small></Card><Card><span>NEXT</span><strong>{next?.title ?? '다음 일정 없음'}</strong><small>{next ? `${next.subject} · ${next.quantity}` : '오늘 일정 완료'}</small></Card><Card><span>미처리</span><strong>{unresolved + pendingDrills + unreadFeedback}</strong><small>오답 {unresolved} · Drill {pendingDrills} · 피드백 {unreadFeedback}</small></Card></div>
    <DailyCoachCard data={data} />
    <div className="execution-hero"><Card className="execution-dday"><span className="card-label">수능까지</span><strong>D-{dday}</strong><p>{data.examDate.replaceAll('-', '.')}</p></Card><Card className="execution-focus"><span className="card-label">TODAY'S FOCUS</span><h2>{capability?.ability ?? '이번 주 능력 목표를 설정하세요.'}</h2><p>{capability?.successCriterion ?? 'Weekly Drill에서 이번 주에 검증할 능력과 성공 기준을 설정할 수 있습니다.'}</p><button className="text-button" onClick={() => navigate('drill')}>능력 목표 보기 <ArrowRight size={15} /></button></Card></div>
    <div className="execution-metrics"><Card><span className="metric-icon"><Clock3 size={19} /></span><span className="card-label">오늘 학습</span><strong className="metric-value">{formatMinutes(todaySeconds / 60)}</strong><Progress value={todaySeconds / 60} max={600} /></Card><Card><span className="metric-icon"><Timer size={19} /></span><span className="card-label">이번 주 누적</span><strong className="metric-value">{formatMinutes(weekSeconds / 60)}</strong><Progress value={weekSeconds / 60} max={3000} /></Card><Card><span className="metric-icon"><ListTodo size={19} /></span><span className="card-label">오늘 계획</span><strong className="metric-value">{completed.length} / {todayPlans.length}</strong><Progress value={completed.length} max={Math.max(todayPlans.length, 1)} /></Card></div>
    <div className="execution-grid"><Card className="today-plan-card"><div className="execution-card-head"><div><span className="card-label">WEEKLY PLAN</span><h2>오늘의 계획</h2></div><button className="text-button" onClick={() => navigate('plans')}>전체 계획 <ArrowRight size={15} /></button></div>{todayPlans.length ? <div className="today-plan-list">{incomplete.map((item) => planRow(item))}{completed.length > 0 && <><button className="completed-toggle" onClick={() => setShowCompleted(!showCompleted)}>완료된 학습 {completed.length}개 {showCompleted ? '접기' : '펼치기'}</button>{showCompleted && completed.map((item) => planRow(item, true))}</>}</div> : <Empty>오늘 계획이 없습니다. Weekly Plan에서 추가하세요.</Empty>}</Card><div className="execution-side"><Card className="drill-action"><div className="execution-card-head"><div><span className="card-label">LATEST DRILL</span><h2>최근 오답 교정</h2></div><Crosshair size={19} /></div>{latestDrill ? <><span className={`subject-badge ${latestDrill.subject}`}>{latestDrill.subject}</span><h3>{latestDrill.question || latestDrill.source}</h3><p><b>교정 행동</b> {latestDrill.correction || '아직 교정 행동이 기록되지 않았습니다.'}</p><button className="text-button" onClick={() => navigate('drill')}>오답 Drill 보기 <ArrowRight size={15} /></button></> : <div className="mini-empty"><TriangleAlert size={17} /> 최근 오답 Drill이 없습니다.</div>}</Card></div></div>
    <SectionTitle title="오늘의 기록 공간" meta="기록은 기존 학습 데이터에 연결됩니다" /><div className="execution-links"><button onClick={() => navigate('notion')}><FileText size={18} /><span><b>Notion</b><small>개인 영역 · 교사에게 공유되지 않음</small></span><ArrowRight size={16} /></button><button onClick={() => navigate('scores')}><Gauge size={18} /><span><b>실모 기록</b><small>점수 변화와 시험 분석</small></span><ArrowRight size={16} /></button></div>
  </div>;
}
