import { useEffect, useMemo, useState } from 'react';
import { Check, ClipboardPlus, Goal, MessageSquareText } from 'lucide-react';
import type { AppData } from '../types';
import { acknowledgeFeedback, linkFeedback, makeDailyDrill, makeWeeklyGoal, studentFeedback, type Feedback } from '../lib/feedback';
import { Card, Empty, PageHeader } from '../components/Ui';

export default function FeedbackInbox({ data, update }: { data:AppData; update:(fn:(value:AppData)=>AppData)=>void }) {
 const [items,setItems]=useState<Feedback[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const refresh=()=>studentFeedback().then(v=>setItems(v.feedback)).catch(e=>setError(e instanceof Error?e.message:'피드백을 불러오지 못했습니다.'));
 useEffect(()=>{void refresh();},[]);
 const active=useMemo(()=>items.filter(item=>item.progress==='active'),[items]);
 const act=async(item:Feedback,kind:'ack'|'daily'|'weekly')=>{setBusy(item.id);setError('');try{if(kind==='ack')await acknowledgeFeedback(item.id);else if(kind==='daily'){const drill=makeDailyDrill(item);await linkFeedback(item.id,'daily_drill',drill.id);update(value=>({...value,dailyDrills:[drill,...value.dailyDrills]}));}else{const goal=makeWeeklyGoal(item);await linkFeedback(item.id,'weekly_goal',goal.id);update(value=>({...value,weeklyCapabilityGoals:[goal,...value.weeklyCapabilityGoals]}));}await refresh();}catch(e){setError(e instanceof Error?e.message:'피드백 반영에 실패했습니다.');}finally{setBusy('');}};
 return <div><PageHeader eyebrow="TEACHER FEEDBACK" title="선생님 피드백" description={active.length?`새로 확인할 피드백 ${active.filter(item=>!item.acknowledgedByStudent).length}개`:'현재 활성 피드백이 없습니다.'}/>{error&&<p className="team-error">{error}</p>}{active.length?<div className="feedback-list">{active.map(item=><Card key={item.id} className="feedback-card"><div className="feedback-card-head"><div><span className={`subject-badge ${item.subject??'전체'}`}>{item.type==='academic_management'?'ACADEMIC MANAGER':item.subject}</span><small>{item.teacher_name||'선생님'} · {item.categories?.join(' · ')}</small><h2>{item.title||item.bottleneck||'학습 피드백'}</h2></div><span className={`feedback-status ${item.status}`}>{item.status==='needs_improvement'?'개선 필요':item.status==='stable'?'안정':'보통'}</span></div>{item.observation&&<p className="feedback-observation">{item.observation}</p>}<div className="feedback-actions-text"><section><b>이번 주 행동</b><p>{item.action||'행동 제안이 없습니다.'}</p></section><section><b>성공 기준</b><p>{item.success_criterion||'성공 기준이 없습니다.'}</p></section></div>{item.comment&&<p className="feedback-comment">{item.comment}</p>}<div className="feedback-buttons"><button className="button" disabled={busy===item.id||item.acknowledgedByStudent} onClick={()=>act(item,'ack')}><Check size={15}/>{item.acknowledgedByStudent?'확인함':'확인'}</button><button className="button" disabled={busy===item.id||Boolean(item.linked_daily_drill_id)} onClick={()=>act(item,'daily')}><ClipboardPlus size={15}/>{item.linked_daily_drill_id?'Daily Drill 반영됨':'Daily Drill에 추가'}</button><button className="button" disabled={busy===item.id||Boolean(item.linked_weekly_goal_id)} onClick={()=>act(item,'weekly')}><Goal size={15}/>{item.linked_weekly_goal_id?'Weekly Goal 반영됨':'Weekly Goal에 반영'}</button></div></Card>)}</div>:<Empty><MessageSquareText size={18}/> 아직 작성된 피드백이 없습니다.</Empty>}</div>;
}
