import { useEffect, useState } from 'react';
import { loadCloudflareConfig } from '../lib/cloudflare';
import { PageHeader } from '../components/Ui';

type Account={id:string;username:string;role:string;active:number}; type Assignment={id:string;teacher_name:string;role:string;subject?:string};
async function request<T>(path:string,method='GET',body?:unknown):Promise<T>{const c=loadCloudflareConfig(),r=await fetch(c.url.replace(/\/+$/,'')+path,{method,headers:{Authorization:`Bearer ${c.token}`,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const v=await r.json() as T&{error?:string};if(!r.ok)throw new Error(v.error||'요청 실패');return v;}
export default function FeedbackAdmin(){
 const [accounts,setAccounts]=useState<Account[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[accountDraft,setAccountDraft]=useState({username:'',password:'',role:'subject_teacher'}),[draft,setDraft]=useState({teacherId:'',role:'subject_teacher',subject:'수학'}),[error,setError]=useState('');
 const refresh=async()=>{try{const [a,b]=await Promise.all([request<{accounts:Account[]}>('/api/support/accounts'),request<{assignments:Assignment[]}>('/api/collab/assignments')]);setAccounts(a.accounts.filter(x=>['subject_teacher','academic_manager'].includes(x.role)));setAssignments(b.assignments);}catch(e){setError(e instanceof Error?e.message:'관리 데이터를 불러오지 못했습니다.');}};useEffect(()=>{void refresh();},[]);
 const createAccount=async(e:React.FormEvent)=>{e.preventDefault();try{await request('/api/support/accounts','POST',accountDraft);setAccountDraft({...accountDraft,username:'',password:''});await refresh();}catch(e){setError(e instanceof Error?e.message:'교사 계정 생성 실패');}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();try{await request('/api/collab/assignments','POST',{...draft,subject:draft.role==='subject_teacher'?draft.subject:undefined,permissions:{viewSessions:true,viewScores:true,viewWrongAnswers:true,viewCalendar:true,viewWeeklyGoals:true,createFeedback:true,createDrillSuggestion:true}});await refresh();}catch(e){setError(e instanceof Error?e.message:'담당 배정 실패');}};
 return <main className="team-page"><PageHeader eyebrow="ADMIN" title="교사 계정 · 담당 배정" description="학생-교사 연결과 필요한 학습 데이터 권한을 관리합니다."/>{error&&<p className="team-error">{error}</p>}<section className="team-panel"><h2>교사 계정 생성</h2><form onSubmit={createAccount}><label>아이디<input required maxLength={40} value={accountDraft.username} onChange={e=>setAccountDraft({...accountDraft,username:e.target.value})}/></label><label>임시 비밀번호<input required minLength={12} type="password" value={accountDraft.password} onChange={e=>setAccountDraft({...accountDraft,password:e.target.value})}/></label><label>역할<select value={accountDraft.role} onChange={e=>setAccountDraft({...accountDraft,role:e.target.value})}><option value="subject_teacher">교과 선생님</option><option value="academic_manager">학업 관리 선생님</option></select></label><button className="button primary">교사 계정 생성</button></form></section><section className="team-panel"><h2>학생 담당 배정</h2><form onSubmit={save}><label>교사<select required value={draft.teacherId} onChange={e=>setDraft({...draft,teacherId:e.target.value})}><option value="">선택</option>{accounts.map(item=><option key={item.id} value={item.id}>{item.username} · {item.role}</option>)}</select></label><label>역할<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="subject_teacher">교과 선생님</option><option value="academic_manager">학업 관리 선생님</option></select></label>{draft.role==='subject_teacher'&&<label>담당 과목<select value={draft.subject} onChange={e=>setDraft({...draft,subject:e.target.value})}>{['국어','수학','영어','탐구'].map(item=><option key={item}>{item}</option>)}</select></label>}<button className="button primary">담당 배정</button></form></section><section className="team-panel"><h2>현재 담당</h2>{assignments.length?assignments.map(item=><div className="team-record" key={item.id}><b>{item.teacher_name}</b> · {item.role==='academic_manager'?'학업 관리':'교과'} {item.subject&&`· ${item.subject}`}</div>):<p>아직 담당 배정이 없습니다.</p>}</section></main>;
}
