import { useEffect,useMemo,useState } from 'react';
import { BookMarked,Check,ChevronDown,Plus,Trash2 } from 'lucide-react';
import { Card,Empty,Field,PageHeader,TextArea } from '../components/Ui';
import { archiveApi,type ArchiveEntry,type ArchiveSubject,type CoreRule,type MasteryStatus } from '../lib/archiveApi';
import type { AppData } from '../types';
const subjects:{id:ArchiveSubject;label:string}[]=[{id:'korean',label:'국어'},{id:'math',label:'수학'},{id:'english',label:'영어'}];
const mastery:{id:MasteryStatus;label:string}[]=[{id:'input',label:'입력'},{id:'understanding',label:'이해'},{id:'reproduction',label:'재현'},{id:'automated',label:'자동화'}];
const today=()=>new Date().toISOString().slice(0,10);
const blank=()=>({subject:'korean' as ArchiveSubject,year:new Date().getFullYear(),month:new Date().getMonth()+1,institution:'KICE',institutionCustomName:'',examName:'',sourceName:'',questionNumber:'',category:'',subcategory:'',title:'',studiedAt:today(),masteryStatus:'input' as MasteryStatus,memo:'',conditionSummary:'',firstThought:'',representation:'',solutionFlow:'',bottleneck:'',transfer:'',mainIdea:'',structureSummary:'',keyExpression:'',reviewEnabled:false});
export default function LearningArchive({data,update}:{data:AppData;update:(fn:(v:AppData)=>AppData)=>void}){
 const [view,setView]=useState<'archive'|'rules'|'review'>('archive'),[entries,setEntries]=useState<ArchiveEntry[]>([]),[reviewEntries,setReviewEntries]=useState<ArchiveEntry[]>([]),[rules,setRules]=useState<CoreRule[]>([]),[form,setForm]=useState(blank()),[editing,setEditing]=useState<ArchiveEntry>(),[open,setOpen]=useState(false),[selected,setSelected]=useState<ArchiveEntry>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[subject,setSubject]=useState(''),[color,setColor]=useState(''),[sort,setSort]=useState<'up'|'down'>('down'),[ruleForm,setRuleForm]=useState({subject:'korean' as ArchiveSubject,title:'',content:'',tags:'',masteryStatus:'input' as MasteryStatus});
 const load=async()=>{setBusy(true);setError('');try{const params=new URLSearchParams();if(query)params.set('q',query);if(subject)params.set('subject',subject);if(color)params.set('color',color);const [a,r]=await Promise.all([archiveApi<{entries:ArchiveEntry[]}>(`/api/archive/entries?${params}`),archiveApi<{rules:CoreRule[]}>('/api/archive/rules')]);setEntries(a.entries);setRules(r.rules);}catch(e){setError(e instanceof Error?e.message:'불러오지 못했습니다.')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[query,subject,color]);
 const shown=useMemo(()=>[...entries].sort((a,b)=>(sort==='down'?-1:1)*a.studiedAt.localeCompare(b.studiedAt)),[entries,sort]);
 const save=async()=>{if(!form.title.trim())return;setBusy(true);try{await archiveApi(editing?`/api/archive/entries/${editing.id}`:'/api/archive/entries',editing?'PATCH':'POST',form);setOpen(false);setEditing(undefined);setForm(blank());await load()}catch(e){setError(e instanceof Error?e.message:'저장 실패')}finally{setBusy(false)}};
 const remove=async(id:string)=>{if(!window.confirm('이 Archive Entry를 삭제할까요?'))return;await archiveApi(`/api/archive/entries/${id}`,'DELETE');setSelected(undefined);await load()};
 const addAnnotation=async(entry:ArchiveEntry)=>{const text=window.prompt('Annotation 내용');if(!text)return;const color=window.prompt('색상 (black/blue/green/red 또는 사용자 색상)','black')||'black';await archiveApi('/api/archive/annotations','POST',{archiveEntryId:entry.id,color,type:'note',text,order:entry.annotations.length});await load()};
 const addRule=async()=>{if(!ruleForm.title||!ruleForm.content)return;await archiveApi('/api/archive/rules','POST',{...ruleForm,tags:ruleForm.tags.split(',').map(v=>v.trim()).filter(Boolean)});setRuleForm({...ruleForm,title:'',content:'',tags:''});await load()};
 const linkRule=async(entry:ArchiveEntry)=>{const id=window.prompt(`연결할 Core Rule ID\n${rules.map(r=>`${r.id}: ${r.title}`).join('\n')}`);if(!id)return;await archiveApi('/api/archive/rule-links','POST',{archiveEntryId:entry.id,coreRuleId:id});await load()};
 const createWrong=async(entry:ArchiveEntry)=>{if(entry.wrongAnswerId)return;const id=crypto.randomUUID();update(v=>({...v,wrongAnswerDrills:[{id,date:entry.studiedAt.slice(0,10),subject:entry.subject==='korean'?'국어':entry.subject==='math'?'수학':'영어',source:[entry.examName,entry.sourceName].filter(Boolean).join(' · '),question:entry.questionNumber||entry.title,wrongJudgment:entry.firstThought||'',missedCue:entry.bottleneck||'',correction:entry.memo,transfer:entry.transfer||'',archiveEntryId:entry.id,retries:[]},...v.wrongAnswerDrills]}));await archiveApi('/api/archive/wrong-answer-links','POST',{archiveEntryId:entry.id,wrongAnswerId:id});await load()};
 const openReview=async()=>{setView('review');try{const value=await archiveApi<{entries:ArchiveEntry[]}>('/api/archive/review');setReviewEntries(value.entries)}catch(e){setError(e instanceof Error?e.message:'Review 조회 실패')}};const review=async(entry:ArchiveEntry,success:boolean)=>{await archiveApi('/api/archive/reviews','POST',{archiveEntryId:entry.id,success,nextIntervalDays:success?7:3,coreRuleRevealed:false});await openReview()};
 return <div className="archive-page"><PageHeader eyebrow="LEARNING ARCHIVE" title="Learning Archive" description="문항에서 얻은 판단 기준을 기록하고 Core Rule로 연결해 재현합니다."/><div className="archive-tabs">{([['archive','Archive'],['rules','Core Rules'],['review','Review']] as const).map(v=><button className={view===v[0]?'active':''} onClick={()=>v[0]==='review'?void openReview():setView(v[0])} key={v[0]}>{v[1]}</button>)}</div>{error&&<p className="team-error" role="alert">{error}</p>}
 {view==='archive'&&<><Card className="archive-toolbar"><input aria-label="검색" placeholder="제목·메모·시험·출처 검색" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="과목" value={subject} onChange={e=>setSubject(e.target.value)}><option value="">전체 과목</option>{subjects.map(s=><option value={s.id} key={s.id}>{s.label}</option>)}</select><select aria-label="색상" value={color} onChange={e=>setColor(e.target.value)}><option value="">전체 색상</option>{['black','blue','green','red'].map(v=><option key={v}>{v}</option>)}</select><button className="button" onClick={()=>setSort(v=>v==='down'?'up':'down')}>날짜 {sort==='down'?'↓':'↑'}</button><button className="button primary" onClick={()=>{setEditing(undefined);setForm(blank());setOpen(true)}}><Plus size={16}/>Entry</button></Card>{busy&&!entries.length?<p>불러오는 중…</p>:shown.length?<div className="archive-grid">{shown.map(entry=><Card className="archive-card" key={entry.id}><button className="archive-card-main" onClick={()=>setSelected(entry)}><span className="card-label">{subjects.find(s=>s.id===entry.subject)?.label} · {entry.year}.{entry.month} · {entry.institution}</span><h3>{entry.title}</h3><p>{entry.examName} {entry.sourceName} {entry.questionNumber}</p><span className={`mastery ${entry.masteryStatus}`}>{mastery.find(v=>v.id===entry.masteryStatus)?.label}</span><div className="annotation-counts">{Object.entries(entry.annotations.reduce<Record<string,number>>((a,v)=>({...a,[v.color]:(a[v.color]||0)+1}),{})).map(([c,n])=><span key={c} data-color={c}>{c} {n}</span>)}</div><div>{entry.coreRules.map(r=><span className="rule-chip" key={r.id}>{r.title}</span>)}</div></button></Card>)}</div>:<Empty title="Archive Entry가 없습니다." description="첫 문항 분석을 기록해 보세요."/>}</>}
 {view==='rules'&&<div className="archive-rules"><Card><h2>Core Rule 추가</h2><div className="form-grid two"><Field label="과목"><select value={ruleForm.subject} onChange={e=>setRuleForm({...ruleForm,subject:e.target.value as ArchiveSubject})}>{subjects.map(s=><option value={s.id} key={s.id}>{s.label}</option>)}</select></Field><Field label="체화 상태"><select value={ruleForm.masteryStatus} onChange={e=>setRuleForm({...ruleForm,masteryStatus:e.target.value as MasteryStatus})}>{mastery.map(v=><option value={v.id} key={v.id}>{v.label}</option>)}</select></Field><Field label="제목"><input value={ruleForm.title} onChange={e=>setRuleForm({...ruleForm,title:e.target.value})}/></Field><Field label="태그"><input value={ruleForm.tags} placeholder="쉼표로 구분" onChange={e=>setRuleForm({...ruleForm,tags:e.target.value})}/></Field></div><Field label="Rule"><TextArea value={ruleForm.content} onChange={content=>setRuleForm({...ruleForm,content})}/></Field><button className="button primary" onClick={addRule}>저장</button></Card><div className="archive-grid">{rules.map(rule=><Card key={rule.id}><span className="card-label">{rule.subject} · 사용 {rule.usageCount}회</span><h3>{rule.title}</h3><p>{rule.content}</p><div>{rule.tags.map(t=><span className="rule-chip" key={t}>#{t}</span>)}</div><details><summary>연결 Entry 보기 <ChevronDown size={14}/></summary>{entries.filter(e=>e.coreRules.some(r=>r.id===rule.id)).map(e=><button className="row-link" key={e.id} onClick={()=>{setSelected(e);setView('archive')}}>{e.title}</button>)}</details></Card>)}</div></div>}
 {view==='review'&&<div><p className="archive-review-note">Core Rule이 있거나 Review를 활성화한 Entry만 표시됩니다. 기본 간격은 3/7/14/30일입니다.</p>{(['overdue','today','upcoming'] as const).map(bucket=><section key={bucket}><div className="section-title"><h2>{bucket==='overdue'?'연체':bucket==='today'?'오늘':'예정'}</h2><span>{reviewEntries.filter(e=>e.reviewBucket===bucket).length}개</span></div><div className="archive-grid">{reviewEntries.filter(e=>e.reviewBucket===bucket).map(e=><Card key={e.id}><span className="card-label">복습 {e.nextReviewAt}</span><h3>{e.title}</h3><details><summary>Core Rule 보기</summary>{e.coreRules.map(r=><p key={r.id}><b>{r.title}</b><br/>{r.content}</p>)}</details><div className="review-actions"><button className="button" onClick={()=>review(e,false)}>재현 실패</button><button className="button primary" onClick={()=>review(e,true)}><Check size={15}/>재현 성공</button></div></Card>)}</div></section>)}</div>}
 {open&&<div className="sheet-backdrop" onClick={()=>setOpen(false)}><aside className="detail-sheet archive-editor" onClick={e=>e.stopPropagation()}><header><h2>{editing?'Entry 수정':'Archive Entry'}</h2><button className="icon-button" onClick={()=>setOpen(false)}>×</button></header><div className="sheet-content"><div className="form-grid two"><Field label="과목"><select value={form.subject} onChange={e=>setForm({...form,subject:e.target.value as ArchiveSubject})}>{subjects.map(s=><option value={s.id} key={s.id}>{s.label}</option>)}</select></Field><Field label="학습일"><input type="date" value={form.studiedAt} onChange={e=>{const d=new Date(e.target.value);setForm({...form,studiedAt:e.target.value,year:d.getFullYear(),month:d.getMonth()+1})}}/></Field><Field label="기관"><select value={form.institution} onChange={e=>setForm({...form,institution:e.target.value})}>{['KICE','education_office','EBS','private','textbook','custom'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="기관 직접 입력"><input value={form.institutionCustomName} onChange={e=>setForm({...form,institutionCustomName:e.target.value})}/></Field><Field label="시험명"><input value={form.examName} onChange={e=>setForm({...form,examName:e.target.value})}/></Field><Field label="출처"><input value={form.sourceName} onChange={e=>setForm({...form,sourceName:e.target.value})}/></Field><Field label="문항"><input value={form.questionNumber} onChange={e=>setForm({...form,questionNumber:e.target.value})}/></Field><Field label="제목"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="대분류"><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></Field><Field label="세부유형"><input value={form.subcategory} onChange={e=>setForm({...form,subcategory:e.target.value})}/></Field><Field label="체화"><select value={form.masteryStatus} onChange={e=>setForm({...form,masteryStatus:e.target.value as MasteryStatus})}>{mastery.map(v=><option value={v.id} key={v.id}>{v.label}</option>)}</select></Field><label className="check-row"><input type="checkbox" checked={form.reviewEnabled} onChange={e=>setForm({...form,reviewEnabled:e.target.checked})}/>Review 활성화</label></div><Field label="메모"><TextArea value={form.memo} onChange={memo=>setForm({...form,memo})}/></Field>{form.subject==='math'&&[['conditionSummary','조건 요약'],['firstThought','첫 생각'],['representation','표상'],['solutionFlow','풀이 흐름'],['bottleneck','병목'],['transfer','전이']].map(([k,l])=><Field label={l} key={k}><TextArea value={(form as any)[k]} onChange={v=>setForm({...form,[k]:v})}/></Field>)}{form.subject==='english'&&[['mainIdea','핵심 주제'],['structureSummary','구조 요약'],['keyExpression','핵심 표현']].map(([k,l])=><Field label={l} key={k}><TextArea value={(form as any)[k]} onChange={v=>setForm({...form,[k]:v})}/></Field>)}<button className="button primary" disabled={busy} onClick={save}>저장</button></div></aside></div>}
 {selected&&<div className="sheet-backdrop" onClick={()=>setSelected(undefined)}><aside className="detail-sheet archive-detail" onClick={e=>e.stopPropagation()}><header><div><span className="card-label">{selected.subject} · {selected.studiedAt.slice(0,10)}</span><h2>{selected.title}</h2></div><button className="icon-button" onClick={()=>setSelected(undefined)}>×</button></header><div className="sheet-content"><div className="archive-detail-tabs"><span>분석</span><span>Annotation</span><span>Core</span><span>문항</span><span>Review</span></div><p>{selected.memo||'메모 없음'}</p><section><h3>Annotation</h3>{selected.annotations.map(a=><p className="annotation-row" data-color={a.color} key={a.id}><span>{a.color} · {a.type}</span>{a.text}</p>)}<button className="button" onClick={()=>addAnnotation(selected)}>Annotation 추가</button></section><section><h3>Core Rules</h3>{selected.coreRules.map(r=><p key={r.id}><b>{r.title}</b> · {r.content}</p>)}<button className="button" onClick={()=>linkRule(selected)}>Core Rule 연결</button></section><section className="review-actions"><button className="button" onClick={()=>createWrong(selected)}>{selected.wrongAnswerId?'연결된 Wrong Answer 있음':'Wrong Answer Drill 생성'}</button><button className="button" onClick={()=>{setEditing(selected);setForm({...blank(),...selected});setSelected(undefined);setOpen(true)}}>수정</button><button className="icon-button danger" onClick={()=>remove(selected.id)}><Trash2/></button></section></div></aside></div>}</div>;
}
