import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Check, ChevronLeft, ChevronRight, FilePlus2, Heading1, ListChecks, Plus, Text, Trash2 } from 'lucide-react';
import type { AppData, NotionBlock, NotionPage } from '../types';
import { Card, Empty, PageHeader } from '../components/Ui';
import { toDateKey, uid } from '../lib/date';
import '../personal-schedule.css';

const createPage = (): NotionPage => ({ id: uid(), title: '새 페이지', icon: '📝', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), blocks: [] });
const block = (type: NotionBlock['type'], date = toDateKey()): NotionBlock => ({ id: uid(), type, content: '', checked: false, category: type === 'todo' ? '개인' : '', date });
const statusOf = (item: NotionBlock): 'pending' | 'open' | 'done' | 'postponed' => item.status ?? (item.checked ? 'done' : 'pending');
const scheduledDate = (item: NotionBlock) => statusOf(item) === 'postponed' && item.postponedTo ? item.postponedTo : item.date ?? '';
const dateLabel = (date: string) => new Intl.DateTimeFormat('ko-KR', { month: 'long', day: 'numeric', weekday: 'short' }).format(new Date(`${date}T12:00:00`));

export default function NotionWorkspace({ data, update }: { data: AppData; update: (fn: (value: AppData) => AppData) => void }) {
  const [selectedId, setSelectedId] = useState<string | null>(data.notionPages[0]?.id ?? null);
  const [view, setView] = useState<'calendar' | 'memo'>('calendar');
  const [cursor, setCursor] = useState(() => new Date());
  const [selectedDate, setSelectedDate] = useState(toDateKey());
  const page = useMemo(() => data.notionPages.find((item) => item.id === selectedId) ?? data.notionPages[0], [data.notionPages, selectedId]);
  const allBlocks = useMemo(() => data.notionPages.flatMap(item => item.blocks.map(blockItem => ({ page: item, block: blockItem }))), [data.notionPages]);
  const datedBlocks = allBlocks.filter(item => item.block.type !== 'heading' && Boolean(item.block.date));
  const selectedBlocks = datedBlocks.filter(item => scheduledDate(item.block) === selectedDate);
  const year = cursor.getFullYear(), month = cursor.getMonth();
  const cells = useMemo(() => { const first = new Date(year, month, 1); const days = new Date(year, month + 1, 0).getDate(); return [...Array(first.getDay()).fill(null), ...Array.from({ length: days }, (_, index) => index + 1)]; }, [year, month]);
  useEffect(() => { if (!selectedId && data.notionPages[0]) setSelectedId(data.notionPages[0].id); }, [data.notionPages, selectedId]);
  const savePage = (id: string, change: Partial<NotionPage>) => update(value => ({ ...value, notionPages: value.notionPages.map(item => item.id === id ? { ...item, ...change, updatedAt: new Date().toISOString() } : item) }));
  const addPage = () => { const item = createPage(); update(value => ({ ...value, notionPages: [...value.notionPages, item] })); setSelectedId(item.id); setView('memo'); };
  const deletePage = (id: string) => { update(value => ({ ...value, notionPages: value.notionPages.filter(item => item.id !== id) })); setSelectedId(data.notionPages.find(item => item.id !== id)?.id ?? null); };
  const addBlock = (type: NotionBlock['type'], date = selectedDate) => {
    let target = page;
    if (!target) { target = createPage(); setSelectedId(target.id); }
    const next = block(type, date);
    update(value => ({ ...value, notionPages: target!.id === page?.id
      ? value.notionPages.map(item => item.id === target!.id ? { ...item, blocks: [...item.blocks, next], updatedAt: new Date().toISOString() } : item)
      : [...value.notionPages, { ...target!, blocks: [next] }] }));
    setView('memo');
  };
  const updateBlock = (pageId: string, id: string, change: Partial<NotionBlock>) => update(value => ({ ...value, notionPages: value.notionPages.map(item => item.id === pageId ? { ...item, blocks: item.blocks.map(entry => entry.id === id ? { ...entry, ...change, ...(change.status ? { checked: change.status === 'done' } : {}) } : entry), updatedAt: new Date().toISOString() } : item) }));
  const deleteBlock = (pageId: string, id: string) => update(value => ({ ...value, notionPages: value.notionPages.map(item => item.id === pageId ? { ...item, blocks: item.blocks.filter(entry => entry.id !== id), updatedAt: new Date().toISOString() } : item) }));
  const setStatus = (pageId: string, item: NotionBlock, status: 'open' | 'done' | 'postponed') => updateBlock(pageId, item.id, { status, checked: status === 'done', ...(status === 'postponed' && !item.postponedTo ? { postponedTo: item.date ?? selectedDate } : {}) });
  const monthTags = new Map<string, number>();
  for (const item of datedBlocks) { const date = scheduledDate(item.block); monthTags.set(date, (monthTags.get(date) ?? 0) + 1); }

  return <div className="personal-schedule-page">
    <PageHeader eyebrow="PRIVATE SCHEDULE" title="일정" description="학습 계획은 Plan에서, 장보기와 약속 같은 개인 일정은 여기에서 기록합니다." action={<div className="personal-header-actions"><button className={`button ${view === 'calendar' ? 'primary' : ''}`} onClick={() => setView('calendar')}><CalendarDays size={16}/> 달력</button><button className={`button ${view === 'memo' ? 'primary' : ''}`} onClick={() => setView('memo')}><Text size={16}/> 메모</button><button className="button primary" onClick={() => addBlock('todo', selectedDate)}><Plus size={16}/> 일정 추가</button></div>} />
    {view === 'calendar' ? <div className="personal-schedule-layout">
      <Card className="personal-calendar-card"><div className="personal-calendar-head"><button aria-label="이전 달" onClick={() => setCursor(new Date(year, month - 1, 1))}><ChevronLeft/></button><h2>{year}년 {month + 1}월</h2><button aria-label="다음 달" onClick={() => setCursor(new Date(year, month + 1, 1))}><ChevronRight/></button></div><div className="personal-weekdays">{'일월화수목금토'.split('').map(day => <span key={day}>{day}</span>)}</div><div className="personal-calendar-grid">{cells.map((day, index) => day ? (() => { const date = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`; const count = monthTags.get(date) ?? 0; return <button key={date} className={`${date === selectedDate ? 'selected' : ''} ${date === toDateKey() ? 'today' : ''}`} onClick={() => setSelectedDate(date)}><b>{day}</b>{count > 0 && <small>{count}개 기록</small>}{datedBlocks.filter(item => scheduledDate(item.block) === date).slice(0, 2).map(item => <em key={item.block.id}>{item.block.category || (item.block.type === 'todo' ? '개인' : '메모')} · {item.block.content || '제목 없음'}</em>)}</button>; })() : <span key={`empty-${index}`} />)}</div></Card>
      <Card className="personal-day-panel"><div className="personal-day-head"><div><span className="card-label">SELECTED DAY</span><h2>{dateLabel(selectedDate)}</h2></div><button className="button" onClick={() => addBlock('todo', selectedDate)}><Plus size={15}/> 추가</button></div>{selectedBlocks.length ? <div className="personal-day-list">{selectedBlocks.map(({ page: owner, block: item }) => { const status = statusOf(item); return <article key={item.id} className={`personal-item status-${status}`}><div className="personal-item-meta"><span className="personal-category">{status === 'postponed' ? '[연기됨] ' : ''}{item.category || (item.type === 'todo' ? '개인' : '메모')}</span><small>{owner.title}</small></div><b>{item.content || (item.type === 'todo' ? '할 일 입력' : '메모 입력')}</b>{item.type === 'todo' && <div className="personal-status-options" role="group" aria-label="일정 상태"><button className={status === 'done' ? 'active' : ''} onClick={() => setStatus(owner.id, item, 'done')}>완료</button><button className={status === 'open' ? 'active' : ''} onClick={() => setStatus(owner.id, item, 'open')}>미완료</button><button className={status === 'postponed' ? 'active' : ''} onClick={() => setStatus(owner.id, item, 'postponed')}>연기</button></div>}{status === 'postponed' && <label className="personal-move-date">옮길 날짜<input type="date" value={item.postponedTo ?? item.date ?? selectedDate} onChange={event => updateBlock(owner.id, item.id, { postponedTo: event.target.value })}/></label>}</article>; })}</div> : <Empty title="이 날짜에 기록이 없습니다." description="일정이나 메모를 추가하면 날짜별 기록으로 모입니다." action={<button className="button" onClick={() => addBlock('todo', selectedDate)}>일정 추가</button>} />}</Card>
    </div> : <div className="notion-workspace personal-memo-workspace">
      <Card className="notion-sidebar"><div className="notion-side-head"><span>PRIVATE PAGES</span><button onClick={addPage} aria-label="새 페이지"><Plus size={16}/></button></div>{data.notionPages.length ? <nav>{data.notionPages.map(item => <button className={page?.id === item.id ? 'active' : ''} onClick={() => setSelectedId(item.id)} key={item.id}><span>{item.icon}</span><b>{item.title || '제목 없는 페이지'}</b></button>)}</nav> : <p>아직 페이지가 없습니다.</p>}<button className="button" onClick={addPage}><FilePlus2 size={15}/> 새 페이지</button></Card>
      {page ? <Card className="notion-editor"><div className="notion-page-top"><input value={page.icon} maxLength={4} aria-label="아이콘" onChange={event => savePage(page.id, { icon: event.target.value })}/><button className="icon-button danger" onClick={() => deletePage(page.id)} aria-label="페이지 삭제"><Trash2 size={17}/></button></div><input className="notion-title" value={page.title} onChange={event => savePage(page.id, { title: event.target.value })} placeholder="제목 없는 페이지"/><small className="notion-updated">마지막 수정 {new Intl.DateTimeFormat('ko-KR', { month: 'long', day: 'numeric' }).format(new Date(page.updatedAt))}</small>
        <div className="notion-blocks">{page.blocks.map(item => { const status = statusOf(item); return <div key={item.id} className={`notion-block ${item.type} status-${status}`}><div className="block-main">{item.type === 'heading' ? <Heading1 size={17}/> : item.type === 'todo' ? <ListChecks size={17}/> : <Text size={17}/>}<textarea className={item.type === 'todo' ? `personal-task-text status-${status}` : ''} rows={item.type === 'text' ? 3 : 1} value={item.content} onChange={event => updateBlock(page.id, item.id, { content: event.target.value })} placeholder={item.type === 'heading' ? '제목' : item.type === 'todo' ? '마트 장보기, 데이트 등 개인 일정' : '메모를 작성하세요'}/></div><button className="block-delete" onClick={() => deleteBlock(page.id, item.id)} aria-label="블록 삭제"><Trash2 size={14}/></button>
          {item.type !== 'heading' && <div className="personal-block-fields"><label>카테고리<input list="personal-categories" value={item.category ?? ''} placeholder="개인 · 장보기 · 약속" onChange={event => updateBlock(page.id, item.id, { category: event.target.value })}/></label><label>날짜 태그<input type="date" value={item.date ?? ''} onChange={event => updateBlock(page.id, item.id, { date: event.target.value })}/></label></div>}
          {item.type === 'todo' && <><div className="personal-status-options" role="group" aria-label="체크리스트 상태"><button className={status === 'done' ? 'active' : ''} onClick={() => setStatus(page.id, item, 'done')}><Check size={13}/> 완료</button><button className={status === 'open' ? 'active' : ''} onClick={() => setStatus(page.id, item, 'open')}>미완료</button><button className={status === 'postponed' ? 'active' : ''} onClick={() => setStatus(page.id, item, 'postponed')}>연기</button></div>{status === 'postponed' && <label className="personal-move-date">옮길 날짜<input type="date" value={item.postponedTo ?? item.date ?? selectedDate} onChange={event => updateBlock(page.id, item.id, { postponedTo: event.target.value })}/></label>}</>}
        </div>; })}</div><datalist id="personal-categories"><option value="개인"/><option value="장보기"/><option value="약속"/><option value="데이트"/><option value="가족"/><option value="기타"/></datalist>
        <div className="notion-add-block"><button onClick={() => addBlock('heading')}><Heading1 size={15}/> 제목</button><button onClick={() => addBlock('text')}><Text size={15}/> 메모</button><button onClick={() => addBlock('todo', selectedDate)}><ListChecks size={15}/> 체크리스트</button></div></Card> : <Empty>새 페이지를 만들어 기록을 시작하세요.</Empty>}
    </div>}
    <Card className="notion-data-note"><div><span className="card-label">PLAN ↔ SCHEDULE</span><h3>학습과 생활 일정을 한 흐름으로</h3><p>Plan에는 학습 목표와 공부 기록을 두고, 일정에는 개인 메모와 약속을 날짜별로 정리합니다. 체크리스트 상태와 연기한 날짜는 Today에도 연결됩니다.</p></div><div><span>{data.monthlyPlans.filter(item => item.month === toDateKey().slice(0, 7)).length} 월간 목표</span><span>{data.scores.length} 실모 기록</span><span>{datedBlocks.filter(item => item.block.type === 'todo').length} 개인 일정</span></div></Card>
  </div>;
}
