import { archiveAllEntries, archiveApi, type ArchiveEntry, type CoreRule } from '../lib/archiveApi';
import { useEffect, useState } from 'react';
import type { AppData, Resource, Subject } from '../types';
import { loadCloudflareConfig } from '../lib/cloudflare';
import { toDateKey, uid } from '../lib/date';
import { emptyDay } from '../lib/planGraph';
import { Card } from '../components/Ui';
import { SUBJECTS } from '../data/config';
async function request(path:string,options:RequestInit={}) {const c=loadCloudflareConfig();const response=await fetch(`${c.url.replace(/\/$/,'')}/api/library${path}`,{...options,headers:{Authorization:`Bearer ${c.token}`,...options.headers}});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||'자료실 요청 실패');}return response;}
export default function ResourceLibrary({data,update}:{data:AppData;update:(fn:(v:AppData)=>AppData)=>void}) {
 const [tab,setTab]=useState<'mine'|'official'>('mine'),[catalog,setCatalog]=useState<Resource[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pdf,setPdf]=useState('');
 const [name,setName]=useState(''),[source,setSource]=useState(''),[subject,setSubject]=useState<Subject>('수학'),[date,setDate]=useState(toDateKey()),[question,setQuestion]=useState('');
 const [search,setSearch]=useState(''),[examType,setExamType]=useState(''),[year,setYear]=useState(''),[month,setMonth]=useState(''),[documentType,setDocumentType]=useState('');
 const [entries,setEntries]=useState<ArchiveEntry[]>([]),[rules,setRules]=useState<CoreRule[]>([]);
 const [linkType,setLinkType]=useState('learning_archive'),[linkId,setLinkId]=useState('');
 const task=async (fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'자료실 오류');}finally{setBusy(false);}};
 useEffect(()=>{void task(async()=>{setCatalog((await (await request('/catalog')).json()).resources);});},[]);
 useEffect(()=>{Promise.all([archiveAllEntries(),archiveApi<{rules:CoreRule[]}>('/api/archive/rules')]).then(([e,r])=>{setEntries(e);setRules(r.rules);}).catch(()=>{});},[]);
 useEffect(()=>()=>{if(pdf)URL.revokeObjectURL(pdf);},[pdf]);
 const patch=(id:string,values:Partial<Resource>)=>update(v=>({...v,resources:v.resources.map(r=>r.id===id?{...r,...values}:r)}));
 const add=(r:Resource)=>update(v=>({...v,resources:[...v.resources,{...r,id:uid(),officialId:r.id,status:'미시작'}]}));
 const filtered=(tab==='mine'?data.resources:catalog).filter(r=>(!search||`${r.name} ${r.subject} ${r.group}`.includes(search))&&(!examType||r.examType===examType)&&(!year||String(r.examYear)===year)&&(!month||String(r.examMonth)===month)&&(!documentType||r.documentType===documentType));
 return <Card><h2>자료실 · Library</h2><div className="filter-tabs"><button className={tab==='mine'?'active':''} onClick={()=>setTab('mine')}>내 자료실</button><button className={tab==='official'?'active':''} onClick={()=>setTab('official')}>공용 자료실</button></div><div className="form-grid two"><input aria-label="자료 검색" placeholder="자료명 · 과목 검색" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="시험 종류" value={examType} onChange={e=>setExamType(e.target.value)}><option value="">모든 시험</option>{['학력평가','모의평가','수능'].map(t=><option key={t}>{t}</option>)}</select><input aria-label="학년도" placeholder="학년도" value={year} onChange={e=>setYear(e.target.value)}/><input aria-label="시험 월" placeholder="월" value={month} onChange={e=>setMonth(e.target.value)}/><select aria-label="문서 종류" value={documentType} onChange={e=>setDocumentType(e.target.value)}><option value="">모든 문서</option>{['문제지','정답','해설'].map(t=><option key={t}>{t}</option>)}</select></div>
 {tab==='official'&&<p><a href="https://www.ebsi.co.kr/ebs/xip/xipc/previousPaperList.ebs" target="_blank" rel="noreferrer">EBSi 공식 기출문제 · 학평 / 모평 / 수능</a> · 공식 출처에서 PDF를 내려받아 내 자료실에 등록할 수 있습니다.</p>}
 {error&&<p role="alert">{error}</p>}
 <div className="resource-grid">{filtered.map(r=>{const sessions=data.sessions.filter(s=>s.resourceId===r.id),seconds=sessions.reduce((n,s)=>n+s.seconds,0),wrongs=data.wrongAnswerDrills.filter(w=>w.resourceId===r.id);return <article className="card" key={r.id}><h3>{r.name}</h3><p>{r.subject} · {r.examYear || ''} {r.examType || r.group} {r.examMonth ? `${r.examMonth}월`:''} {r.documentType || ''}</p>{r.sourceUrl&&<a href={r.sourceUrl} target="_blank" rel="noreferrer">공식 출처 / 자료 링크</a>}{tab==='official'?<button disabled={busy||data.resources.some(x=>x.officialId===r.id)} onClick={()=>add(r)}>내 자료실에 추가</button>:<><select aria-label={`${r.name} 학습 상태`} value={r.status ?? '미시작'} onChange={e=>patch(r.id,{status:e.target.value})}>{['미시작','진행 중','풀이 완료','오답 분석 중','복기 완료'].map(s=><option key={s}>{s}</option>)}</select><p>{Math.floor(seconds/60)}분 · 오답 {wrongs.length} · Archive {(r.links ?? []).filter(l=>l.targetType==='learning_archive').length} · Core Rule {(r.links ?? []).filter(l=>l.targetType==='core_rule').length}</p>{sessions.length>0&&<small>첫 학습 {[...sessions].sort((a,b)=>a.date.localeCompare(b.date))[0].date} · 최근 학습 {[...sessions].sort((a,b)=>b.date.localeCompare(a.date))[0].date}</small>}<div className="library-actions">{r.fileId&&<button disabled={busy} onClick={()=>void task(async()=>{const response=await request(`/files?id=${encodeURIComponent(r.fileId!)}`);setPdf(URL.createObjectURL(await response.blob()));})}>PDF 열기</button>}<button onClick={()=>update(v=>{const entry=v.calendar[date] ?? emptyDay(date);return {...v,calendar:{...v.calendar,[date]:{...entry,plans:[...(entry.plans ?? []),{id:uid(),subject:r.subject,title:r.name,detail:'',quantity:'',done:false,resourceId:r.id}]}}};})}>선택 날짜 계획에 추가</button><button disabled={!question.trim()} onClick={()=>{update(v=>({...v,wrongAnswerDrills:[{id:uid(),date,subject:r.subject,source:r.name,question:question.trim(),resourceId:r.id,wrongJudgment:'',missedCue:'',correction:'',transfer:''},...v.wrongAnswerDrills]}));setQuestion('');}}>오답 생성</button><button disabled={!linkId.trim()} onClick={()=>patch(r.id,{links:[...(r.links ?? []).filter(l=>!(l.targetType===linkType&&l.targetId===linkId.trim())),{targetType:linkType,targetId:linkId.trim()},...(linkType==='learning_archive'?(entries.find(e=>e.id===linkId)?.coreRules ?? []).map(rule=>({targetType:'core_rule',targetId:rule.id})):[])]})}>기록 연결</button></div></> }</article>})}</div>
 {tab==='mine'&&<><div className="form-grid two"><label>계획 / 오답 날짜<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>오답 문항번호<input value={question} onChange={e=>setQuestion(e.target.value)}/></label><select aria-label="연결 기록 종류" value={linkType} onChange={e=>{setLinkType(e.target.value);setLinkId('');}}>{['learning_archive','core_rule','mock_exam'].map(t=><option key={t}>{t}</option>)}</select><select aria-label="연결할 기록" value={linkId} onChange={e=>setLinkId(e.target.value)}><option value="">연결할 기록 선택</option>{(linkType==='learning_archive'?entries:linkType==='core_rule'?rules:data.scores.map(s=>({id:s.id,title:s.name}))).map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></div><p>생성한 오답은 Wrong Answer에서 판단·근거·수정 내용을 작성하세요.</p></>}
 <details><summary>{tab==='official'?'공용 공식 자료 등록 (관리자)':'개인 PDF / 링크 추가'}</summary><form className="form-grid two" onSubmit={e=>{e.preventDefault();void task(async()=>{const r:Resource={id:uid(),subject,group:examType,name:name.trim(),sourceUrl:source||undefined,total:1,done:0,status:'미시작',examType:examType||undefined,examYear:Number(year)||undefined,examMonth:Number(month)||undefined,documentType:documentType||undefined};if(tab==='official'){await request('/catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)});setCatalog((await (await request('/catalog')).json()).resources);}else update(v=>({...v,resources:[...v.resources,r]}));setName('');setSource('');});}}><input required placeholder="자료명" value={name} onChange={e=>setName(e.target.value)}/><select value={subject} onChange={e=>setSubject(e.target.value as Subject)}>{SUBJECTS.map(s=><option key={s}>{s}</option>)}</select><input type="url" required={tab==='official'} placeholder="https:// 공식 출처 / 자료 링크" value={source} onChange={e=>setSource(e.target.value)}/><button className="button" disabled={busy}>링크 등록</button>{tab==='mine'&&<label>개인 PDF (20MB 이하)<input type="file" accept="application/pdf" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(!file)return;void task(async()=>{if(file.size>20*1024*1024)throw new Error('PDF는 20MB 이하여야 합니다.');const result=await (await request(`/files?name=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':'application/pdf'},body:file})).json();update(v=>({...v,resources:[...v.resources,{id:uid(),subject,group:'개인 PDF',name:name.trim()||file.name,total:1,done:0,fileId:result.id,status:'미시작'}]}));});e.target.value='';}}/></label>}</form></details>{pdf&&<div><button onClick={()=>setPdf('')}>PDF 닫기</button><iframe title="개인 PDF" className="library-pdf" src={pdf}/></div>}
 </Card>;
}
