import { useMemo, useState } from 'react';
import { Brain, CheckCircle2, Crosshair, FlaskConical, Gauge, Layers3, Sparkles, Target, Zap } from 'lucide-react';
import type { AppData, JournalEntry, PlaireEntry, Subject, TrinityEntry } from '../types';
import { SUBJECTS } from '../data/config';
import { Card, Empty, Field, PageHeader, SaveButton, TextArea } from '../components/Ui';
import { toDateKey, uid, weekStartKey } from '../lib/date';
import WeeklyDrill from './WeeklyDrill';
import ScoreTracker from './ScoreTracker';

const blankJournal = (date: string): JournalEntry => ({ date, studied: '', wins: '', blocked: '', cause: '', hypothesis: '', action: '', event: '' });
const blankPlaire = (date: string): PlaireEntry => ({ date, record: '', criterion: '', wrongJudgment: '', lens: '', focus: '', simulation: '', workingMemory: '', automatic: '', conscious: '', transfer: '', bottleneck: '', nextAction: '', levels: { criterion: 5, immersion: 5, embodiment: 5 } });
const endOfWeek = (week: string) => { const d = new Date(`${week}T00:00:00`); d.setDate(d.getDate() + 6); return toDateKey(d); };
const formatMinutes = (seconds: number) => { const m = Math.round(seconds / 60); const h = Math.floor(m / 60); return h ? `${h}시간 ${m % 60 ? `${m % 60}분` : ''}` : `${m}분`; };

export default function ReviewPage({ data, update }: { data: AppData; update: (fn: (value: AppData) => AppData) => void }) {
  const [date, setDate] = useState(toDateKey()); const [view, setView] = useState<'review' | 'drill' | 'mock'>('review');
  const [journal, setJournal] = useState(data.journals[date] ?? blankJournal(date)); const [plaire, setPlaire] = useState(data.plaire[date] ?? blankPlaire(date));
  const [analysisSubject, setAnalysisSubject] = useState<'국어' | '수학'>('국어'); const [analysisFields, setAnalysisFields] = useState<Record<string, string>>({});
  const context = useMemo(() => {
    const plans = data.calendar[date]?.plans ?? []; const goals = data.weeklyCapabilityGoals.filter((item) => item.weekStart <= date && endOfWeek(item.weekStart) >= date); const scores = data.scores.filter((item) => item.date === date); const drills = data.wrongAnswerDrills.filter((item) => item.date === date || scores.some((score) => score.id === item.scoreId)); const sessions = data.sessions.filter((item) => item.date === date); const seconds = sessions.reduce((sum, item) => sum + item.seconds, 0); return { plans, goals, scores, drills, seconds };
  }, [data, date]);
  const week = weekStartKey(new Date(`${date}T00:00:00`)); const weekSessions = data.sessions.filter((item) => item.date >= week && item.date <= endOfWeek(week)).reduce((sum, item) => sum + item.seconds, 0); const weekDrills = data.wrongAnswerDrills.filter((item) => item.date >= week && item.date <= endOfWeek(week));
  const setJournalField = (key: keyof JournalEntry, value: string) => setJournal({ ...journal, [key]: value });
  const setPlaireField = (key: keyof PlaireEntry, value: string) => setPlaire({ ...plaire, [key]: value });
  const saveReview = () => update((value) => ({ ...value, journals: { ...value.journals, [date]: { ...journal, date } }, plaire: { ...value.plaire, [date]: { ...plaire, date } } }));
  const saveAnalysis = () => { const entry: TrinityEntry = { id: uid(), date, subject: analysisSubject, mode: analysisSubject, fields: analysisFields }; update((value) => ({ ...value, trinity: [entry, ...value.trinity] })); setAnalysisFields({}); };
  const defs = analysisSubject === '국어' ? [['diagnosis','현재 진단'],['representation','표상: 구조가 어디서 무너졌는가?'],['mapping','매핑: 근거와 선지의 대응'],['action','다음 실전 행동']] : [['problem','문제'],['condition','핵심 조건'],['necessary','필요·충분조건'],['action','실전 행동']];
  return <div><PageHeader eyebrow="REVIEW" title="오늘의 Review" description="기록을 남기는 곳이 아니라, 실패를 다음 행동으로 바꾸는 곳입니다." action={<input className="date-input" type="date" value={date} onChange={(e) => { const next = e.target.value; setDate(next); setJournal(data.journals[next] ?? blankJournal(next)); setPlaire(data.plaire[next] ?? blankPlaire(next)); }}/>} />
    <div className="review-tabs unified"><button className={view === 'review' ? 'active' : ''} onClick={() => setView('review')}>오늘 Review</button><button className={view === 'drill' ? 'active' : ''} onClick={() => setView('drill')}>Drill</button><button className={view === 'mock' ? 'active' : ''} onClick={() => setView('mock')}>실모 분석</button></div>
    {view === 'review' ? <>
      <Card className="review-context"><div className="review-context-head"><div><span className="card-label">LEARNING LOOP</span><h2>{date.replaceAll('-', '.')} · 학습 연결</h2><p>오늘 한 일 → 막힌 지점 → 원인 → 교정 행동 → 다음 검증으로 이어집니다.</p></div><div className="review-context-metrics"><span><b>{formatMinutes(context.seconds)}</b><small>오늘 순공</small></span><span><b>{context.plans.filter((p) => p.done).length}/{context.plans.length}</b><small>계획 완료</small></span><span><b>{context.drills.length}</b><small>오답</small></span></div></div><div className="connection-flow"><section><span><Target size={14}/> 이번 주 능력</span>{context.goals.slice(0,2).map((g)=><small key={g.id}>{g.subject} · {g.ability}</small>)}{!context.goals.length&&<small>능력 목표 없음</small>}</section><section><span><CheckCircle2 size={14}/> 오늘 계획</span>{context.plans.slice(0,2).map((p)=><small key={p.id}>{p.subject} · {p.title}{p.done?' · 완료':''}</small>)}{!context.plans.length&&<small>계획 없음</small>}</section><section><span><Gauge size={14}/> 실모</span>{context.scores.slice(0,2).map((s)=><small key={s.id}>{s.name}</small>)}{!context.scores.length&&<small>실모 없음</small>}</section><section><span><Crosshair size={14}/> 오답</span>{context.drills.slice(0,2).map((d)=><small key={d.id}>{d.subject} · {d.question||d.source}</small>)}{!context.drills.length&&<small>오답 없음</small>}</section></div></Card>
      <Card className="weekly-auto-review"><div className="weekly-auto-review-head"><Sparkles size={18}/><div><span className="card-label">WEEKLY SIGNAL</span><h2>이번 주는 무엇이 바뀌었나</h2><p>주간 기록을 다음 행동으로 압축합니다.</p></div></div><div className="weekly-review-grid"><section><b>순공</b><strong>{formatMinutes(weekSessions)}</strong><small>시간은 결과의 원인이 아니라 실행량의 보조 지표</small></section><section><b>오답</b><strong>{weekDrills.length}개</strong><small>가장 많이 반복된 병목은 {weekDrills.length ? Object.entries(weekDrills.reduce<Record<string,number>>((a,d)=>({...a,[d.bottleneck??'미분류']:(a[d.bottleneck??'미분류']??0)+1}),{})).sort((a,b)=>b[1]-a[1])[0]?.[0] : '기록 대기'}</small></section><section><b>능력 목표</b><strong>{context.goals[0]?.ability ?? '설정 필요'}</strong><small>이번 주 성공 기준을 오늘 행동으로 번역</small></section><section><b>다음 검증</b><strong>{plaire.nextAction || journal.action || '아직 없음'}</strong><small>Review 저장 후 다음 Drill로 연결</small></section></div></Card>
      <div className="review-flow-grid"><Card><div className="review-stage"><span>01</span><div><b>무엇을 했는가?</b><small>사실만 기록</small></div></div><Field label="오늘 공부한 것"><TextArea value={journal.studied} onChange={(v)=>setJournalField('studied',v)} placeholder="과목 · 범위 · 수행량"/></Field><Field label="잘된 행동"><TextArea value={journal.wins} onChange={(v)=>setJournalField('wins',v)} placeholder="다음에도 재현하고 싶은 행동"/></Field><Field label="어디서 막혔는가?"><TextArea value={journal.blocked} onChange={(v)=>setJournalField('blocked',v)} placeholder="어느 순간, 어떤 조건에서 막혔는가"/></Field></Card><Card><div className="review-stage"><span>02</span><div><b>왜 실패했는가?</b><small>원인을 분류하고 한 단계 더 파고들기</small></div></div><Field label="원인"><TextArea value={journal.cause} onChange={(v)=>setJournalField('cause',v)} placeholder="개념 부족 · 조건 해석 · 표상 · 매핑 · 계산 · 시간 · 멘탈 등"/></Field><Field label="검증할 가설"><TextArea value={journal.hypothesis} onChange={(v)=>setJournalField('hypothesis',v)} placeholder="내일 관찰 가능한 가설"/></Field><Field label="현재 병목"><TextArea value={plaire.bottleneck} onChange={(v)=>setPlaireField('bottleneck',v)} placeholder="현재 성장을 가장 제한하는 한 지점"/></Field></Card><Card><div className="review-stage"><span>03</span><div><b>다음 행동은?</b><small>관찰 가능한 최소 행동</small></div></div><Field label="교정 행동"><TextArea value={journal.action} onChange={(v)=>{setJournalField('action',v);setPlaireField('nextAction',v)}} placeholder="다음 문제에서 먼저 할 한 가지 행동"/></Field><Field label="검증 방법"><TextArea value={plaire.transfer} onChange={(v)=>setPlaireField('transfer',v)} placeholder="몇 문제·어떤 조건에서 다시 재현할 것인가"/></Field><Field label="오늘의 사건"><TextArea value={journal.event} onChange={(v)=>setJournalField('event',v)} placeholder="학습에 영향을 준 외부 요인"/></Field></Card></div>
      <Card className="framework-review"><div className="framework-head"><div><span className="card-label">PLAIRE × TRINITY</span><h2>판단이 실제 행동으로 바뀌었는가?</h2></div><span className="framework-badge">기준 → 몰입 → 체화</span></div><div className="framework-grid"><Field label="기준 · 무엇을 먼저 판단할 것인가"><TextArea value={plaire.criterion} onChange={(v)=>setPlaireField('criterion',v)} placeholder="다음 문제에서 먼저 확인할 기준"/></Field><Field label="몰입 · 시험 중 유지되는가"><TextArea value={plaire.focus} onChange={(v)=>setPlaireField('focus',v)} placeholder="흐트러진 시점과 복귀 행동"/></Field><Field label="체화 · 자동으로 나왔는가"><TextArea value={plaire.automatic} onChange={(v)=>setPlaireField('automatic',v)} placeholder="의식하지 않아도 나온 행동"/></Field></div><div className="level-sliders">{([['criterion','기준'],['immersion','몰입'],['embodiment','체화']] as const).map(([key,label])=><Field key={key} label={`${label} · ${plaire.levels[key]}/10`}><input type="range" min="1" max="10" value={plaire.levels[key]} onChange={(e)=>setPlaire({...plaire,levels:{...plaire.levels,[key]:Number(e.target.value)}})}/></Field>)}</div></Card>
      <Card className="analysis-inline"><div className="analysis-inline-head"><div><span className="card-label">TRINITY ANALYSIS</span><h2>과목별 판단 분석</h2></div><div className="subject-tabs"><button className={analysisSubject==='국어'?'active':''} onClick={()=>{setAnalysisSubject('국어');setAnalysisFields({})}}>국어</button><button className={analysisSubject==='수학'?'active':''} onClick={()=>{setAnalysisSubject('수학');setAnalysisFields({})}}>수학</button></div></div><div className="form-grid two">{defs.map(([key,label])=><Field key={key} label={label}><TextArea value={analysisFields[key]??''} onChange={(v)=>setAnalysisFields({...analysisFields,[key]:v})}/></Field>)}</div><SaveButton onClick={saveAnalysis} label="과목 분석 저장"/></Card>
      <div className="sticky-save"><span>저장하면 Journal과 Plaire가 같은 날짜 기록으로 함께 갱신됩니다.</span><SaveButton onClick={saveReview} label="오늘 Review 저장"/></div>
    </> : view === 'drill' ? <WeeklyDrill data={data} update={update}/> : <ScoreTracker data={data} update={update}/>}</div>;
}
