import { useState } from 'react';
import { Plus, Trash2, X } from 'lucide-react';
import type { AppData, ScoreEntry, Subject } from '../types';
import { ERROR_TYPES, SUBJECTS } from '../data/config';
import { Card, Empty, Field, PageHeader, SaveButton, TextArea } from '../components/Ui';
import { toDateKey, uid } from '../lib/date';

const blank = (): ScoreEntry => ({ id: '', name: '', date: toDateKey(), subject: '국어', duration: 0, errorType: '조건 해석 실패', cause: '', nextAction: '' });
export default function ScoreTracker({ data, update }: { data: AppData; update: (fn: (value: AppData) => AppData) => void }) {
  const [open, setOpen] = useState(false); const [draft, setDraft] = useState(blank());
  const save = () => { update((value) => ({ ...value, scores: [{ ...draft, id: uid() }, ...value.scores] })); setDraft(blank()); setOpen(false); };
  const remove = (id: string) => update((value) => ({ ...value, scores: value.scores.filter((x) => x.id !== id) }));
  return <div><PageHeader eyebrow="SCORE TRACKER" title="시험 측정 기록" description="점수와 함께 시간, 오답 원인, 다음 행동을 묶어 저장합니다." action={<button className="button primary" onClick={() => setOpen(true)}><Plus size={17} /> 시험 기록</button>} />
    {data.scores.length ? <div className="score-list">{data.scores.map((score) => <Card key={score.id} className="score-row"><div className="score-date"><span>{score.date.slice(5).replace('-', '.')}</span><small>{score.subject}</small></div><div className="score-main"><h3>{score.name}</h3><div className="score-values">{score.korean !== undefined && <span>국어 <b>{score.korean}</b></span>}{score.math !== undefined && <span>수학 <b>{score.math}</b></span>}{score.english !== undefined && <span>영어 <b>{score.english}</b></span>}<span>시간 <b>{score.duration}분</b></span></div><p><span className="error-chip">{score.errorType}</span>{score.nextAction || '다음 행동 미설정'}</p></div><button className="icon-button danger" onClick={() => remove(score.id)} aria-label="삭제"><Trash2 size={17} /></button></Card>)}</div> : <Empty>아직 시험 기록이 없습니다. 첫 실모를 측정값으로 남겨보세요.</Empty>}
    {open && <div className="modal-backdrop" onClick={() => setOpen(false)}><div className="modal" onClick={(e) => e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">NEW MEASUREMENT</p><h2>시험 기록</h2></div><button onClick={() => setOpen(false)}><X /></button></div><div className="form-grid two"><Field label="시험명"><input value={draft.name} onChange={(e) => setDraft({...draft, name:e.target.value})} /></Field><Field label="날짜"><input type="date" value={draft.date} onChange={(e) => setDraft({...draft, date:e.target.value})} /></Field><Field label="주 분석 과목"><select value={draft.subject} onChange={(e) => setDraft({...draft, subject:e.target.value as Subject})}>{SUBJECTS.map((s)=><option key={s}>{s}</option>)}</select></Field><Field label="시험 시간(분)"><input type="number" value={draft.duration} onChange={(e)=>setDraft({...draft,duration:Number(e.target.value)})}/></Field><Field label="국어 점수"><input type="number" onChange={(e)=>setDraft({...draft,korean:e.target.value?Number(e.target.value):undefined})}/></Field><Field label="수학 점수"><input type="number" onChange={(e)=>setDraft({...draft,math:e.target.value?Number(e.target.value):undefined})}/></Field><Field label="영어 점수"><input type="number" onChange={(e)=>setDraft({...draft,english:e.target.value?Number(e.target.value):undefined})}/></Field><Field label="대표 오답 원인"><select value={draft.errorType} onChange={(e)=>setDraft({...draft,errorType:e.target.value})}>{ERROR_TYPES.map((x)=><option key={x}>{x}</option>)}</select></Field><Field label="오답 원인"><TextArea value={draft.cause} onChange={(v)=>setDraft({...draft,cause:v})}/></Field><Field label="다음 행동"><TextArea value={draft.nextAction} onChange={(v)=>setDraft({...draft,nextAction:v})} placeholder="다음 시험에서 관찰 가능한 행동"/></Field></div><div className="modal-actions"><SaveButton onClick={save} label="시험 저장" /></div></div></div>}
  </div>;
}
