import { useEffect, useState } from 'react';
import { loadCloudflareConfig } from '../lib/cloudflare';
import type { TimerSession } from '../types';
import StudyRhythm from './StudyRhythm';
type Auth = {url:string;token:string;role?:string};
type Comment = {id:string;username:string;role:string;target:string;body:string;created_at:string};
type Document = {id:string;title:string;agency:string;year:number;subject:string};
async function api(auth:Auth,path:string,method='GET',body?:unknown){
 const response=await fetch(auth.url.replace(/\/+$/,'')+path,{method,headers:{Authorization:'Bearer '+auth.token,'Content-Type':'application/json'},cache:'no-store',...(body?{body:JSON.stringify(body)}:{})});
 const value=await response.json();if(!response.ok)throw Error(value.error||'요청 실패');return value;
}
const message=(e:unknown)=>e instanceof Error?e.message:'요청 실패';
function Comments({auth,write=false}:{auth:Auth;write?:boolean}){
 const [items,setItems]=useState<Comment[]>([]),[body,setBody]=useState(''),[target,setTarget]=useState('주간 총평'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const refresh=()=>api(auth,'/api/support/comments').then(v=>setItems(v.comments)).catch(e=>setError(message(e)));
 useEffect(()=>{void refresh();},[auth.token]);
 return <section><h2>{write?'첨언 · 학습량 평가':'선생님 · 학부모 의견'}</h2><button className="button" onClick={refresh}>의견 새로고침</button>{write&&<form className="team-panel" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api(auth,'/api/support/comments','POST',{body,target});setBody('');await refresh();}catch(e){setError(message(e));}finally{setBusy(false);}}}><label>대상 기록·주차<input required maxLength={200} value={target} onChange={e=>setTarget(e.target.value)}/></label><label>의견<textarea required maxLength={4000} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="button primary" disabled={busy}>의견 저장</button></form>}{error&&<p className="team-error" role="alert">{error}</p>}{items.map(c=><article className="team-record" key={c.id}><b>{c.username} · {c.role==='tutor'?'선생님':'학부모'} · {c.target}</b><p>{c.body}</p><small>{new Date(c.created_at).toLocaleString('ko-KR')}</small></article>)}{!items.length&&<p>아직 의견이 없습니다.</p>}</section>;
}
export function ExamArchive({auth=loadCloudflareConfig(),owner=true}:{auth?:Auth;owner?:boolean}){
 const [docs,setDocs]=useState<Document[]>([]),[filter,setFilter]=useState(''),[error,setError]=useState(''),[pdf,setPdf]=useState(''),[busy,setBusy]=useState(false);
 const [draft,setDraft]=useState({title:'',agency:'평가원',year:new Date().getFullYear(),subject:'수학',object_key:''});
 const refresh=()=>api(auth,'/api/exams').then(v=>setDocs(v.documents)).catch(e=>setError(message(e)));
 useEffect(()=>{void refresh();},[auth.token]);
 const open=async(id:string)=>{setBusy(true);setError('');try{const v=await api(auth,'/api/exams/'+id);if(typeof v.path!=='string'||!v.path.startsWith('exams/'))throw Error('PDF 경로가 올바르지 않습니다.');const base=(import.meta.env.BASE_URL||'/').replace(/\/?$/,'/'),root=new URL(base+'exams/',window.location.origin),target=new URL(base+v.path,window.location.origin);if(target.origin!==root.origin||!target.pathname.startsWith(root.pathname))throw Error('PDF 경로가 올바르지 않습니다.');const check=await fetch(target.href,{method:'HEAD',cache:'no-store'});if(!check.ok||!(check.headers.get('content-type')||'').toLowerCase().includes('pdf'))throw Error('public/exams/에 PDF가 없거나 아직 배포되지 않았습니다.');setPdf(target.href);}catch(e){setError(message(e));}finally{setBusy(false);}};
 return <section className="team-panel"><h2>기출 PDF 자료실</h2><p>평가원 · 교육청 · 사관학교 / PDF를 프로젝트의 public/exams/에 올린 뒤 목록에 등록하세요.</p><p className="team-error">주의: 이 방식은 무료이지만 PDF 주소를 아는 사람은 로그인 없이 파일을 열 수 있습니다. 개인 기록은 이 폴더에 올리지 마세요.</p><input aria-label="자료 검색" placeholder="기관·연도·과목·시험명 검색" value={filter} onChange={e=>setFilter(e.target.value)}/><button className="button" onClick={refresh}>목록 새로고침</button>
 {owner&&<details><summary>자료 등록 양식</summary><form className="team-panel" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api(auth,'/api/exams','POST',draft);setDraft({...draft,title:'',object_key:''});await refresh();}catch(e){setError(message(e));}finally{setBusy(false);}}}><label>시험명<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>기관<select value={draft.agency} onChange={e=>setDraft({...draft,agency:e.target.value})}>{['평가원','교육청','사관학교'].map(v=><option key={v}>{v}</option>)}</select></label><label>연도<input type="number" min="1980" max="2100" value={draft.year} onChange={e=>setDraft({...draft,year:Number(e.target.value)})}/></label><label>과목<select value={draft.subject} onChange={e=>setDraft({...draft,subject:e.target.value})}>{['국어','수학','영어','탐구'].map(v=><option key={v}>{v}</option>)}</select></label><label>public/exams/ 아래 경로<input required placeholder="2026/kice/math.pdf" value={draft.object_key} onChange={e=>setDraft({...draft,object_key:e.target.value})}/></label><button className="button primary" disabled={busy}>목록 등록</button></form></details>}
 {error&&<p className="team-error" role="alert">{error}</p>}{docs.filter(d=>[d.title,d.agency,d.year,d.subject].join(' ').includes(filter)).map(d=><article className="team-record" key={d.id}><b>{d.year} · {d.agency} · {d.subject} · {d.title}</b><button className="button" disabled={busy} onClick={()=>open(d.id)}>PDF 열기</button></article>)}{!docs.length&&<p>등록된 PDF가 없습니다.</p>}
 {pdf&&<><a href={pdf} target="_blank" rel="noreferrer">PDF 새 탭에서 열기</a><button className="button" onClick={()=>setPdf('')}>닫기</button><iframe title="기출 PDF" src={pdf} style={{width:'100%',height:'75vh'}}/></>}</section>;
}
export function SupportOwner(){
 const auth=loadCloudflareConfig();const [accounts,setAccounts]=useState<{id:string;username:string;role:string;active:number}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [draft,setDraft]=useState({username:'',password:'',role:'tutor'});
 const refresh=()=>api(auth,'/api/support/accounts').then(v=>setAccounts(v.accounts)).catch(e=>setError(message(e)));
 useEffect(()=>{void refresh();},[]);
 return <div className="team-panel"><h1>선생님 · 학부모 공유 관리</h1><p>서버에 마지막으로 저장한 학습 기록을 공유합니다. 먼저 ‘데이터 및 설정’에서 Cloudflare 저장을 완료하세요.</p><p>수학 선생님에게는 수학 구조화 기록, 학부모에게는 진도·학습량을 공유합니다. 개인 Notion·저널·Plaire 원문은 공유하지 않습니다.</p><form className="team-panel" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api(auth,'/api/support/accounts','POST',draft);setDraft({...draft,username:'',password:''});await refresh();}catch(e){setError(message(e));}finally{setBusy(false);}}}><label>역할<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="tutor">수학 선생님</option><option value="parent">학부모</option></select></label><label>아이디<input required value={draft.username} maxLength={40} onChange={e=>setDraft({...draft,username:e.target.value})}/></label><label>전용 비밀번호 (12자 이상)<input required type="password" minLength={12} maxLength={256} value={draft.password} onChange={e=>setDraft({...draft,password:e.target.value})}/></label><button className="button primary" disabled={busy}>공유 계정 생성</button></form><p>계정 생성 후 아이디·비밀번호·Worker URL을 해당 사람에게 직접 전달하세요. Cloudflare API 토큰은 전달하지 마세요.</p><div className="team-tools"><a href="?portal=tutor">선생님 로그인 창</a><a href="?portal=parent">학부모 로그인 창</a></div>{error&&<p className="team-error">{error}</p>}{accounts.map(a=><div className="team-record" key={a.id}>{a.username} · {a.role} · {a.active?'접근 허용':'차단됨'} {a.active===1&&<button className="button" onClick={async()=>{if(!window.confirm('이 계정의 접근을 차단할까요?'))return;try{await api(auth,'/api/support/accounts','PUT',{id:a.id});await refresh();}catch(e){setError(message(e));}}}>접근 차단</button>}</div>)}<Comments auth={auth}/></div>;
}
export default function SupportPortal({role}:{role:'tutor'|'parent'}){
 const key='trinity-support:'+role;
 const [auth,setAuth]=useState<Auth|null>(()=>{try{return JSON.parse(sessionStorage.getItem(key)||'null');}catch{return null;}});
 const [url,setUrl]=useState(auth?.url??'https://trinity-os-sync.khk090525.workers.dev'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[payload,setPayload]=useState<any>(null);
 const refresh=async()=>{if(!auth)return;setError('');try{setPayload(await api(auth,'/api/support/data'));}catch(e){setPayload(null);setError(message(e));}};
 useEffect(()=>{void refresh();},[auth?.token]);
 const logout=async()=>{if(auth)try{await api(auth,'/api/support/logout','POST');}catch{}sessionStorage.removeItem(key);setAuth(null);setPayload(null);};
 const labels:Record<string,string>={resources:'교재 진도',plans:'날짜별 계획',goals:'주간 능력 목표',daily:'Daily Drill',scores:'실모 점수',wrong:'수학 오답',monthly:'월간 목표',analysis:'기존 수학 분석',routine:'학습 루틴',checklist:'목표 체크리스트'};
 const fields:Record<string,string>={subject:'과목',name:'이름',title:'제목',date:'날짜',total:'전체',done:'완료',quantity:'목표량',ability:'능력',weekStart:'주 시작',month:'월',objective:'목표',strategy:'전략',successCriterion:'성공 기준',evidence:'증거',drillDesign:'훈련 설계',action:'실행',reflection:'회고',minutes:'분',math:'수학',korean:'국어',english:'영어',source:'출처',question:'문항',wrongJudgment:'틀린 판단',missedCue:'놓친 단서',correction:'교정 행동',transfer:'전이',review:'수학 분석',fields:'분석 기록',retries:'재검증',cause:'원인',nextAction:'다음 행동',errorType:'오류 유형',detail:'내용'};
 return <main className="team-page"><h1>{role==='tutor'?'수학 선생님':'학부모'} 전용</h1>{!auth?<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const v=await api({url,token:''},'/api/support/login','POST',{username,password,role});const next={url,token:v.token,role:v.role};sessionStorage.setItem(key,JSON.stringify(next));setAuth(next);setPassword('');}catch(e){setError(message(e));}finally{setBusy(false);}}}><label>Worker URL<input type="url" required value={url} onChange={e=>setUrl(e.target.value)}/></label><label>아이디<input required value={username} onChange={e=>setUsername(e.target.value)}/></label><label>비밀번호<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button primary" disabled={busy}>로그인</button><a href="?">학생 로그인으로</a></form>:<><div className="team-tools"><button className="button" onClick={refresh}>학습 기록 새로고침</button><button className="button" onClick={logout}>로그아웃</button></div><p>서버 저장 시각: {payload?.updatedAt?new Date(payload.updatedAt).toLocaleString('ko-KR'):'저장된 기록 없음'}</p>{payload?.data&&<><StudyRhythm sessions={payload.data.sessions as TimerSession[]}/><p>공유된 총 학습량: {Math.round(payload.data.sessions.reduce((n:number,s:TimerSession)=>n+s.seconds,0)/60)}분</p>{Object.entries(labels).map(([k,label])=><details key={k} className="team-record"><summary>{label} · {payload.data[k]?.length??0}개</summary>{(payload.data[k]??[]).map((item:any,i:number)=><article className="team-record" key={item.id??i}>{Object.entries(item).filter(([f])=>f!=='id').map(([f,v])=><p key={f}><b>{fields[f]??f}: </b>{typeof v==='boolean'?(v?'완료':'미완료'):typeof v==='object'?JSON.stringify(v,null,2):String(v)}</p>)}</article>)}</details>)}</>}<Comments auth={auth} write/>{role==='tutor'&&<ExamArchive auth={auth} owner={false}/>}</>}{error&&<p className="team-error" role="alert">{error}</p>}</main>;
}
