import { useMemo, useState } from 'react';
import { Check, ClipboardPenLine, RefreshCw, Sparkles, Target, Trash2 } from 'lucide-react';
import type { AppData, DrillBottleneck, DrillRetry, Subject, WeeklyCapabilityGoal, WrongAnswerDrill } from '../types';
import { SUBJECTS } from '../data/config';
import { Card, Empty, Field, PageHeader, SaveButton, TextArea } from '../components/Ui';
import { toDateKey, uid, weekStartKey } from '../lib/date';

const goalBlank = (weekStart: string): WeeklyCapabilityGoal => ({ id: '', weekStart, subject: '국어', ability: '', successCriterion: '', drillDesign: '', evidence: '', done: false });
const drillBlank = (): WrongAnswerDrill => ({ id: '', date: toDateKey(), subject: '국어', source: '', question: '', wrongJudgment: '', missedCue: '', correction: '', transfer: '', scoreId: undefined, capabilityGoalId: undefined, bottleneck: '전략·판단' });
const rangeEnd = (weekStart: string) => { const date = new Date(`${weekStart}T00:00:00`); date.setDate(date.getDate() + 6); return toDateKey(date); };
const labelWeek = (weekStart: string) => `${weekStart.replaceAll('-', '.')} ~ ${rangeEnd(weekStart).slice(5).replace('-', '.')}`;
const bottlenecks: DrillBottleneck[] = ['발문·해석', '개념 공백', '계산 실수', '시간 관리', '전략·판단', '기타'];
const retryPlan = (date: string): DrillRetry[] => [3, 7, 14].map((days) => { const value = new Date(`${date}T00:00:00`); value.setDate(value.getDate() + days); return { id: `${days}d` as DrillRetry['id'], label: `${days}일 후 재도전`, dueDate: toDateKey(value) }; });

export default function WeeklyDrill({ data, update }: { data: AppData; update: (fn: (value: AppData) => AppData) => void }) {
  const [weekStart, setWeekStart] = useState(weekStartKey()); const [goal, setGoal] = useState(goalBlank(weekStartKey())); const [drill, setDrill] = useState(drillBlank()); const [openGoal, setOpenGoal] = useState(false); const [openDrill, setOpenDrill] = useState(false);
  const goals = useMemo(() => data.weeklyCapabilityGoals.filter((item) => item.weekStart === weekStart), [data.weeklyCapabilityGoals, weekStart]);
  const drills = useMemo(() => data.wrongAnswerDrills.filter((item) => item.date >= weekStart && item.date <= rangeEnd(weekStart)), [data.wrongAnswerDrills, weekStart]);
  const weeklyPlans = useMemo(() => Object.values(data.calendar).filter((item) => item.date >= weekStart && item.date <= rangeEnd(weekStart)).flatMap((item) => item.plans ?? []), [data.calendar, weekStart]);
  const weeklySessions = useMemo(() => data.sessions.filter((item) => item.date >= weekStart && item.date <= rangeEnd(weekStart)), [data.sessions, weekStart]);
  const weeklyScores = useMemo(() => data.scores.filter((item) => item.date >= weekStart && item.date <= rangeEnd(weekStart)), [data.scores, weekStart]);
  const retryDue = useMemo(() => data.wrongAnswerDrills.flatMap((item) => (item.retries ?? []).filter((retry) => !retry.completedDate && retry.dueDate <= toDateKey()).map((retry) => ({ item, retry }))).sort((a, b) => a.retry.dueDate.localeCompare(b.retry.dueDate)), [data.wrongAnswerDrills]);
  const weeklyBottleneck = useMemo(() => { const counts = drills.reduce<Record<string, number>>((result, item) => ({ ...result, [item.bottleneck ?? '미분류']: (result[item.bottleneck ?? '미분류'] ?? 0) + 1 }), {}); return Object.entries(counts).sort((a, b) => b[1] - a[1])[0]; }, [drills]);
  const setWeek = (value: string) => { setWeekStart(value); setGoal(goalBlank(value)); };
  const saveGoal = () => { if (!goal.ability.trim() || !goal.successCriterion.trim()) return; update((value) => ({ ...value, weeklyCapabilityGoals: [...value.weeklyCapabilityGoals, { ...goal, id: uid(), weekStart }] })); setGoal(goalBlank(weekStart)); setOpenGoal(false); };
  const saveDrill = () => { if (!drill.source.trim() || !drill.wrongJudgment.trim()) return; update((value) => ({ ...value, wrongAnswerDrills: [{ ...drill, id: uid(), retries: retryPlan(drill.date) }, ...value.wrongAnswerDrills] })); setDrill(drillBlank()); setOpenDrill(false); };
  const deleteGoal = (id: string) => update((value) => ({ ...value, weeklyCapabilityGoals: value.weeklyCapabilityGoals.filter((item) => item.id !== id) }));
  const deleteDrill = (id: string) => update((value) => ({ ...value, wrongAnswerDrills: value.wrongAnswerDrills.filter((item) => item.id !== id) }));
  const toggleGoal = (id: string) => update((value) => ({ ...value, weeklyCapabilityGoals: value.weeklyCapabilityGoals.map((item) => item.id === id ? { ...item, done: !item.done } : item) }));
  const toggleRetry = (drillId: string, retryId: DrillRetry['id']) => update((value) => ({ ...value, wrongAnswerDrills: value.wrongAnswerDrills.map((item) => item.id !== drillId ? item : { ...item, retries: (item.retries ?? retryPlan(item.date)).map((retry) => retry.id === retryId ? { ...retry, completedDate: retry.completedDate ? undefined : toDateKey() } : retry) }) }));
  return <div><PageHeader eyebrow="PLAIRE WEEKLY DRILL" title="능력 목표 · 오답 Drill" description="이번 주에 끝낼 과제가 아니라, 재현할 능력과 그 능력을 검증할 오답 훈련을 설계합니다." action={<input className="date-input" type="date" value={weekStart} onChange={(event) => setWeek(event.target.value)} />} />
    <Card className="week-intent"><div><span className="card-label">THIS WEEK</span><h2>{labelWeek(weekStart)}</h2><p>기준을 만들고 → 실전에서 재현하고 → 오답으로 수정한 뒤 → 다음 문제로 전이합니다.</p></div><div className="week-intent-actions"><button className="button primary" onClick={() => setOpenGoal(!openGoal)}><Target size={16} /> 능력 목표</button><button className="button" onClick={() => setOpenDrill(!openDrill)}><ClipboardPenLine size={16} /> 오답 Drill</button></div></Card>
    <Card className="weekly-auto-review"><div className="weekly-auto-review-head"><Sparkles size={18} /><div><span className="card-label">AUTO WEEKLY REVIEW</span><h2>이번 주 기록 요약</h2><p>입력된 계획·실모·오답을 바탕으로 다음 주의 초점을 자동으로 정리합니다.</p></div></div><div className="weekly-review-grid"><section><b>실행</b><strong>{weeklyPlans.filter((item) => item.done).length} / {weeklyPlans.length}</strong><small>날짜별 계획 완료 · 순공 {Math.round(weeklySessions.reduce((sum, item) => sum + item.seconds, 0) / 60)}분</small></section><section><b>검증</b><strong>{weeklyScores.length}회</strong><small>실모 {weeklyScores.length}개 · 오답 Drill {drills.length}개</small></section><section><b>반복 병목</b><strong>{weeklyBottleneck ? weeklyBottleneck[0] : '기록 대기'}</strong><small>{weeklyBottleneck ? `${weeklyBottleneck[1]}회 기록됨` : '오답 Drill에서 원인을 분류하세요.'}</small></section><section><b>다음 주 제안</b><strong>{goals.find((item) => !item.done)?.ability ?? (weeklyBottleneck ? `${weeklyBottleneck[0]} 교정` : '능력 목표 설정')}</strong><small>{goals.find((item) => !item.done) ? '미완료 능력 목표를 다시 검증하세요.' : '병목을 하나 골라 성공 기준을 만드세요.'}</small></section></div></Card>
    {retryDue.length > 0 && <Card className="retry-due-card"><div className="weekly-auto-review-head"><RefreshCw size={18} /><div><span className="card-label">RETRY DUE</span><h2>지금 재현할 오답 {retryDue.length}개</h2><p>해설을 다시 보는 대신, 저장한 교정 행동을 먼저 적용해 보세요.</p></div></div><div className="retry-due-list">{retryDue.slice(0, 5).map(({ item, retry }) => <div key={`${item.id}-${retry.id}`}><span className={`subject-badge ${item.subject}`}>{item.subject}</span><b>{item.question || item.source}</b><small>{retry.label} · {retry.dueDate}</small><button className="button small" onClick={() => toggleRetry(item.id, retry.id)}><Check size={14} /> 재현 완료</button></div>)}</div></Card>}
    {openGoal && <Card className="weekly-form"><div className="weekly-form-title"><Target size={18} /><div><b>이번 주에 기를 능력</b><small>완료량이 아니라, 어떤 상황에서 어떤 행동을 할 수 있어야 하는지 적습니다.</small></div></div><div className="form-grid two"><Field label="과목"><select value={goal.subject} onChange={(event) => setGoal({ ...goal, subject: event.target.value as Subject })}>{SUBJECTS.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="기를 능력"><input value={goal.ability} onChange={(event) => setGoal({ ...goal, ability: event.target.value })} placeholder="예: 선지 간 정보의 연결을 표상하기" /></Field></div><Field label="성공 기준"><TextArea value={goal.successCriterion} onChange={(value) => setGoal({ ...goal, successCriterion: value })} placeholder="예: 비문학 3지문에서 근거와 선지를 2회 이상 명시적으로 매핑한다." /></Field><Field label="훈련 설계"><TextArea value={goal.drillDesign} onChange={(value) => setGoal({ ...goal, drillDesign: value })} placeholder="어떤 지문·문제에서, 어떤 조건으로 반복할지" /></Field><Field label="이번 주 증거"><TextArea value={goal.evidence} onChange={(value) => setGoal({ ...goal, evidence: value })} placeholder="성공·실패를 판정할 기록: 오답 번호, 타임스탬프, 재현 횟수 등" /></Field><div className="modal-actions"><SaveButton onClick={saveGoal} label="능력 목표 저장" /></div></Card>}
    {openDrill && <Card className="weekly-form"><div className="weekly-form-title"><ClipboardPenLine size={18} /><div><b>오답 Drill 기록</b><small>정답 해설이 아니라, 틀린 판단을 다음 문제에서 교정할 기준으로 변환합니다.</small></div></div><div className="form-grid two"><Field label="날짜"><input type="date" value={drill.date} onChange={(event) => setDrill({ ...drill, date: event.target.value })} /></Field><Field label="과목"><select value={drill.subject} onChange={(event) => setDrill({ ...drill, subject: event.target.value as Subject })}>{SUBJECTS.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="출처"><input value={drill.source} onChange={(event) => setDrill({ ...drill, source: event.target.value })} placeholder="예: 서바이벌 프로 8월" /></Field><Field label="문항 / 상황"><input value={drill.question} onChange={(event) => setDrill({ ...drill, question: event.target.value })} placeholder="예: 국어 비문학 12번 내용일치" /></Field><Field label="병목 분류"><select value={drill.bottleneck ?? '전략·판단'} onChange={(event) => setDrill({ ...drill, bottleneck: event.target.value as DrillBottleneck })}>{bottlenecks.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="연결할 실모 기록 · 선택"><select value={drill.scoreId ?? ''} onChange={(event) => setDrill({ ...drill, scoreId: event.target.value || undefined })}><option value="">연결 안 함</option>{data.scores.map((item) => <option key={item.id} value={item.id}>{item.date} · {item.name}</option>)}</select></Field><Field label="연결할 능력 목표 · 선택"><select value={drill.capabilityGoalId ?? ''} onChange={(event) => setDrill({ ...drill, capabilityGoalId: event.target.value || undefined })}><option value="">연결 안 함</option>{data.weeklyCapabilityGoals.filter((item) => item.subject === drill.subject).map((item) => <option key={item.id} value={item.id}>{labelWeek(item.weekStart)} · {item.ability}</option>)}</select></Field></div><Field label="내가 틀린 판단"><TextArea value={drill.wrongJudgment} onChange={(value) => setDrill({ ...drill, wrongJudgment: value })} placeholder="왜 그 선택이 맞다고 판단했는지" /></Field><Field label="놓친 단서"><TextArea value={drill.missedCue} onChange={(value) => setDrill({ ...drill, missedCue: value })} placeholder="지문·발문·조건 중 무엇을 놓쳤는지" /></Field><Field label="교정 행동"><TextArea value={drill.correction} onChange={(value) => setDrill({ ...drill, correction: value })} placeholder="다음번 이 상황에서 먼저 할 구체적인 행동" /></Field><Field label="전이 Drill"><TextArea value={drill.transfer} onChange={(value) => setDrill({ ...drill, transfer: value })} placeholder="어떤 유사 문제에서 몇 회 재현해 확인할지" /></Field><div className="modal-actions"><SaveButton onClick={saveDrill} label="오답 Drill 저장" /></div></Card>}
    <div className="section-title"><h2>이번 주 능력 목표</h2><span>{goals.filter((item) => item.done).length} / {goals.length} 검증 완료</span></div>{goals.length ? <div className="capability-grid">{goals.map((item) => <Card key={item.id} className={`capability-card ${item.done ? 'done' : ''}`}><div className="capability-head"><span className={`subject-badge ${item.subject}`}>{item.subject}</span><div><button className="goal-check" onClick={() => toggleGoal(item.id)}>{item.done ? <Check size={14} /> : '○'}</button><button className="goal-delete" onClick={() => deleteGoal(item.id)}><Trash2 size={14} /></button></div></div><h3>{item.ability}</h3><div><b>성공 기준</b><p>{item.successCriterion}</p></div><div><b>훈련 설계</b><p>{item.drillDesign || '미설정'}</p></div><div><b>증거</b><p>{item.evidence || '미설정'}</p></div></Card>)}</div> : <Empty>이번 주에 기를 능력을 하나 설정해 보세요.</Empty>}
    <div className="section-title"><h2>이번 주 오답 Drill</h2><span>{drills.length}개 기록</span></div>{drills.length ? <div className="drill-list">{drills.map((item) => { const score = data.scores.find((value) => value.id === item.scoreId); const linkedGoal = data.weeklyCapabilityGoals.find((value) => value.id === item.capabilityGoalId); return <Card key={item.id} className="drill-record"><div className="drill-head"><div><span className={`subject-badge ${item.subject}`}>{item.subject}</span><small>{item.date} · {item.source}</small><h3>{item.question || '문항 미입력'}</h3>{(score || linkedGoal) && <div className="record-links">{score && <span>실모 · {score.name}</span>}{linkedGoal && <span>능력 · {linkedGoal.ability}</span>}</div>}</div><button className="icon-button danger" onClick={() => deleteDrill(item.id)} aria-label="삭제"><Trash2 size={17} /></button></div><div className="drill-chain"><div><b>틀린 판단</b><p>{item.wrongJudgment}</p></div><div><b>놓친 단서</b><p>{item.missedCue || '미기록'}</p></div><div><b>교정 행동</b><p>{item.correction || '미기록'}</p></div><div><b>전이 Drill</b><p>{item.transfer || '미기록'}</p></div></div></Card>; })}</div> : <Empty>오답을 “다음 문제의 행동 기준”으로 바꿔 기록해 보세요.</Empty>}</div>;
}
