import { FormEvent, useEffect, useRef, useState } from 'react';
import { ArrowUp, MessageCircle, X } from 'lucide-react';
import type { DailyCoachContext } from '../lib/aiCoach';
import { requestCoachChat } from '../lib/aiCoach';

type Message = { role: 'user' | 'assistant'; content: string };
export default function CoachChat({ context, onClose }: { context: DailyCoachContext; onClose: () => void }) {
  const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [busy, setBusy] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { inputRef.current?.focus(); const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown); }, [onClose]);
  const send = async (event: FormEvent) => { event.preventDefault(); const content = input.trim(); if (!content || busy) return; const next = [...messages, { role: 'user' as const, content }].slice(-6); setMessages(next); setInput(''); setBusy(true); try { const reply = await requestCoachChat(context, next); setMessages((value) => [...value, { role: 'assistant' as const, content: reply.message }].slice(-6)); } catch (error) { setMessages((value) => [...value, { role: 'assistant' as const, content: error instanceof Error ? error.message : '지금은 상담을 연결할 수 없습니다.' }].slice(-6)); } finally { setBusy(false); } };
  return <div className="coach-sheet-backdrop" role="presentation" onPointerDown={onClose}><section className="coach-sheet" role="dialog" aria-modal="true" aria-labelledby="coach-chat-title" onPointerDown={(event) => event.stopPropagation()}><header><div><span className="card-label">AI STUDY COACH</span><h2 id="coach-chat-title">학습 상담</h2><p>오늘 기록을 바탕으로 짧고 구체적으로 답합니다.</p></div><button className="icon-button" aria-label="상담 닫기" onClick={onClose}><X size={18} /></button></header><div className="coach-messages" aria-live="polite">{messages.length ? messages.map((message, index) => <p className={message.role} key={`${message.role}-${index}`}>{message.content}</p>) : <div className="coach-start"><MessageCircle size={18} /><p>예: “지금 국어와 수학 중 무엇을 먼저 할까?”</p></div>}{busy && <p className="assistant loading">생각하고 있습니다…</p>}</div><form onSubmit={send}><input ref={inputRef} value={input} onChange={(event) => setInput(event.target.value)} maxLength={500} placeholder="학습 상황을 짧게 물어보세요" aria-label="AI 코치에게 질문" /><button className="button primary" type="submit" disabled={!input.trim() || busy} aria-label="질문 보내기"><ArrowUp size={17} /></button></form></section></div>;
}
