import test from 'node:test';
import assert from 'node:assert/strict';
import {calculateArenaScore} from '../src/lib/arenaScore.ts';

const now=new Date('2026-09-17T12:00:00Z');
const base=()=>({calendar:{},sessions:[],scores:[],weeklyCapabilityGoals:[],wrongAnswerDrills:[],dailyDrills:[],plaire:{},mockSchedule:[],journals:{},resources:[],goals:[],monthlyPlans:[],notionPages:[],routine:[],quotes:[],examDate:'',googleClientId:'',trinity:[]});
const li=(overrides={})=>({reviewSuccesses:0,reviewCompleted:0,drillSuccesses:0,drillCompleted:0,repeatedErrorsCurrent:0,repeatedErrorsPrevious:0,reviewScheduleCredits:0,reviewScheduleCompleted:0,...overrides});

test('Arena v2 is deterministic and capped at 1000',()=>{const data=base(),a=calculateArenaScore(data,now,li()),b=calculateArenaScore(data,now,li());assert.deepEqual(a,b);assert.equal(a.scoreVersion,2);assert.ok(a.total<=1000);assert.equal(a.total,Object.values(a.breakdown).reduce((x,y)=>x+y,0))});
test('one successful review cannot create full mastery',()=>{const score=calculateArenaScore(base(),now,li({reviewSuccesses:1,reviewCompleted:1}));assert.ok(score.breakdown.mastery<300);assert.ok(score.metrics.reviewSuccessRate<100)});
test('volume and record creation alone do not create a top score',()=>{const data=base();data.sessions=Array.from({length:40},(_,i)=>({id:String(i),date:'2026-09-17',subject:'수학',seconds:3600}));data.wrongAnswerDrills=Array.from({length:100},(_,i)=>({id:String(i),date:'2026-09-17',subject:'수학',source:'',question:'',wrongJudgment:'',missedCue:'',correction:'',transfer:'',retries:[]}));const score=calculateArenaScore(data,now,li({repeatedErrorsCurrent:100,repeatedErrorsPrevious:1}));assert.ok(score.total<700);assert.ok(score.breakdown.mastery<150)});
test('learning improvement beats study volume without evidence',()=>{const volume=base();volume.sessions=[{id:'a',date:'2026-09-17',subject:'수학',seconds:20*3600}];const improved=base();improved.calendar['2026-09-17']={date:'2026-09-17',study:'',minutes:0,exam:'',event:'',condition:3,reflection:'',plans:[{id:'p',subject:'수학',title:'x',detail:'',quantity:'',done:true}]};const a=calculateArenaScore(volume,now,li()),b=calculateArenaScore(improved,now,li({reviewSuccesses:5,reviewCompleted:5,drillSuccesses:5,drillCompleted:5,repeatedErrorsCurrent:1,repeatedErrorsPrevious:4,reviewScheduleCredits:5,reviewScheduleCompleted:5}));assert.ok(b.total>a.total)});
test('personal target fallback compares rates rather than raw hours',()=>{const make=(hours)=>{const d=base();for(let w=0;w<4;w++)d.sessions.push({id:`p${w}`,date:`2026-08-${24+w}`,subject:'수학',seconds:hours*3600});d.sessions.push({id:'now',date:'2026-09-17',subject:'수학',seconds:hours*3600});return d};assert.equal(calculateArenaScore(make(20),now).metrics.studyGoalRate,calculateArenaScore(make(40),now).metrics.studyGoalRate)});
