export type Subject = '국어' | '수학' | '영어' | '탐구';
export type CalendarPlan = { id: string; subject: Subject | '생활'; title: string; detail: string; quantity: string; done: boolean };
export type CalendarEntry = { date: string; study: string; minutes: number; exam: string; event: string; condition: number; reflection: string; plans?: CalendarPlan[] };
export type TimerSession = { id: string; date: string; subject: Subject; seconds: number; note?: string; startedAt?: string; endedAt?: string; segments?: { start: string; end: string; kind: 'focus' | 'break' }[]; focusDrops?: string[] };
export type MockScheduleItem = { id: string; label: string; start: string; end: string; kind: 'exam' | 'break' | 'admin'; subject?: Subject; questions?: number };
export type JournalEntry = { date: string; studied: string; wins: string; blocked: string; cause: string; hypothesis: string; action: string; event: string };
export type MockExamSubject = '국어' | '수학' | '영어';
export type MockExamReview = { score?: number; duration?: number; wrongQuestions: string; observation: string; improvement: string };
export type ScoreEntry = { id: string; name: string; date: string; subject: Subject; korean?: number; math?: number; english?: number; duration: number; errorType: string; cause: string; nextAction: string; reviews?: Partial<Record<MockExamSubject, MockExamReview>>; overallReview?: string };
export type Resource = { id: string; subject: Subject; group: string; name: string; total: number; done: number };
export type Goal = { id: string; subject: Subject; text: string; done: boolean };
export type WeeklyCapabilityGoal = { id: string; weekStart: string; subject: Subject; ability: string; successCriterion: string; drillDesign: string; evidence: string; done: boolean; feedbackId?: string };
export type DrillBottleneck = '발문·해석' | '개념 공백' | '계산 실수' | '시간 관리' | '전략·판단' | '기타';
export type DrillRetry = { id: '3d' | '7d' | '14d'; label: string; dueDate: string; completedDate?: string };
export type WrongAnswerDrill = { id: string; date: string; subject: Subject; source: string; question: string; wrongJudgment: string; missedCue: string; correction: string; transfer: string; scoreId?: string; capabilityGoalId?: string; bottleneck?: DrillBottleneck; retries?: DrillRetry[] };
export type DailyDrill = { id: string; date: string; subject: Subject; title: string; action: string; successCriterion: string; minutes: number; capabilityGoalId?: string; feedbackId?: string; done: boolean; reflection: string };
export type MonthlyPlan = { id: string; month: string; subject: Subject; title: string; objective: string; successCriterion: string; strategy: string; done: boolean };
export type NotionBlock = { id: string; type: 'heading' | 'text' | 'todo'; content: string; checked?: boolean };
export type NotionPage = { id: string; title: string; icon: string; createdAt: string; updatedAt: string; blocks: NotionBlock[] };
export type RoutineItem = { id: string; time: string; title: string; detail: string; subject: Subject | '생활' };
export type PlaireEntry = { date: string; record: string; criterion: string; wrongJudgment: string; lens: string; focus: string; simulation: string; workingMemory: string; automatic: string; conscious: string; transfer: string; bottleneck: string; nextAction: string; levels: { criterion: number; immersion: number; embodiment: number } };
export type TrinityEntry = { id: string; date: string; subject: Subject; mode: '국어' | '수학'; fields: Record<string, string> };
export type ArenaGroupType = 'university' | 'department' | 'custom';
export type ArenaVisibility = 'public' | 'private';
export type ArenaProfile = {
  userId?: number;
  nickname: string;
  grade: string;
  targetUniversity: string;
  targetDepartment: string;
  targetAdmissionType: string;
  studyGoal: string[];
  achievementLevel: string;
  profileImage?: string;
};
export type ArenaGroup = {
  id: string;
  name: string;
  type: ArenaGroupType;
  targetUniversity?: string;
  targetDepartment?: string;
  memberCount: number;
  visibility: ArenaVisibility;
  joined: boolean;
  owner: boolean;
  inviteCode?: string;
};
export type ArenaScoreBreakdown = {
  execution: number;
  problemSolving: number;
  consistency: number;
  growth: number;
};
export type ArenaScoreMetrics = {
  currentWeekSeconds: number;
  previousWeekSeconds: number;
  planExecutionRate: number;
  activeDays: number;
  streakDays: number;
  scoreChange: number;
  drillCompletionRate: number;
  completedTripleDrills: number;
  weaknessImprovementRate: number;
  growthRate: number;
  weakAreas: string[];
  nextActions: string[];
};
export type ArenaScore = {
  total: number;
  breakdown: ArenaScoreBreakdown;
  metrics: ArenaScoreMetrics;
  calculatedAt: string;
};
export type ArenaRankingEntry = {
  rank: number;
  userId: number;
  nickname: string;
  score: number;
  growthRate: number;
  targetUniversity: string;
  targetDepartment: string;
  isMe?: boolean;
};
export type ArenaSeason = { id: string; name: string; startsAt: string; endsAt: string; status: 'upcoming' | 'active' | 'ended' };
export type ArenaAchievement = { id: string; code: string; title: string; description: string; awardedAt: string };
export type ArenaRival = ArenaRankingEntry & { comparison?: { label: string; mine: number; rival: number; unit: string }[]; insight?: string };
export type ArenaBootstrap = {
  profile: ArenaProfile | null;
  groups: ArenaGroup[];
  ranking: ArenaRankingEntry[];
  rivals: ArenaRival[];
  achievements: ArenaAchievement[];
  season: ArenaSeason;
  latestScore: ArenaScore | null;
};
export type AppData = {
  calendar: Record<string, CalendarEntry>;
  sessions: TimerSession[];
  mockSchedule: MockScheduleItem[];
  journals: Record<string, JournalEntry>;
  scores: ScoreEntry[];
  resources: Resource[];
  goals: Goal[];
  weeklyCapabilityGoals: WeeklyCapabilityGoal[];
  wrongAnswerDrills: WrongAnswerDrill[];
  dailyDrills: DailyDrill[];
  monthlyPlans: MonthlyPlan[];
  notionPages: NotionPage[];
  routine: RoutineItem[];
  quotes: string[];
  examDate: string;
  googleClientId: string;
  plaire: Record<string, PlaireEntry>;
  trinity: TrinityEntry[];
};
