import { useCallback, useEffect, useRef, useState } from 'react';
import { Check, RotateCcw, X } from 'lucide-react';
import { archiveApi } from '../../lib/archiveApi';
import { useDialogFocus } from '../motion/useDialogFocus';

type ReviewItem={id:string;targetType:'wrong_answer'|'core_rule'|'drill'|'learning_item';targetId:string;subject:string;title:string;reason:string;scheduledAt:string;reviewedAt:string|null;result:string;previousResult:string|null;priority:number;notes:string;detail:Record<string,unknown>};
type Queue={overdue:ReviewItem[];today:ReviewItem[];upcoming:ReviewItem[];counts:{overdue:number;today:number;upcoming:number;due:number}};
const subject:Record<string,string>={korean:'국어',math:'수학',english:'영어'};
const labels:Record<ReviewItem['targetType'],string>={core_rule:'CORE RULE',wrong_answer:'WRONG ANSWER',learning_item:'LEARNING ARCHIVE',drill:'DRILL'};
const empty:Queue={overdue:[],today:[],upcoming:[],counts:{overdue:0,today:0,upcoming:0,due:0}};
const format=(value:string)=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value));

function ReviewDetail({item,onClose,onSaved}:{item:ReviewItem;onClose:()=>void;onSaved:()=>void}){
 const ref=useRef<HTMLElement>(null),[notes,setNotes]=useState(item.notes),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useDialogFocus(true,ref,onClose);
 const save=async(result:'success'|'fail')=>{if(busy)return;setBusy(true);setError('');try{await archiveApi(`/api/learning-intelligence/reviews/${encodeURIComponent(item.id)}`,'PATCH',{result,notes});onSaved();onClose();}catch(e){setError(e instanceof Error?e.message:'Review 결과를 저장하지 못했습니다.')}finally{setBusy(false)}};
 const d=item.detail;
 return <div className="sheet-backdrop" onClick={()=>!busy&&onClose()}><aside ref={ref} tabIndex={-1} className="detail-sheet review-detail" role="dialog" aria-modal="true" aria-labelledby="review-detail-title" onClick={event=>event.stopPropagation()}><header><div><span className="eyebrow">{labels[item.targetType]}</span><h2 id="review-detail-title">{item.title}</h2><p>{subject[item.subject]??item.subject} · {format(item.scheduledAt)}</p></div><button className="icon-button" disabled={busy} onClick={onClose} aria-label="닫기"><X/></button></header><div className="sheet-content review-detail-content">{item.targetType==='core_rule'&&<><section><b>Rule 내용</b><p>{String(d.content??item.reason)}</p></section><section><b>최근 실패</b><p>{Number((d.stats as Record<string,unknown> | undefined)?.failures7d??0)}회 · 최근 7일</p></section><section><b>Evidence</b><p>{Number((d.stats as Record<string,unknown> | undefined)?.evidenceCount??0)}개 근거가 연결되어 있습니다.</p></section></>}{item.targetType==='wrong_answer'&&<><section><b>문제</b><p>{String(d.source??'')} {String(d.question??'')}</p></section><section><b>잘못된 판단</b><p>{String(d.wrongJudgment??'')}</p></section><section><b>놓친 단서</b><p>{String(d.missedCue??'')}</p></section><section><b>교정 행동</b><p>{String(d.correction??item.reason)}</p></section></>}{item.targetType==='learning_item'&&<><section><b>자료 · 문항</b><p>{String(d.questionNumber??'문항 정보 없음')}</p></section><section><b>핵심 분석</b><p>{String(d.solutionFlow??d.bottleneck??d.memo??item.reason)}</p></section></>}{item.targetType==='drill'&&<><section><b>Drill</b><p>{item.title}</p></section><section><b>성공 기준</b><p>{String(d.successCriterion??'')}</p></section><section><b>교정 행동</b><p>{String(d.action??item.reason)}</p></section></>}<label>메모<textarea value={notes} onChange={event=>setNotes(event.target.value)} placeholder="이번 Review에서 확인한 점"/></label>{error&&<p className="team-error" role="alert">{error}</p>}</div><footer><button className="button" disabled={busy} onClick={()=>void save('fail')}><RotateCcw size={16}/>재현 실패</button><button className="button primary" disabled={busy} onClick={()=>void save('success')}><Check size={16}/>재현 성공</button></footer></aside></div>;
}

export default function UnifiedReviewQueue(){
 const [queue,setQueue]=useState<Queue>(empty),[selected,setSelected]=useState<ReviewItem>(),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{setQueue(await archiveApi<Queue>('/api/learning-intelligence/reviews?view=queue'));}catch(e){setError(e instanceof Error?e.message:'Review Queue를 불러오지 못했습니다.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const groups:[keyof Pick<Queue,'overdue'|'today'|'upcoming'>,string][]=[['overdue','Overdue'],['today','Today'],['upcoming','Upcoming']];
 return <div className="unified-review"><div className="review-queue-head"><div><span className="eyebrow">REVIEW</span><h2>오늘 재현할 판단 기준</h2><p>학습일은 오전 6시 기준으로 계산됩니다.</p></div><button className="text-button" onClick={()=>void load()} disabled={loading}>새로고침</button></div><div className="review-counts"><span>연체 <b>{queue.counts.overdue}</b></span><span>오늘 <b>{queue.counts.today}</b></span><span>예정 <b>{queue.counts.upcoming}</b></span></div>{error&&<p className="team-error" role="alert">{error}</p>}{loading?<p>Review Queue를 불러오는 중…</p>:groups.map(([key,label])=><section className="review-group" key={key}><div className="section-title"><h3>{label}</h3><span>{queue[key].length}개</span></div>{queue[key].length?<div className="review-rows">{queue[key].map(item=><button className="review-row" key={item.id} onClick={()=>setSelected(item)}><span className="card-label">{labels[item.targetType]} · {subject[item.subject]??item.subject}</span><b>{item.title}</b><small>{item.reason||'판단 기준을 다시 재현하세요.'}</small><em>{key==='upcoming'?format(item.scheduledAt):key==='today'?'오늘':'연체'} {item.priority>0?`· Priority ${item.priority}`:''}</em></button>)}</div>:<p className="review-empty">예정된 Review가 없습니다.</p>}</section>)}{selected&&<ReviewDetail item={selected} onClose={()=>setSelected(undefined)} onSaved={()=>void load()}/>}</div>;
}
