import { useCallback, useEffect, useState } from 'react';
import { Check, RotateCcw, X } from 'lucide-react';
import { archiveApi } from '../../lib/archiveApi';
import { RichMathText, TextArea } from '../Ui';

type Item={id:string;targetType:'wrong_answer'|'core_rule'|'drill'|'learning_item';subject:string;title:string;reason:string;scheduledAt:string;priority:number;notes:string;detail:Record<string,unknown>};
type Queue={overdue:Item[];today:Item[];upcoming:Item[];counts:{overdue:number;today:number;upcoming:number}};
const empty:Queue={overdue:[],today:[],upcoming:[],counts:{overdue:0,today:0,upcoming:0}};
const labels:Record<Item['targetType'],string>={core_rule:'CORE RULE',wrong_answer:'WRONG ANSWER',learning_item:'LEARNING ARCHIVE',drill:'DRILL'};
const subjects:Record<string,string>={korean:'국어',math:'수학',english:'영어'};
const format=(value:string)=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric'}).format(new Date(value));

export default function UnifiedReviewQueue(){
 const [queue,setQueue]=useState<Queue>(empty),[selected,setSelected]=useState<Item>(),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{setError('');try{setQueue(await archiveApi<Queue>('/api/learning-intelligence/reviews?view=queue'));}catch(cause){setError(cause instanceof Error?cause.message:'Review Queue를 불러오지 못했습니다.')}},[]);
 useEffect(()=>{void load()},[load]);
 const save=async(result:'success'|'fail')=>{if(!selected||busy)return;setBusy(true);try{await archiveApi(`/api/learning-intelligence/reviews/${encodeURIComponent(selected.id)}`,'PATCH',{result,notes});setSelected(undefined);await load();}catch(cause){setError(cause instanceof Error?cause.message:'Review 결과를 저장하지 못했습니다.')}finally{setBusy(false)}};
 const groups:[keyof Pick<Queue,'overdue'|'today'|'upcoming'>,string][]=[['overdue','Overdue'],['today','Today'],['upcoming','Upcoming']];
 return <div className="unified-review"><div className="review-queue-head"><div><span className="eyebrow">REVIEW</span><h2>오늘 재현할 판단 기준</h2><p>학습일은 오전 6시 기준으로 계산됩니다.</p></div><button className="text-button" onClick={()=>void load()}>새로고침</button></div><div className="review-counts"><span>연체 <b>{queue.counts.overdue}</b></span><span>오늘 <b>{queue.counts.today}</b></span><span>예정 <b>{queue.counts.upcoming}</b></span></div>{error&&<p role="alert" className="team-error">{error}</p>}{groups.map(([key,label])=><section className="review-group" key={key}><div className="section-title"><h3>{label}</h3><span>{queue[key].length}개</span></div>{queue[key].length?<div className="review-rows">{queue[key].map(item=><button className="review-row" key={item.id} onClick={()=>{setSelected(item);setNotes(item.notes);}}><span className="card-label">{labels[item.targetType]} · {subjects[item.subject]??item.subject}</span><b>{item.title}</b><small>{item.reason||'판단 기준을 다시 재현하세요.'}</small><em>{key==='upcoming'?format(item.scheduledAt):key==='today'?'오늘':'연체'}{item.priority>0?` · Priority ${item.priority}`:''}</em></button>)}</div>:<p className="review-empty">예정된 Review가 없습니다.</p>}</section>)}{selected&&<div className="sheet-backdrop" onClick={()=>!busy&&setSelected(undefined)}><aside className="detail-sheet review-detail" role="dialog" aria-modal="true" aria-label="Review 상세" onClick={event=>event.stopPropagation()}><header><div><span className="eyebrow">{labels[selected.targetType]}</span><h2>{selected.title}</h2><p>{subjects[selected.subject]??selected.subject} · {format(selected.scheduledAt)}</p></div><button className="icon-button" onClick={()=>setSelected(undefined)} aria-label="닫기"><X/></button></header><div className="sheet-content review-detail-content"><section><b>교정 기준</b><div className="math-record-output"><RichMathText value={selected.reason||String(selected.detail.content??'')} fallback="기록 없음"/></div></section>{selected.targetType==='wrong_answer'&&<><section><b>잘못된 판단</b><div className="math-record-output"><RichMathText value={String(selected.detail.wrongJudgment??'')} fallback="미기록"/></div></section><section><b>놓친 단서</b><div className="math-record-output"><RichMathText value={String(selected.detail.missedCue??'')} fallback="미기록"/></div></section></>}{selected.targetType==='drill'&&<section><b>성공 기준</b><div className="math-record-output"><RichMathText value={String(selected.detail.successCriterion??'')} fallback="미기록"/></div></section>}<label>메모<TextArea value={notes} onChange={setNotes} placeholder="이번 Review에서 확인한 점"/></label></div><footer><button className="button" disabled={busy} onClick={()=>void save('fail')}><RotateCcw size={16}/>재현 실패</button><button className="button primary" disabled={busy} onClick={()=>void save('success')}><Check size={16}/>재현 성공</button></footer></aside></div>}</div>;
}
