import { useMemo, useState } from 'react';
import { signalPriority } from '../../lib/teacherSignals';
import { learningAnalytics, formatStudyTime } from '../../lib/teacherAnalytics';
import { Empty, SectionTitle } from '../Ui';
import SegmentedControl from '../navigation/SegmentedControl';
import { FeedbackComposer, FeedbackHistory, Insight, SignalCards, StatusBadge, TeacherDialog, type EvidenceTarget } from './shared';
import type { TeacherDashboardProps } from './types';
import { ResourcesPanel } from './MathPanels';
import ArenaReviewPanel from './ArenaReviewPanel';
import { EffortOutcomePanel, ExecutionPanel, SubjectStatus, WeeklyGoalsPanel } from './LearningPanels';
const tabs=['Overview','Execution','Subjects','Weekly Goals','Teacher Signals','Schedule / Load','Trends','Resources','ARENA','Feedback'] as const;
type Tab=typeof tabs[number];
export default function LearningManagerDashboard({data,range,feedback,busy,canFeedback,onFeedback,onSignalAction}:TeacherDashboardProps) {
  const [tab,setTab]=useState<Tab>('Overview'),[request,setRequest]=useState<EvidenceTarget>(),[requestSubject,setRequestSubject]=useState<'국어'|'수학'|'영어'|'탐구'>('수학');
  const analysis=useMemo(()=>learningAnalytics(data,range),[data,range]);
  const [evidence,setEvidence]=useState<string>();
  const signalCards=<SignalCards items={feedback} role="academic_manager" onAction={onSignalAction} onEvidence={setEvidence} busy={busy||!canFeedback}/>;
  const statuses=<SubjectStatus analysis={analysis} setTab={setTab}/>;
  const execution=<ExecutionPanel analysis={analysis}/>;
  const effort=<EffortOutcomePanel analysis={analysis}/>;
  const attention=<section><SectionTitle title="Attention Required" meta="교사 판단 → 실행 누락 → 재진단"/><SignalCards items={feedback.filter(item=>item.signal&&['open','accepted'].includes(item.signal.status))} role="academic_manager" onAction={onSignalAction} onEvidence={setEvidence} busy={busy||!canFeedback}/>{analysis.subjects.filter(item=>item.reassess||item.plans.some(plan=>!plan.done)||item.repeated.length).map(item=><article className="teacher-attention" key={item.subject}><StatusBadge value={item.reassess||item.repeated.length?'high':'medium'}/><h3>{item.subject} · {item.reassess?'학습량 증가 · Drill 완료 · 성과 정체':item.repeated.length?'반복 오류 진단 검토 필요':'Execution gap detected'}</h3><p>{item.reassess?`${formatStudyTime(item.previousSeconds)} → ${formatStudyTime(item.seconds)} · 평균 변화 ${item.delta?.toFixed(1)}점`:`계획 ${item.plans.length}회 · 실행 ${item.plans.filter(plan=>plan.done).length}회 · 반복 오류 분류 ${item.repeated.length}개`}</p><div className="teacher-actions"><button className="button" onClick={()=>setTab('Execution')}>시간 배치 · 관련 기록 확인</button>{canFeedback&&<button className="button" onClick={()=>{setRequestSubject(item.subject);setRequest({type:'subject_progress',id:item.subject,title:`${item.subject} 재진단 요청`,evidence:`기간 ${range.start} ~ ${range.end}. 학습량 ${formatStudyTime(item.previousSeconds)} → ${formatStudyTime(item.seconds)}, 성적 평균 변화 ${item.delta!==undefined?item.delta.toFixed(1):'분석 불가'}, Drill 완료 ${item.drills.filter(drill=>drill.done).length}/${item.drills.length}. 반복 오류 ${item.repeated.map(pattern=>pattern.label).join(', ')||'미확인'}`});}}>과목 선생님에게 재진단 요청</button>}</div></article>)}{!analysis.subjects.some(item=>item.reassess||item.repeated.length||item.plans.some(plan=>!plan.done))&&<Empty title="자동으로 발견된 실행 이상이 없습니다." description="계획·학습 시간·성적 기록이 없는 과목은 정상으로 판단하지 않습니다."/>}</section>;
  const goals=<WeeklyGoalsPanel analysis={analysis} data={data} signalCards={signalCards}/>;
  const prioritySignal=useMemo(()=>feedback.filter(item=>item.signal?.targetRole==='academic_manager'&&['open','accepted'].includes(item.signal.status)).slice().sort((a,b)=>signalPriority(a.signal!.priority)-signalPriority(b.signal!.priority))[0],[feedback]);
  const overview=<><Insight label="LEARNING SYSTEM · PRIORITY" title={prioritySignal?`${prioritySignal.signal!.subject} · ‘${prioritySignal.bottleneck||prioritySignal.title||'과목 진단'}’의 개입이 우선입니다.`:analysis.subjects.some(item=>item.status==='Attention')?'학습량과 성과 사이의 병목을 먼저 확인하세요.':analysis.plans.some(item=>!item.done)?'완료되지 않은 계획의 시간 배치를 점검하세요.':'전체 학습 시스템을 판단할 근거를 확인하세요.'}><div className="teacher-facts"><span>계획 실행률 <b>{analysis.executionRate!==undefined?`${analysis.executionRate}%`:'데이터 부족'}</b></span><span>순공 <b>{formatStudyTime(analysis.totalSeconds)}</b></span><span>능력 목표 <b>{analysis.goals.filter(item=>item.done).length} / {analysis.goals.length}</b></span><span>미해결 Signal <b>{feedback.filter(item=>item.signal?.targetRole==='academic_manager'&&['open','accepted'].includes(item.signal.status)).length}</b></span></div></Insight>{statuses}<div className="teacher-quick-links"><button onClick={()=>setTab('Resources')}><b>Resources</b><span>교재 진행 · {data.resources.length}개</span></button><button onClick={()=>setTab('ARENA')}><b>ARENA</b><span>성장 기록 · 배지 · 참여 그룹</span></button></div>{attention}</>;
  const refType=evidence?.split(':')[0],refId=evidence?.slice(evidence.indexOf(':')+1);
  const wrong=refType==='wrong_answer'?data.wrongAnswerDrills.find(item=>item.id===refId):undefined;
  const score=refType==='mock_exam'?data.scores.find(item=>item.id===refId):undefined;
  return <><nav><SegmentedControl label="Learning Control Center" options={tabs.map(id=>({id,label:id}))} value={tab} onChange={setTab} className="teacher-tabs"/></nav><div role="tabpanel" aria-label={tab}>{tab==='Overview'?overview:tab==='Execution'?<>{execution}{effort}</>:tab==='Subjects'?<>{statuses}{effort}</>:tab==='Weekly Goals'?goals:tab==='Teacher Signals'?signalCards:tab==='Schedule / Load'?<>{execution}<p>계획 건수와 명시된 시간으로 부하를 점검합니다. 자유 기록을 시간으로 추정하지 않습니다.</p></>:tab==='Trends'?effort:tab==='Resources'?<ResourcesPanel data={data}/>:tab==='ARENA'?<ArenaReviewPanel data={data} range={range}/>:<>{canFeedback&&<FeedbackComposer role="academic_manager" subject="수학" onSubmit={onFeedback} busy={busy}/>}<FeedbackHistory items={feedback}/></>}</div>
  {request&&<TeacherDialog title="과목 재진단 요청" onClose={()=>setRequest(undefined)}><FeedbackComposer role="academic_manager" subject={requestSubject} target={request} onSubmit={async draft=>{await onFeedback(draft);setRequest(undefined);}} busy={busy}/></TeacherDialog>}
  {evidence&&<TeacherDialog title="Signal · 근거 기록" onClose={()=>setEvidence(undefined)}>{wrong?<><h3>{wrong.subject} · {wrong.question||wrong.source}</h3><small>{wrong.date}</small>{[['잘못된 판단',wrong.wrongJudgment],['놓친 단서',wrong.missedCue],['교정',wrong.correction],['Transfer',wrong.transfer]].map(([label,value])=><p key={label}><b>{label}</b><br/>{value||'미기록'}</p>)}</>:score?<><h3>{score.name}</h3><p>{score.date} · 국어 {score.korean??'미기록'} · 수학 {score.math??'미기록'} · 영어 {score.english??'미기록'}</p></>:<><p>연결된 개별 기록이 없거나 열람 권한이 없습니다. Signal의 관찰 내용과 실행 현황을 함께 확인하세요.</p><button className="button" onClick={()=>{setEvidence(undefined);setTab('Execution');}}>관련 실행 데이터 분석</button></>}</TeacherDialog>}</>;
}
