import type { ReactNode } from 'react';
import { learningAnalytics, formatStudyTime, type TeacherData } from '../../lib/teacherAnalytics';
import { Card, Empty, SectionTitle } from '../Ui';
import { StatusBadge } from './shared';
type Analysis=ReturnType<typeof learningAnalytics>;
export function SubjectStatus({analysis,setTab}:{analysis:Analysis;setTab:(tab:'Subjects')=>void}) { return <section><SectionTitle title="System Status" meta="실행·반복 오류 기반"/><div className="teacher-subject-status">{analysis.subjects.map(item=><button key={item.subject} onClick={()=>setTab('Subjects')}><b>{item.subject}</b><StatusBadge value={item.status}/></button>)}</div></section>; }

export function ExecutionPanel({analysis}:{analysis:Analysis}) { return <section><SectionTitle title="Plan vs Execution" meta="완료율은 계획 건수 기준"/>{analysis.subjects.map(item=><Card key={item.subject}><div className="teacher-row-head"><h3>{item.subject}</h3><b>{formatStudyTime(item.seconds)}</b></div><div className="teacher-facts"><span>계획 완료 <b>{item.plans.filter(plan=>plan.done).length} / {item.plans.length}</b></span><span>명시된 계획 시간 <b>{item.plannedMinutes?formatStudyTime(item.plannedMinutes*60):'시간 기록 없음'}</b></span></div><p>{item.timedPlanCount<item.plans.length?'시간이 없는 계획이 포함되어 시간 실행률을 계산하지 않습니다.':item.plannedMinutes?`시간 실행률 ${Math.round(item.seconds/60/item.plannedMinutes*100)}%`:'시간 실행률 · 분석 불가'}</p><details><summary>계획과 성과 근거 확인</summary>{item.plans.map(plan=><p key={plan.id}>{plan.date} · {plan.title} · {plan.quantity||'시간 미기록'} · {plan.done?'완료':'미완료'}</p>)}<p>선택 기간 성적 기록 {item.scores.length}건 · 이전 같은 기간 대비 {item.delta!==undefined?`${item.delta>0?'+':''}${item.delta.toFixed(1)}점`:'비교 기록 부족'}</p></details></Card>)}</section>; }

export function EffortOutcomePanel({analysis}:{analysis:Analysis}) { return <section><SectionTitle title="Effort vs Outcome" meta="시간: 명시된 계획 대비 · 성과: 이전 같은 기간 평균 대비"/>{analysis.subjects.map(item=><div className="teacher-effort-row" key={item.subject}><b>{item.subject}</b><div><h3>{item.effort===undefined||item.outcome===undefined?'분류에 필요한 데이터가 부족합니다.':item.effort?item.outcome?'HIGH EFFORT + HIGH OUTCOME · 유지':'HIGH EFFORT + LOW OUTCOME · 병목 진단 필요':item.outcome?'LOW EFFORT + HIGH OUTCOME · 효율적':'LOW EFFORT + LOW OUTCOME · 실행 개입 필요'}</h3><p>{formatStudyTime(item.seconds)} · 성적 변화 {item.delta!==undefined?`${item.delta.toFixed(1)}점`:'비교 불가'}</p><small>다른 시험의 난도 차이는 반영하지 않는 단순 기록 비교입니다.</small></div></div>)}</section>; }

export function WeeklyGoalsPanel({analysis,data,signalCards}:{analysis:Analysis;data:TeacherData;signalCards:ReactNode}) { return <section><SectionTitle title="Weekly Capability Goals" meta="학생 원본 목표 · 교사는 제안"/>{analysis.goals.length?analysis.goals.map(goal=><Card key={goal.id}><div className="teacher-row-head"><h3>{goal.subject} · {goal.ability}</h3><StatusBadge value={goal.done?'Resolved':'open'}/></div><p>{goal.successCriterion}</p><p>{goal.drillDesign}</p><small>연결 Drill {data.dailyDrills.filter(item=>item.capabilityGoalId===goal.id||goal.feedbackId&&item.feedbackId===goal.feedbackId).length}건</small></Card>):<Empty>선택 기간의 능력 목표가 없습니다.</Empty>}{signalCards}</section>; }
