import type { Subject } from '../../types';
import type { Feedback } from '../../lib/feedback';
import { mathAnalytics, subjectScore, type DateRange, type TeacherData } from '../../lib/teacherAnalytics';
import { Card, Empty, Progress, SectionTitle } from '../Ui';
import SegmentedControl from '../navigation/SegmentedControl';
import { FeedbackComposer, StatusBadge, TeacherDialog, type EvidenceTarget, type FeedbackDraft } from './shared';
type Analysis=ReturnType<typeof mathAnalytics>;
type InspectorAction=(id:string,type?:EvidenceTarget['type'])=>void;
export function WrongAnswerPatterns({analysis,filter,setFilter,inspect}:{analysis:Analysis;filter:string;setFilter:(value:string)=>void;inspect:InspectorAction}) { return <section><SectionTitle title="Wrong Answer Patterns" meta="분류는 학생 기록 기준"/><SegmentedControl label="오류 패턴 필터" options={['전체',...analysis.patterns.map(item=>item.label)].map(id=>({id,label:id}))} value={filter} onChange={setFilter} className="teacher-filter"/>{analysis.patterns.filter(item=>filter==='전체'||item.label===filter).map(pattern=><Card key={pattern.label}><h3>{pattern.label} · {pattern.records.length}회</h3>{pattern.records.map(item=><button className="row-link" key={item.id} onClick={()=>inspect(item.id)}><span><b>{item.question||item.source}</b><small>{item.date} · {item.source}<br/>{item.missedCue||item.wrongJudgment||'단서 기록 필요'}</small></span><span>분석 →</span></button>)}</Card>)}{!analysis.wrong.length&&<Empty title="오답 기록이 없습니다." description="학생이 오답을 기록하면 날짜순 목록 대신 오류 패턴으로 연결됩니다."/>}</section>; }

export function CapabilityPanel({data,analysis,subject,range}:{data:TeacherData;analysis:Analysis;subject:Subject;range:DateRange}) { return <section><SectionTitle title="Capability Evidence" meta="능력 점수 없음 · 기록에 근거한 상태"/><p>오답 분류는 주의 신호입니다. 기록이 없다는 이유로 강점으로 판단하지 않습니다.</p>{[
    {label:'조건 · 발문 해석',pattern:'발문·해석'},{label:'필요충분 · 전략 판단',pattern:'전략·판단'},{label:'개념',pattern:'개념 공백'},{label:'계산 안정성',pattern:'계산 실수'},{label:'시간 관리',pattern:'시간 관리'},{label:'논리 완결성',pattern:''},{label:'그래프 해석',pattern:''},{label:'재현성',pattern:''}
  ].map(axis=>{const records=analysis.wrong.filter(item=>axis.pattern&&item.bottleneck===axis.pattern);return <div className="teacher-capability" key={axis.label}><b>{axis.label}</b><span>{records.length?`오답 근거 ${records.length}건`:'독립 평가 기록 없음'}</span><StatusBadge value={records.length?'Attention':'데이터 부족'}/></div>;})}<h3>Trinity · 학습 분석 근거</h3>{data.trinity?.filter(item=>item.subject===subject&&item.date>=range.start&&item.date<=range.end).slice(-3).map(item=><details key={item.id}><summary>{item.date} · 학생 Trinity 분석</summary>{Object.entries(item.fields).filter(([,value])=>value).map(([label,value])=><p key={label}><b>{label}</b><br/>{value}</p>)}</details>)}{!data.trinity?.some(item=>item.subject===subject)&&<p>열람 가능한 Trinity 분석 기록이 없습니다.</p>}<h3>Weekly Capability Goals</h3>{analysis.goals.length?analysis.goals.map(goal=><Card key={goal.id}><h3>{goal.ability}</h3><p>{goal.successCriterion}</p><p>{goal.drillDesign}</p><StatusBadge value={goal.done?'Resolved':'open'}/><small>학생이 기록한 목표 완료 상태</small></Card>):<Empty>선택 기간의 수학 능력 목표가 없습니다.</Empty>}</section>; }

export function MockExamPanel({analysis,subject,inspect}:{analysis:Analysis;subject:Subject;inspect:InspectorAction}) { return <Card><SectionTitle title="Mock Exams" meta={`${analysis.scores.length}건`}/>{analysis.scores.length?analysis.scores.slice().reverse().map(item=><button className="row-link" key={item.id} onClick={()=>inspect(item.id,'mock_exam')}><span><b>{item.name}</b><small>{item.date} · {item.duration!==undefined?`${item.duration}분`:'시간 기록 없음'}</small></span><b>{subjectScore(item,subject)}점</b></button>):<Empty>선택 기간의 실모 성적이 없습니다.</Empty>}</Card>; }

export function DrillPanel({data,analysis,feedback}:{data:TeacherData;analysis:Analysis;feedback:Feedback[]}) { return <section><SectionTitle title="Drill · Intervention Review" meta="완료는 성공률과 다릅니다."/>{analysis.drills.length?analysis.drills.map(item=>{const goal=data.weeklyCapabilityGoals.find(goal=>goal.id===item.capabilityGoalId);const note=feedback.find(note=>note.id===item.feedbackId);return <Card key={item.id}><div className="teacher-row-head"><h3>{item.title}</h3><StatusBadge value={item.done?'Resolved':'open'}/></div><p>{item.action}</p><p>성공 기준 · {item.successCriterion||'미기록'}</p><small>{item.date} · {item.minutes}분{goal&&` · 목표: ${goal.ability}`}{note&&` · Signal: ${note.title}`}</small></Card>;}):<Empty>선택 기간의 Daily Drill 기록이 없습니다.</Empty>}</section>; }

export function ResourcesPanel({data,subject}:{data:TeacherData;subject?:Subject}) { return <section><SectionTitle title="Resources" meta="현재 교재 진행 상태"/>{data.resources.filter(item=>!subject||item.subject===subject).map(item=><Card key={item.id}><div className="teacher-row-head"><h3>{item.name}</h3><StatusBadge value={item.subject}/></div><Progress value={item.done} max={item.total}/><small>{item.done} / {item.total}</small></Card>)}{!data.resources.some(item=>!subject||item.subject===subject)&&<Empty>연결된 교재가 없습니다.</Empty>}</section>; }

export function ProblemInspector({data,target,analysis,subject,range,canFeedback,busy,onFeedback,inspect,onClose}:{data:TeacherData;target:EvidenceTarget;analysis:Analysis;subject:Subject;range:DateRange;canFeedback:boolean;busy:boolean;onFeedback:(draft:FeedbackDraft)=>Promise<void>;inspect:InspectorAction;onClose:()=>void}) {
 const wrong=target.type==='wrong_answer'?data.wrongAnswerDrills.find(item=>item.id===target.id&&item.subject===subject):undefined;
 const score=target.type==='mock_exam'?data.scores.find(item=>item.id===target.id&&subjectScore(item,subject)!==undefined):undefined;
 return <TeacherDialog title="문항 분석" inspector onClose={onClose}><span className="eyebrow">EVIDENCE · STUDENT RECORD</span><h3>{target.title}</h3>{target.type==='subject_progress'&&<><p>선택 기간 {range.start} ~ {range.end}</p><p>학습 시간 · {Math.floor(data.sessions.filter(item=>item.subject===subject&&item.date>=range.start&&item.date<=range.end).reduce((sum,item)=>sum+item.seconds,0)/60)}분</p><p>Drill 완료 · {analysis.drills.filter(item=>item.done).length} / {analysis.drills.length}</p>{analysis.scores.map(item=><button className='row-link' key={item.id} onClick={()=>inspect(item.id,'mock_exam')}>{item.date} · {item.name} · {subjectScore(item,subject)}점 →</button>)}<p>성적 정체는 학습 선생님의 관찰입니다. 난도와 문항별 오류 근거를 검토해 전문 진단을 작성하세요.</p></>}{wrong?<><small>{wrong.date} · {wrong.source}</small>{[['잘못된 판단',wrong.wrongJudgment],['놓친 단서',wrong.missedCue],['교정',wrong.correction],['Transfer',wrong.transfer]].map(([label,value])=><section className="teacher-inspector-field" key={label}><b>{label}</b><p>{value||'미기록'}</p></section>)}<h3>재도전 기록</h3>{wrong.retries?.length?wrong.retries.map(retry=><p key={retry.id}>{retry.label} · {retry.completedDate?`완료 ${retry.completedDate}`:`예정 ${retry.dueDate}`}</p>):<p>재도전 기록 없음 · 완료 여부를 성공률로 환산하지 않습니다.</p>}{wrong.scoreId&&<button className="text-button" onClick={()=>inspect(wrong.scoreId!,'mock_exam')}>연결 실모 확인</button>}</>:score?<><p>{score.date} · {subjectScore(score,subject)}점</p><p>{score.duration!==undefined?`풀이 시간 ${score.duration}분`:'시간 기록 없음'}</p><p>기록된 오류 유형 · {score.errorType||'미기록'}</p><h3>연결 오답</h3>{data.wrongAnswerDrills.filter(item=>item.scoreId===score.id&&item.subject===subject).map(item=><button className="row-link" key={item.id} onClick={()=>inspect(item.id)}>{item.question||item.source} →</button>)}</>:null}{canFeedback&&<FeedbackComposer key={target.id} role="subject_teacher" subject={subject} target={target} onSubmit={onFeedback} busy={busy}/>}</TeacherDialog>;
}
