import { useMemo, useState } from 'react';
import type { ActiveCoreRule, CoreRuleIntelligence } from '../../lib/archiveApi';
import { filterAndSortTeacherCoreRules, type TeacherCoreRuleSort } from '../../lib/teacherWorkspace';
import { Empty } from '../Ui';
const subject:Record<string,string>={math:'수학',korean:'국어',english:'영어'};
const status:Record<string,string>={ACTIVE:'집중 교정',WATCH:'관찰',MASTERED:'체화',ARCHIVED:'안정'};
const mastery:Record<string,string>={input:'입력',understanding:'이해',reproduction:'재현',automated:'자동화'};
const sortLabels:Record<TeacherCoreRuleSort,string>={priority:'우선순위',recent_failure:'최근 실패',failures:'실패 많은순',recent_use:'최근 사용',lowest_mastery:'숙련도 낮은순',title:'제목순'};
const metric=(label:string,value:string|number|null|undefined)=><div key={label}><span>{label}</span><b>{value??'—'}</b></div>;
export default function TeacherCoreRulePanel({rules,error,onOpen,detail}:{rules:ActiveCoreRule[]|null;error?:string;onOpen:(id:string)=>void;detail?:CoreRuleIntelligence|null}){
 const [query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState(''),[masteryFilter,setMasteryFilter]=useState(''),[sort,setSort]=useState<TeacherCoreRuleSort>('priority'),[selectedId,setSelectedId]=useState<string>();
 const visible=useMemo(()=>filterAndSortTeacherCoreRules(rules??[],{query,status:statusFilter,mastery:masteryFilter,sort}),[rules,query,statusFilter,masteryFilter,sort]); const selected=visible.find(x=>x.id===selectedId)??visible[0];
 return <section className="tutor-panel teacher-core-workspace"><header className="tutor-panel-head"><div><span className="eyebrow">CORE RULE</span><h2>핵심 판단 규칙</h2></div><small>{visible.length}개</small></header>{error&&<p className="team-error" role="alert">{error}</p>}<div className="teacher-filter-grid teacher-core-toolbar"><input aria-label="Core Rule 검색" placeholder="검색" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Core Rule 상태" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">상태</option>{Object.entries(status).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="Core Rule 숙련도" value={masteryFilter} onChange={e=>setMasteryFilter(e.target.value)}><option value="">숙련도</option>{Object.entries(mastery).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="Core Rule 정렬" value={sort} onChange={e=>setSort(e.target.value as TeacherCoreRuleSort)}>{Object.entries(sortLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>{rules===null?<p>Core Rule을 불러오는 중…</p>:visible.length?<div className="teacher-core-master-detail"><div className="teacher-core-list">{visible.map(x=><button type="button" key={x.id} className={`teacher-core-row ${selected?.id===x.id?'selected':''}`} onClick={()=>{setSelectedId(x.id);onOpen(x.id)}}><small>{subject[x.subject]??x.subject} · {status[x.status]??x.status}</small><b>{x.title}</b><p>{x.content}</p><footer><span>P {x.priorityScore}</span><span>최근 7일 실패 {x.stats.failures7d}</span><span>Archive {x.stats.archiveCount}</span><span>Review {x.stats.reviewCount}</span></footer></button>)}</div><CoreDetail rule={selected} detail={detail?.coreRule?.id===selected?.id?detail:undefined} onClose={()=>setSelectedId(undefined)}/></div>:<Empty title="연결된 Core Rule이 없습니다." description="검색 또는 필터 조건에 맞는 Rule이 없습니다."/>}</section>;
}
function CoreDetail({rule,detail,onClose}:{rule?:ActiveCoreRule;detail?:CoreRuleIntelligence;onClose:()=>void}){
 if(!rule)return <aside className="teacher-core-detail teacher-detail-empty"><Empty title="Core Rule을 선택하세요." description="왼쪽 목록에서 규칙을 선택하세요."/></aside>; const s=rule.stats;
 return <aside className="teacher-core-detail" aria-label="Core Rule 상세"><header><div><span className="eyebrow">{status[rule.status]??rule.status} · PRIORITY {rule.priorityScore}</span><h2>{rule.title}</h2><div className="teacher-detail-chips"><span>{subject[rule.subject]??rule.subject}</span><span>{mastery[rule.masteryStatus]??rule.masteryStatus}</span><span>{status[rule.status]??rule.status}</span></div></div><button className="icon-button teacher-detail-close" aria-label="상세 닫기" onClick={onClose}>×</button></header><div className="teacher-detail-body"><p className="teacher-rule-content">{rule.content}</p><section><h3>Metrics</h3><div className="teacher-metric-grid">{metric('최근 7일 실패',s.failures7d)}{metric('최근 30일 실패',s.failures30d)}{metric('Wrong Answer',s.wrongAnswerCount)}{metric('Drill',s.drillCount)}{metric('Review 성공',s.reviewSuccessCount)}{metric('Review 실패',s.reviewFailureCount)}{metric('숙련률',s.masteryRate===null?null:`${Math.round(s.masteryRate*100)}%`)}</div><p className="teacher-detail-dates">최근 사용 {s.lastOccurrenceAt?.slice(0,10)??'—'} · 최근 실패 {s.lastFailureAt?.slice(0,10)??'—'}</p></section>{detail&&<><section><h3>Related Data</h3><div className="teacher-related-summary"><span>Archive {detail.linkedItems.length}</span><span>Wrong Answer {detail.wrongAnswers.length}</span><span>Drill {detail.drills.length}</span><span>Review {detail.reviews.length}</span></div></section><section><h3>Evidence Timeline</h3><div className="teacher-evidence-timeline">{detail.evidence.length?detail.evidence.map(x=><article key={`${x.sourceType}:${x.sourceId}:${x.occurredAt}`}><time>{x.occurredAt?.slice(0,10)}</time><b>{x.sourceType==='wrong_answer'?'Wrong Answer':x.sourceType==='drill'?'Drill':x.sourceType==='review'?'Review':'Archive'}</b><span>{x.relationType==='failed'?'실패':x.relationType==='reinforced'?'강화':x.relationType==='applied'?'적용':'도출'}</span></article>):<p>표시할 Evidence가 없습니다.</p>}</div></section></>}</div></aside>;
}