import { useMemo, useState } from 'react';
import { ArrowRight, Search } from 'lucide-react';
import type { ActiveCoreRule, ArchiveSubject, CoreRuleIntelligence } from '../../lib/archiveApi';
import { filterAndSortTeacherCoreRules, type TeacherCoreRuleSort } from '../../lib/teacherWorkspace';
import { Empty } from '../Ui';

const labels:Record<TeacherCoreRuleSort,string>={priority:'우선순위',recent_failure:'최근 실패',failures:'실패 많은 순',recent_use:'최근 사용',lowest_mastery:'숙련 낮은 순',title:'이름순'};
const statusCopy:Record<string,string>={ACTIVE:'집중 교정',WATCH:'관찰',MASTERED:'체화',ARCHIVED:'안정'};
const masteryCopy:Record<string,string>={input:'입력',understanding:'이해',reproduction:'재현',automated:'자동화'};
const subjectCopy:Record<ArchiveSubject,string>={korean:'국어',math:'수학',english:'영어'};
const date=(value:string|null|undefined)=>value?value.slice(0,10).replaceAll('-','.'):'—';

export default function TeacherCoreRulePanel({rules,error,onOpen,detail}:{rules:ActiveCoreRule[]|null;error?:string;onOpen:(id:string)=>void;detail?:CoreRuleIntelligence|null}){
 const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[mastery,setMastery]=useState(''),[sort,setSort]=useState<TeacherCoreRuleSort>('priority'),[selectedId,setSelectedId]=useState('');
 const visible=useMemo(()=>filterAndSortTeacherCoreRules(rules??[],{query,status,mastery,sort}),[rules,query,status,mastery,sort]);
 const selected=visible.find(rule=>rule.id===selectedId)??visible[0];
 const open=(rule:ActiveCoreRule)=>{setSelectedId(rule.id);onOpen(rule.id)};
 const intelligence=detail?.coreRule?.id===selected?.id?detail:null;
 return <div className="tutor-panel teacher-core-rules-v2">
   <header className="teacher-core-header"><div><span className="eyebrow">CORE RULE</span><h2>누적 풀이 원칙</h2><p>목록에서 우선순위를 비교하고, 선택한 규칙의 근거와 실패 패턴을 오른쪽에서 확인합니다.</p></div><span className="teacher-core-count">{visible.length} rules</span></header>
   {error&&<p role="alert" className="team-error">{error}</p>}
   <div className="teacher-core-toolbar"><label className="teacher-core-search"><Search size={16}/><input aria-label="Core Rule 검색" placeholder="Core Rule 검색" value={query} onChange={event=>setQuery(event.target.value)}/></label><select aria-label="Core Rule 정렬" value={sort} onChange={event=>setSort(event.target.value as TeacherCoreRuleSort)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="Core Rule 상태" value={status} onChange={event=>setStatus(event.target.value)}><option value="">전체 상태</option>{['ACTIVE','WATCH','MASTERED','ARCHIVED'].map(value=><option key={value} value={value}>{statusCopy[value]}</option>)}</select><select aria-label="Core Rule 숙련 상태" value={mastery} onChange={event=>setMastery(event.target.value)}><option value="">전체 숙련</option>{['input','understanding','reproduction','automated'].map(value=><option key={value} value={value}>{masteryCopy[value]}</option>)}</select></div>
   {rules===null?<p aria-live="polite">Core Rule을 불러오는 중…</p>:visible.length?<div className="teacher-core-master-detail">
     <div className="teacher-core-list" aria-label="Core Rule 목록">{visible.map(rule=><button type="button" key={rule.id} className={`teacher-core-list-item ${selected?.id===rule.id?'active':''}`} onClick={()=>open(rule)}><div className="teacher-core-list-top"><span>{subjectCopy[rule.subject]}</span><span className={`teacher-rule-status status-${rule.status.toLowerCase()}`}>{statusCopy[rule.status]??rule.status}</span><b>P{rule.priorityScore}</b></div><h3>{rule.title}</h3><p>{rule.content}</p><div className="teacher-core-list-metrics"><span>실패 <b>{rule.stats.failures7d}</b></span><span>Archive <b>{rule.stats.archiveCount}</b></span><span>Review <b>{rule.stats.reviewCount}</b></span></div></button>)}</div>
     <section className="teacher-core-detail" aria-live="polite">{selected?<><div className="teacher-core-detail-head"><div><span className={`teacher-rule-status status-${selected.status.toLowerCase()}`}>{statusCopy[selected.status]??selected.status}</span><span>{subjectCopy[selected.subject]}</span><span>{masteryCopy[selected.masteryStatus]??selected.masteryStatus}</span></div><strong>P{selected.priorityScore}</strong></div><h2>{selected.title}</h2><p className="teacher-core-rule-body">{selected.content}</p><div className="teacher-core-stat-grid"><div><span>최근 7일 실패</span><b>{selected.stats.failures7d}</b></div><div><span>최근 30일 실패</span><b>{selected.stats.failures30d}</b></div><div><span>Wrong Answer</span><b>{selected.stats.wrongAnswerCount}</b></div><div><span>Drill</span><b>{selected.stats.drillCount}</b></div><div><span>Review 성공</span><b>{selected.stats.reviewSuccessCount}</b></div><div><span>숙련도</span><b>{selected.stats.masteryRate===null?'—':`${Math.round(selected.stats.masteryRate*100)}%`}</b></div></div><div className="teacher-core-dates"><span>최근 사용 <b>{date(selected.stats.lastOccurrenceAt)}</b></span><span>최근 실패 <b>{date(selected.stats.lastFailureAt)}</b></span></div>{intelligence?<><section className="teacher-core-related"><div><span>Archive</span><b>{intelligence.linkedItems.length}</b></div><div><span>Wrong Answer</span><b>{intelligence.wrongAnswers.length}</b></div><div><span>Drill</span><b>{intelligence.drills.length}</b></div><div><span>Review</span><b>{intelligence.reviews.length}</b></div></section><section className="teacher-core-evidence"><div className="teacher-core-section-title"><div><span className="eyebrow">EVIDENCE</span><h3>최근 근거</h3></div><span>{intelligence.evidence.length}개</span></div>{intelligence.evidence.length?intelligence.evidence.slice(0,8).map(item=><article key={`${item.sourceType}:${item.sourceId}:${item.occurredAt}`}><span>{date(item.occurredAt)}</span><b>{item.sourceType.replace('_',' ')}</b><em>{item.relationType}</em><small>{item.sourceId}</small></article>):<p className="teacher-core-empty">아직 연결된 Evidence가 없습니다.</p>}</section></>:<button className="teacher-core-load-detail" onClick={()=>onOpen(selected.id)}>상세 근거 불러오기 <ArrowRight size={15}/></button>}</>:<Empty title="Core Rule을 선택하세요." description="왼쪽 목록에서 규칙을 선택하면 상세 근거가 표시됩니다."/>}</section>
   </div>:<Empty title="연결된 Core Rule이 없습니다." description="검색 또는 필터 조건에 맞는 Rule이 없습니다."/>}
 </div>;
}
