import { useMemo, useState } from 'react';
import type { ArchiveEntry } from '../../lib/archiveApi';
import { filterAndSortTeacherArchive, type TeacherArchiveSort } from '../../lib/teacherWorkspace';
import { Empty } from '../Ui';

const mastery:Record<string,string>={input:'입력',understanding:'이해',reproduction:'재현',automated:'자동화'};
const sortLabels:Record<TeacherArchiveSort,string>={newest:'최신순',oldest:'오래된순',mastery:'숙련도순',source:'시험 / 자료순',category:'카테고리순'};
const fields:[string,keyof ArchiveEntry][]=[['문제 조건','conditionSummary'],['첫 사고','firstThought'],['표현 / 모델링','representation'],['풀이 흐름','solutionFlow'],['병목','bottleneck'],['전이','transfer'],['Memo','memo'],['핵심 주제','mainIdea'],['구조 요약','structureSummary'],['핵심 표현','keyExpression']];

export default function TeacherArchivePanel({entries,error,onOpenRule}:{entries:ArchiveEntry[];error?:string;onOpenRule?:(id:string)=>void}){
 const [query,setQuery]=useState(''),[source,setSource]=useState(''),[category,setCategory]=useState(''),[masteryFilter,setMasteryFilter]=useState(''),[sort,setSort]=useState<TeacherArchiveSort>('newest'),[selectedId,setSelectedId]=useState<string>();
 const sources=useMemo(()=>[...new Set(entries.map(x=>`${x.examName} ${x.sourceName}`.trim()).filter(Boolean))],[entries]);
 const categories=useMemo(()=>[...new Set(entries.map(x=>x.category).filter(Boolean))],[entries]);
 const visible=useMemo(()=>filterAndSortTeacherArchive(entries,{query,source,category,mastery:masteryFilter,from:'',to:'',sort}),[entries,query,source,category,masteryFilter,sort]);
 const selected=visible.find(x=>x.id===selectedId)??visible[0];
 return <section className="tutor-panel teacher-archive-workspace"><header className="tutor-panel-head"><div><span className="eyebrow">LEARNING ARCHIVE</span><h2>학습 기록</h2></div><small>{visible.length} / {entries.length}개</small></header>{error?<p className="team-error" role="alert">{error}</p>:<><div className="teacher-filter-grid teacher-archive-toolbar"><input aria-label="Archive 검색" placeholder="검색" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="시험 또는 자료" value={source} onChange={e=>setSource(e.target.value)}><option value="">시험 / 자료</option>{sources.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Archive 카테고리" value={category} onChange={e=>setCategory(e.target.value)}><option value="">카테고리</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Archive 숙련도" value={masteryFilter} onChange={e=>setMasteryFilter(e.target.value)}><option value="">숙련도</option>{Object.entries(mastery).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="Archive 정렬" value={sort} onChange={e=>setSort(e.target.value as TeacherArchiveSort)}>{Object.entries(sortLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>{visible.length?<div className="teacher-archive-master-detail"><div className="teacher-archive-list">{visible.map(x=><button type="button" key={x.id} className={`teacher-archive-row ${selected?.id===x.id?'selected':''}`} onClick={()=>setSelectedId(x.id)}><small>{x.studiedAt?.slice(0,10)}</small><b>{x.examName||x.sourceName||x.title}{x.questionNumber?` · ${x.questionNumber}`:''}</b><span>{[x.category,x.subcategory].filter(Boolean).join(' · ')||'분류 없음'}</span><em>{mastery[x.masteryStatus]??x.masteryStatus}</em><footer>Annotation {x.annotations.length} · Core Rule {x.coreRules.length}</footer></button>)}</div><ArchiveDetail entry={selected} onOpenRule={onOpenRule} onClose={()=>setSelectedId(undefined)}/></div>:<Empty title="Learning Archive가 비어 있습니다." description="검색 또는 필터 조건에 맞는 기록이 없습니다."/>}</>}</section>;
}
function ArchiveDetail({entry,onOpenRule,onClose}:{entry?:ArchiveEntry;onOpenRule?:(id:string)=>void;onClose:()=>void}){
 if(!entry)return <aside className="teacher-archive-detail teacher-detail-empty"><Empty title="기록을 선택하세요." description="왼쪽 목록에서 학습 기록을 선택하세요."/></aside>;
 const metadata=[entry.institutionCustomName||entry.institution,entry.examName||entry.sourceName,entry.year?`${entry.year}.${String(entry.month).padStart(2,'0')}`:''].filter(Boolean).join(' · ');
 return <aside className="teacher-archive-detail" aria-label="Learning Archive 상세"><header><div><span className="eyebrow">LEARNING ARCHIVE · READ ONLY</span><h2>{entry.title}</h2><p>{metadata}</p><div className="teacher-detail-chips"><span>{entry.category||'미분류'}</span><span>{entry.studiedAt?.slice(0,10)}</span><span>{mastery[entry.masteryStatus]??entry.masteryStatus}</span></div></div><button className="icon-button teacher-detail-close" aria-label="상세 닫기" onClick={onClose}>×</button></header><div className="teacher-detail-body"><section><h3>풀이 분석</h3><dl className="teacher-analysis-list">{fields.map(([label,key])=>entry[key]?<div key={key}><dt>{label}</dt><dd>{String(entry[key])}</dd></div>:null)}</dl></section>{entry.annotations.length>0&&<section><h3>Annotation</h3><div className="teacher-annotation-list">{entry.annotations.map(x=><article key={x.id} style={{'--annotation-color':x.color} as React.CSSProperties}><i/><b>{x.type}</b><p>{x.text}</p></article>)}</div></section>}{entry.coreRules.length>0&&<section><h3>Linked Core Rules</h3><div className="teacher-linked-rules">{entry.coreRules.map(x=><button type="button" key={x.id} onClick={()=>onOpenRule?.(x.id)}><b>{x.title}</b><span>{x.relationType==='failed'?'적용 실패':x.relationType==='applied'?'적용':x.relationType==='reinforced'?'강화':'도출'}</span><p>{x.content}</p></button>)}</div></section>}</div></aside>;
}